import { MODE_KEYS, type Mode } from "@/lib/mode-keys";

export type ChallengeId =
  | "gratitude-3day"
  | "shared-encouragement-3day"
  | "waiting-5day"
  | "stewardship-7day"
  | "sabbath-rest-5day"
  | "listening-3day"
  | "repair-4day"
  | "generosity-7day"
  | "attention-fast-5day"
  | "hidden-service-5day"
  | "read-with-me-7day";

export type ChallengeDayPrompt = {
  day: number;
  scripture: string;
  principleKey: string;
  promptKey: string;
  practiceKey: string;
  principle: string;
  prompt: string;
  practice: string;
};

export type ChallengeDefinition = {
  id: ChallengeId;
  titleKey: string;
  descriptionKey: string;
  title: string;
  description: string;
  totalDays: number;
  mode: Mode;
  days: ChallengeDayPrompt[];
};

export const challengeDefinitions: ChallengeDefinition[] = [
  {
    id: "gratitude-3day",
    titleKey: "challenges.gratitude3day.title",
    descriptionKey: "challenges.gratitude3day.description",
    title: "",
    description: "",
    totalDays: 3,
    mode: MODE_KEYS.LIFE,
    days: [
      {
        day: 1,
        scripture: "1 Thessalonians 5:18",
        principleKey: "challenges.gratitude3day.day1.principle",
        promptKey: "challenges.gratitude3day.day1.prompt",
        practiceKey: "challenges.gratitude3day.day1.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 2,
        scripture: "Psalm 107:1",
        principleKey: "challenges.gratitude3day.day2.principle",
        promptKey: "challenges.gratitude3day.day2.prompt",
        practiceKey: "challenges.gratitude3day.day2.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 3,
        scripture: "Philippians 4:11",
        principleKey: "challenges.gratitude3day.day3.principle",
        promptKey: "challenges.gratitude3day.day3.prompt",
        practiceKey: "challenges.gratitude3day.day3.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
    ],
  },
  {
    id: "shared-encouragement-3day",
    titleKey: "challenges.sharedEncouragement3day.title",
    descriptionKey: "challenges.sharedEncouragement3day.description",
    title: "",
    description: "",
    totalDays: 3,
    mode: MODE_KEYS.LIFE,
    days: [
      {
        day: 1,
        scripture: "Hebrews 10:24-25",
        principleKey: "challenges.sharedEncouragement3day.day1.principle",
        promptKey: "challenges.sharedEncouragement3day.day1.prompt",
        practiceKey: "challenges.sharedEncouragement3day.day1.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 2,
        scripture: "Proverbs 27:17",
        principleKey: "challenges.sharedEncouragement3day.day2.principle",
        promptKey: "challenges.sharedEncouragement3day.day2.prompt",
        practiceKey: "challenges.sharedEncouragement3day.day2.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 3,
        scripture: "Colossians 3:16",
        principleKey: "challenges.sharedEncouragement3day.day3.principle",
        promptKey: "challenges.sharedEncouragement3day.day3.prompt",
        practiceKey: "challenges.sharedEncouragement3day.day3.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
    ],
  },
  {
    id: "waiting-5day",
    titleKey: "challenges.waiting5day.title",
    descriptionKey: "challenges.waiting5day.description",
    title: "",
    description: "",
    totalDays: 5,
    mode: MODE_KEYS.PURPOSE,
    days: [
      {
        day: 1,
        scripture: "Psalm 27:14",
        principleKey: "challenges.waiting5day.day1.principle",
        promptKey: "challenges.waiting5day.day1.prompt",
        practiceKey: "challenges.waiting5day.day1.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 2,
        scripture: "Proverbs 4:25-26",
        principleKey: "challenges.waiting5day.day2.principle",
        promptKey: "challenges.waiting5day.day2.prompt",
        practiceKey: "challenges.waiting5day.day2.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 3,
        scripture: "Isaiah 40:31",
        principleKey: "challenges.waiting5day.day3.principle",
        promptKey: "challenges.waiting5day.day3.prompt",
        practiceKey: "challenges.waiting5day.day3.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 4,
        scripture: "James 1:5",
        principleKey: "challenges.waiting5day.day4.principle",
        promptKey: "challenges.waiting5day.day4.prompt",
        practiceKey: "challenges.waiting5day.day4.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 5,
        scripture: "Proverbs 3:5-6",
        principleKey: "challenges.waiting5day.day5.principle",
        promptKey: "challenges.waiting5day.day5.prompt",
        practiceKey: "challenges.waiting5day.day5.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
    ],
  },
  {
    id: "stewardship-7day",
    titleKey: "challenges.stewardship7day.title",
    descriptionKey: "challenges.stewardship7day.description",
    title: "",
    description: "",
    totalDays: 7,
    mode: MODE_KEYS.MONEY,
    days: [
      {
        day: 1,
        scripture: "Deuteronomy 8:18",
        principleKey: "challenges.stewardship7day.day1.principle",
        promptKey: "challenges.stewardship7day.day1.prompt",
        practiceKey: "challenges.stewardship7day.day1.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 2,
        scripture: "Proverbs 21:5",
        principleKey: "challenges.stewardship7day.day2.principle",
        promptKey: "challenges.stewardship7day.day2.prompt",
        practiceKey: "challenges.stewardship7day.day2.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 3,
        scripture: "Luke 16:10",
        principleKey: "challenges.stewardship7day.day3.principle",
        promptKey: "challenges.stewardship7day.day3.prompt",
        practiceKey: "challenges.stewardship7day.day3.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 4,
        scripture: "Romans 13:8",
        principleKey: "challenges.stewardship7day.day4.principle",
        promptKey: "challenges.stewardship7day.day4.prompt",
        practiceKey: "challenges.stewardship7day.day4.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 5,
        scripture: "2 Corinthians 9:7",
        principleKey: "challenges.stewardship7day.day5.principle",
        promptKey: "challenges.stewardship7day.day5.prompt",
        practiceKey: "challenges.stewardship7day.day5.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 6,
        scripture: "Matthew 6:24",
        principleKey: "challenges.stewardship7day.day6.principle",
        promptKey: "challenges.stewardship7day.day6.prompt",
        practiceKey: "challenges.stewardship7day.day6.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 7,
        scripture: "1 Timothy 6:6",
        principleKey: "challenges.stewardship7day.day7.principle",
        promptKey: "challenges.stewardship7day.day7.prompt",
        practiceKey: "challenges.stewardship7day.day7.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
    ],
  },
  {
    id: "sabbath-rest-5day",
    titleKey: "challenges.sabbathRest5day.title",
    descriptionKey: "challenges.sabbathRest5day.description",
    title: "",
    description: "",
    totalDays: 5,
    mode: MODE_KEYS.WORK,
    days: [
      {
        day: 1,
        scripture: "Exodus 20:8-10",
        principleKey: "challenges.sabbathRest5day.day1.principle",
        promptKey: "challenges.sabbathRest5day.day1.prompt",
        practiceKey: "challenges.sabbathRest5day.day1.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 2,
        scripture: "Mark 2:27",
        principleKey: "challenges.sabbathRest5day.day2.principle",
        promptKey: "challenges.sabbathRest5day.day2.prompt",
        practiceKey: "challenges.sabbathRest5day.day2.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 3,
        scripture: "Psalm 46:10",
        principleKey: "challenges.sabbathRest5day.day3.principle",
        promptKey: "challenges.sabbathRest5day.day3.prompt",
        practiceKey: "challenges.sabbathRest5day.day3.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 4,
        scripture: "Luke 10:41-42",
        principleKey: "challenges.sabbathRest5day.day4.principle",
        promptKey: "challenges.sabbathRest5day.day4.prompt",
        practiceKey: "challenges.sabbathRest5day.day4.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 5,
        scripture: "Isaiah 58:13-14",
        principleKey: "challenges.sabbathRest5day.day5.principle",
        promptKey: "challenges.sabbathRest5day.day5.prompt",
        practiceKey: "challenges.sabbathRest5day.day5.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
    ],
  },
  {
    id: "listening-3day",
    titleKey: "challenges.listening3day.title",
    descriptionKey: "challenges.listening3day.description",
    title: "",
    description: "",
    totalDays: 3,
    mode: MODE_KEYS.LIFE,
    days: [
      {
        day: 1,
        scripture: "James 1:19",
        principleKey: "challenges.listening3day.day1.principle",
        promptKey: "challenges.listening3day.day1.prompt",
        practiceKey: "challenges.listening3day.day1.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 2,
        scripture: "Proverbs 18:13",
        principleKey: "challenges.listening3day.day2.principle",
        promptKey: "challenges.listening3day.day2.prompt",
        practiceKey: "challenges.listening3day.day2.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 3,
        scripture: "Proverbs 20:5",
        principleKey: "challenges.listening3day.day3.principle",
        promptKey: "challenges.listening3day.day3.prompt",
        practiceKey: "challenges.listening3day.day3.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
    ],
  },
  {
    id: "repair-4day",
    titleKey: "challenges.repair4day.title",
    descriptionKey: "challenges.repair4day.description",
    title: "",
    description: "",
    totalDays: 4,
    mode: MODE_KEYS.LIFE,
    days: [
      {
        day: 1,
        scripture: "Matthew 5:23-24",
        principleKey: "challenges.repair4day.day1.principle",
        promptKey: "challenges.repair4day.day1.prompt",
        practiceKey: "challenges.repair4day.day1.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 2,
        scripture: "Ephesians 4:26-27",
        principleKey: "challenges.repair4day.day2.principle",
        promptKey: "challenges.repair4day.day2.prompt",
        practiceKey: "challenges.repair4day.day2.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 3,
        scripture: "James 5:16",
        principleKey: "challenges.repair4day.day3.principle",
        promptKey: "challenges.repair4day.day3.prompt",
        practiceKey: "challenges.repair4day.day3.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 4,
        scripture: "Romans 12:18",
        principleKey: "challenges.repair4day.day4.principle",
        promptKey: "challenges.repair4day.day4.prompt",
        practiceKey: "challenges.repair4day.day4.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
    ],
  },
  {
    id: "generosity-7day",
    titleKey: "challenges.generosity7day.title",
    descriptionKey: "challenges.generosity7day.description",
    title: "",
    description: "",
    totalDays: 7,
    mode: MODE_KEYS.GENEROSITY,
    days: [
      {
        day: 1,
        scripture: "Proverbs 11:25",
        principleKey: "challenges.generosity7day.day1.principle",
        promptKey: "challenges.generosity7day.day1.prompt",
        practiceKey: "challenges.generosity7day.day1.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 2,
        scripture: "2 Corinthians 8:12",
        principleKey: "challenges.generosity7day.day2.principle",
        promptKey: "challenges.generosity7day.day2.prompt",
        practiceKey: "challenges.generosity7day.day2.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 3,
        scripture: "Acts 20:35",
        principleKey: "challenges.generosity7day.day3.principle",
        promptKey: "challenges.generosity7day.day3.prompt",
        practiceKey: "challenges.generosity7day.day3.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 4,
        scripture: "Proverbs 19:17",
        principleKey: "challenges.generosity7day.day4.principle",
        promptKey: "challenges.generosity7day.day4.prompt",
        practiceKey: "challenges.generosity7day.day4.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 5,
        scripture: "1 Timothy 6:17-19",
        principleKey: "challenges.generosity7day.day5.principle",
        promptKey: "challenges.generosity7day.day5.prompt",
        practiceKey: "challenges.generosity7day.day5.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 6,
        scripture: "2 Corinthians 9:11",
        principleKey: "challenges.generosity7day.day6.principle",
        promptKey: "challenges.generosity7day.day6.prompt",
        practiceKey: "challenges.generosity7day.day6.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 7,
        scripture: "Deuteronomy 15:10",
        principleKey: "challenges.generosity7day.day7.principle",
        promptKey: "challenges.generosity7day.day7.prompt",
        practiceKey: "challenges.generosity7day.day7.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
    ],
  },
  {
    id: "attention-fast-5day",
    titleKey: "challenges.attentionFast5day.title",
    descriptionKey: "challenges.attentionFast5day.description",
    title: "",
    description: "",
    totalDays: 5,
    mode: MODE_KEYS.PURPOSE,
    days: [
      {
        day: 1,
        scripture: "Psalm 90:12",
        principleKey: "challenges.attentionFast5day.day1.principle",
        promptKey: "challenges.attentionFast5day.day1.prompt",
        practiceKey: "challenges.attentionFast5day.day1.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 2,
        scripture: "Proverbs 4:23",
        principleKey: "challenges.attentionFast5day.day2.principle",
        promptKey: "challenges.attentionFast5day.day2.prompt",
        practiceKey: "challenges.attentionFast5day.day2.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 3,
        scripture: "Matthew 6:22-23",
        principleKey: "challenges.attentionFast5day.day3.principle",
        promptKey: "challenges.attentionFast5day.day3.prompt",
        practiceKey: "challenges.attentionFast5day.day3.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 4,
        scripture: "Romans 12:2",
        principleKey: "challenges.attentionFast5day.day4.principle",
        promptKey: "challenges.attentionFast5day.day4.prompt",
        practiceKey: "challenges.attentionFast5day.day4.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 5,
        scripture: "Philippians 4:8",
        principleKey: "challenges.attentionFast5day.day5.principle",
        promptKey: "challenges.attentionFast5day.day5.prompt",
        practiceKey: "challenges.attentionFast5day.day5.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
    ],
  },
  {
    id: "hidden-service-5day",
    titleKey: "challenges.hiddenService5day.title",
    descriptionKey: "challenges.hiddenService5day.description",
    title: "",
    description: "",
    totalDays: 5,
    mode: MODE_KEYS.LIFE,
    days: [
      {
        day: 1,
        scripture: "Matthew 6:3-4",
        principleKey: "challenges.hiddenService5day.day1.principle",
        promptKey: "challenges.hiddenService5day.day1.prompt",
        practiceKey: "challenges.hiddenService5day.day1.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 2,
        scripture: "Galatians 5:13",
        principleKey: "challenges.hiddenService5day.day2.principle",
        promptKey: "challenges.hiddenService5day.day2.prompt",
        practiceKey: "challenges.hiddenService5day.day2.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 3,
        scripture: "1 Peter 4:10",
        principleKey: "challenges.hiddenService5day.day3.principle",
        promptKey: "challenges.hiddenService5day.day3.prompt",
        practiceKey: "challenges.hiddenService5day.day3.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 4,
        scripture: "Colossians 3:23-24",
        principleKey: "challenges.hiddenService5day.day4.principle",
        promptKey: "challenges.hiddenService5day.day4.prompt",
        practiceKey: "challenges.hiddenService5day.day4.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 5,
        scripture: "Hebrews 6:10",
        principleKey: "challenges.hiddenService5day.day5.principle",
        promptKey: "challenges.hiddenService5day.day5.prompt",
        practiceKey: "challenges.hiddenService5day.day5.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
    ],
  },
  {
    id: "read-with-me-7day",
    titleKey: "challenges.readWithMe7day.title",
    descriptionKey: "challenges.readWithMe7day.description",
    title: "",
    description: "",
    totalDays: 7,
    mode: MODE_KEYS.PURPOSE,
    days: [
      {
        day: 1,
        scripture: "Proverbs 18:15",
        principleKey: "challenges.readWithMe7day.day1.principle",
        promptKey: "challenges.readWithMe7day.day1.prompt",
        practiceKey: "challenges.readWithMe7day.day1.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 2,
        scripture: "James 1:19",
        principleKey: "challenges.readWithMe7day.day2.principle",
        promptKey: "challenges.readWithMe7day.day2.prompt",
        practiceKey: "challenges.readWithMe7day.day2.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 3,
        scripture: "Proverbs 4:7",
        principleKey: "challenges.readWithMe7day.day3.principle",
        promptKey: "challenges.readWithMe7day.day3.prompt",
        practiceKey: "challenges.readWithMe7day.day3.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 4,
        scripture: "Psalm 119:105",
        principleKey: "challenges.readWithMe7day.day4.principle",
        promptKey: "challenges.readWithMe7day.day4.prompt",
        practiceKey: "challenges.readWithMe7day.day4.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 5,
        scripture: "Acts 17:11",
        principleKey: "challenges.readWithMe7day.day5.principle",
        promptKey: "challenges.readWithMe7day.day5.prompt",
        practiceKey: "challenges.readWithMe7day.day5.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 6,
        scripture: "Colossians 3:16",
        principleKey: "challenges.readWithMe7day.day6.principle",
        promptKey: "challenges.readWithMe7day.day6.prompt",
        practiceKey: "challenges.readWithMe7day.day6.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 7,
        scripture: "2 Timothy 2:15",
        principleKey: "challenges.readWithMe7day.day7.principle",
        promptKey: "challenges.readWithMe7day.day7.prompt",
        practiceKey: "challenges.readWithMe7day.day7.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
    ],
  },
];

export function getChallengeById(id: string): ChallengeDefinition | undefined {
  return challengeDefinitions.find((c) => c.id === id);
}
