import { MODE_KEYS, type Mode } from "@/lib/mode-keys";

export type ChallengeId =
  | "gratitude-3day"
  | "shared-encouragement-3day"
  | "waiting-5day"
  | "stewardship-7day"
  | "sabbath-rest-5day"
  | "listening-3day"
  | "repair-4day"
  | "generosity-7day"
  | "attention-fast-5day"
  | "hidden-service-5day"
  | "read-with-me-7day";

export type ChallengeDayPrompt = {
  day: number;
  scripture: string;
  principleKey: string;
  promptKey: string;
  practiceKey: string;
  principle: string;
  prompt: string;
  practice: string;
};

export type ChallengeDefinition = {
  id: ChallengeId;
  titleKey: string;
  descriptionKey: string;
  title: string;
  description: string;
  totalDays: number;
  mode: Mode;
  days: ChallengeDayPrompt[];
};

export const challengeDefinitions: ChallengeDefinition[] = [
  {
    id: "gratitude-3day",
    titleKey: "challenges.gratitude3day.title",
    descriptionKey: "challenges.gratitude3day.description",
    title: "3-Day Gratitude Practice",
    description:
      "Three days of quiet noticing - one ordinary gift, one steady presence, one area where contentment is growing.",
    totalDays: 3,
    mode: MODE_KEYS.LIFE,
    days: [
      {
        day: 1,
        scripture: "1 Thessalonians 5:18",
        principleKey: "challenges.gratitude3day.day1.principle",
        promptKey: "challenges.gratitude3day.day1.prompt",
        practiceKey: "challenges.gratitude3day.day1.practice",
        principle: "Give thanks in all circumstances; for this is the will of God in Christ Jesus for you.",
        prompt: "Notice one ordinary gift today that you might normally overlook. Write a brief note about it.",
        practice: "Name one ordinary mercy you almost missed.",
      },
      {
        day: 2,
        scripture: "Psalm 107:1",
        principleKey: "challenges.gratitude3day.day2.principle",
        promptKey: "challenges.gratitude3day.day2.prompt",
        practiceKey: "challenges.gratitude3day.day2.practice",
        principle: "Give thanks to the Lord, for he is good; his steadfast love endures forever.",
        prompt: "Think about someone whose steadfast presence has shaped your discernment. Write what you are grateful for about them.",
        practice: "Name a person whose steady presence you are grateful for.",
      },
      {
        day: 3,
        scripture: "Philippians 4:11",
        principleKey: "challenges.gratitude3day.day3.principle",
        promptKey: "challenges.gratitude3day.day3.prompt",
        practiceKey: "challenges.gratitude3day.day3.practice",
        principle: "I have learned, in whatever state I am, to be content.",
        prompt: "Where has contentment felt difficult this week? What would it look like to choose gratitude over scarcity in that place?",
        practice: "Name one area where gratitude is replacing scarcity today.",
      },
    ],
  },
  {
    id: "shared-encouragement-3day",
    titleKey: "challenges.sharedEncouragement3day.title",
    descriptionKey: "challenges.sharedEncouragement3day.description",
    title: "3-Day Shared Encouragement Practice",
    description:
      "Three days of mutual encouragement - send one specific word of courage, one sharpening truth, and one thank-you that lands.",
    totalDays: 3,
    mode: MODE_KEYS.LIFE,
    days: [
      {
        day: 1,
        scripture: "Hebrews 10:24-25",
        principleKey: "challenges.sharedEncouragement3day.day1.principle",
        promptKey: "challenges.sharedEncouragement3day.day1.prompt",
        practiceKey: "challenges.sharedEncouragement3day.day1.practice",
        principle: "Let us consider how to stir up one another to love and good works, not neglecting to meet together.",
        prompt: "Send one person a specific encouragement today. What did you notice in them that is worth naming?",
        practice: "Send one specific encouragement by text, note, or voice memo and name what you saw.",
      },
      {
        day: 2,
        scripture: "Proverbs 27:17",
        principleKey: "challenges.sharedEncouragement3day.day2.principle",
        promptKey: "challenges.sharedEncouragement3day.day2.prompt",
        practiceKey: "challenges.sharedEncouragement3day.day2.practice",
        principle: "Iron sharpens iron, and one man sharpens another.",
        prompt: "Share one insight from your day that could help someone else grow, without trying to fix their whole story.",
        practice: "Offer one honest, sharpening observation with kindness and one clear next question.",
      },
      {
        day: 3,
        scripture: "Colossians 3:16",
        principleKey: "challenges.sharedEncouragement3day.day3.principle",
        promptKey: "challenges.sharedEncouragement3day.day3.prompt",
        practiceKey: "challenges.sharedEncouragement3day.day3.practice",
        principle: "Let the word of Christ dwell in you richly, teaching and admonishing one another in all wisdom.",
        prompt: "What has changed in you this week because someone else walked with you?",
        practice: "Thank someone for the way they helped you keep going, and be specific.",
      },
    ],
  },
  {
    id: "waiting-5day",
    titleKey: "challenges.waiting5day.title",
    descriptionKey: "challenges.waiting5day.description",
    title: "5-Day Waiting Practice",
    description:
      "Five days of held decisions - slow the pace, name the fear, and let wisdom arrive before you move.",
    totalDays: 5,
    mode: MODE_KEYS.PURPOSE,
    days: [
      {
        day: 1,
        scripture: "Psalm 27:14",
        principleKey: "challenges.waiting5day.day1.principle",
        promptKey: "challenges.waiting5day.day1.prompt",
        practiceKey: "challenges.waiting5day.day1.practice",
        principle: "Wait for the Lord; be strong, and let your heart take courage; wait for the Lord.",
        prompt: "Name the decision or pressure you are carrying. Write one line describing what urgency is asking you to do.",
        practice: "Name the decision and what urgency is whispering.",
      },
      {
        day: 2,
        scripture: "Proverbs 4:25-26",
        principleKey: "challenges.waiting5day.day2.principle",
        promptKey: "challenges.waiting5day.day2.prompt",
        practiceKey: "challenges.waiting5day.day2.practice",
        principle: "Let your eyes look directly forward, and your gaze be straight before you. Ponder the path of your feet; then all your ways will be sure.",
        prompt: "What would it cost to wait three more days before deciding? Write the real fear beneath the urgency.",
        practice: "Name the fear beneath the urgency.",
      },
      {
        day: 3,
        scripture: "Isaiah 40:31",
        principleKey: "challenges.waiting5day.day3.principle",
        promptKey: "challenges.waiting5day.day3.prompt",
        practiceKey: "challenges.waiting5day.day3.practice",
        principle: "They who wait for the Lord shall renew their strength; they shall mount up with wings like eagles.",
        prompt: "What is one sign that waiting has been good so far - even something small?",
        practice: "Write one sign that waiting is protecting something good.",
      },
      {
        day: 4,
        scripture: "James 1:5",
        principleKey: "challenges.waiting5day.day4.principle",
        promptKey: "challenges.waiting5day.day4.prompt",
        practiceKey: "challenges.waiting5day.day4.practice",
        principle: "If any of you lacks wisdom, let him ask God, who gives generously to all without reproach, and it will be given him.",
        prompt: "Have you asked a trusted voice about this decision? Write what you have heard or what you would ask them.",
        practice: "Write what counsel has said - or what you would ask.",
      },
      {
        day: 5,
        scripture: "Proverbs 3:5-6",
        principleKey: "challenges.waiting5day.day5.principle",
        promptKey: "challenges.waiting5day.day5.prompt",
        practiceKey: "challenges.waiting5day.day5.practice",
        principle: "Trust in the Lord with all your heart, and do not lean on your own understanding. In all your ways acknowledge him, and he will make straight your paths.",
        prompt: "After five days, what has changed in how you see this decision? What is the next faithful step - even if it is another week of waiting?",
        practice: "Name the next faithful step with an open hand.",
      },
    ],
  },
  {
    id: "stewardship-7day",
    titleKey: "challenges.stewardship7day.title",
    descriptionKey: "challenges.stewardship7day.description",
    title: "7-Day Stewardship Practice",
    description:
      "Seven days of honest stewardship - map what you have, where haste leaks money, and what enough looks like in this season.",
    totalDays: 7,
    mode: MODE_KEYS.MONEY,
    days: [
      {
        day: 1,
        scripture: "Deuteronomy 8:18",
        principleKey: "challenges.stewardship7day.day1.principle",
        promptKey: "challenges.stewardship7day.day1.prompt",
        practiceKey: "challenges.stewardship7day.day1.practice",
        principle: "Remember the Lord your God, for it is he who gives you power to get wealth.",
        prompt: "Write one way your income or resources have come to you - something you did not fully earn on your own.",
        practice: "Acknowledge one resource that was given, not only earned, and say thanks out loud.",
      },
      {
        day: 2,
        scripture: "Proverbs 21:5",
        principleKey: "challenges.stewardship7day.day2.principle",
        promptKey: "challenges.stewardship7day.day2.prompt",
        practiceKey: "challenges.stewardship7day.day2.practice",
        principle: "The plans of the diligent lead surely to abundance, but everyone who is hasty comes only to poverty.",
        prompt: "Where are you making a financial decision in haste? Name it and write what slow discernment would ask.",
        practice: "Name one area where haste is shaping spending, then pause before you buy.",
      },
      {
        day: 3,
        scripture: "Luke 16:10",
        principleKey: "challenges.stewardship7day.day3.principle",
        promptKey: "challenges.stewardship7day.day3.prompt",
        practiceKey: "challenges.stewardship7day.day3.practice",
        principle: "One who is faithful in a very little is also faithful in much, and one who is dishonest in a very little is also dishonest in much.",
        prompt: "What is one small area of financial faithfulness you have practised recently? Write it down as an act of gratitude, not pride.",
        practice: "Name one small area where faithfulness has shown up.",
      },
      {
        day: 4,
        scripture: "Romans 13:8",
        principleKey: "challenges.stewardship7day.day4.principle",
        promptKey: "challenges.stewardship7day.day4.prompt",
        practiceKey: "challenges.stewardship7day.day4.practice",
        principle: "Owe no one anything, except to love each other.",
        prompt: "Look at your debts - student, personal, consumer, or relational. Write one honest sentence about what you owe and what faithful next step looks like.",
        practice: "Write one honest sentence about what you owe.",
      },
      {
        day: 5,
        scripture: "2 Corinthians 9:7",
        principleKey: "challenges.stewardship7day.day5.principle",
        promptKey: "challenges.stewardship7day.day5.prompt",
        practiceKey: "challenges.stewardship7day.day5.practice",
        principle: "Each one must give as he has decided in his heart, not reluctantly or under compulsion, for God loves a cheerful giver.",
        prompt: "Write about the last time you gave freely - without guilt or pressure. What made it joyful?",
        practice: "Name one act of giving that came from freedom, not compulsion.",
      },
      {
        day: 6,
        scripture: "Matthew 6:24",
        principleKey: "challenges.stewardship7day.day6.principle",
        promptKey: "challenges.stewardship7day.day6.prompt",
        practiceKey: "challenges.stewardship7day.day6.practice",
        principle: "You cannot serve God and money.",
        prompt: "Where is money making a decision that should belong to wisdom, relationships, or rest? Name it without shame.",
        practice: "Name one place where money is leading instead of serving.",
      },
      {
        day: 7,
        scripture: "1 Timothy 6:6",
        principleKey: "challenges.stewardship7day.day7.principle",
        promptKey: "challenges.stewardship7day.day7.prompt",
        practiceKey: "challenges.stewardship7day.day7.practice",
        principle: "Godliness with contentment is great gain.",
        prompt: "After seven days, write what is enough for this season. Not an ideal - what is actually enough right now?",
        practice: "Write what is enough for this season, plainly.",
      },
    ],
  },
  {
    id: "sabbath-rest-5day",
    titleKey: "challenges.sabbathRest5day.title",
    descriptionKey: "challenges.sabbathRest5day.description",
    title: "5-Day Sabbath Rest Practice",
    description:
      "Five days of protected rest - stop, breathe, delight, and build a rhythm that actually restores you.",
    totalDays: 5,
    mode: MODE_KEYS.WORK,
    days: [
      {
        day: 1,
        scripture: "Exodus 20:8-10",
        principleKey: "challenges.sabbathRest5day.day1.principle",
        promptKey: "challenges.sabbathRest5day.day1.prompt",
        practiceKey: "challenges.sabbathRest5day.day1.practice",
        principle: "Remember the Sabbath day, to keep it holy.",
        prompt: "Name one block of time this week that you will protect for rest. What would make it feel truly set apart?",
        practice: "Protect one restful block on your calendar.",
      },
      {
        day: 2,
        scripture: "Mark 2:27",
        principleKey: "challenges.sabbathRest5day.day2.principle",
        promptKey: "challenges.sabbathRest5day.day2.prompt",
        practiceKey: "challenges.sabbathRest5day.day2.practice",
        principle: "The Sabbath was made for man, not man for the Sabbath.",
        prompt: "What part of your pace needs releasing so rest can serve you instead of feeling like a reward?",
        practice: "Let one task wait without guilt.",
      },
      {
        day: 3,
        scripture: "Psalm 46:10",
        principleKey: "challenges.sabbathRest5day.day3.principle",
        promptKey: "challenges.sabbathRest5day.day3.prompt",
        practiceKey: "challenges.sabbathRest5day.day3.practice",
        principle: "Be still, and know that I am God.",
        prompt: "Pause for two minutes and do nothing but breathe and notice where your body is carrying stress.",
        practice: "Take a 2-minute quiet pause.",
      },
      {
        day: 4,
        scripture: "Luke 10:41-42",
        principleKey: "challenges.sabbathRest5day.day4.principle",
        promptKey: "challenges.sabbathRest5day.day4.prompt",
        practiceKey: "challenges.sabbathRest5day.day4.practice",
        principle: "One thing is necessary. Mary has chosen the good portion.",
        prompt: "What is one necessary thing you can let remain unfinished today so you can choose the better portion?",
        practice: "Leave one nonessential task unfinished on purpose.",
      },
      {
        day: 5,
        scripture: "Isaiah 58:13-14",
        principleKey: "challenges.sabbathRest5day.day5.principle",
        promptKey: "challenges.sabbathRest5day.day5.prompt",
        practiceKey: "challenges.sabbathRest5day.day5.practice",
        principle: "If you call the Sabbath a delight ... then you shall take delight in the Lord.",
        prompt: "What delight restores you most faithfully - music, a walk, a meal, silence, a conversation? Choose one and keep it simple.",
        practice: "Choose one delight and receive it without hurry, phone away.",
      },
    ],
  },
  {
    id: "listening-3day",
    titleKey: "challenges.listening3day.title",
    descriptionKey: "challenges.listening3day.description",
    title: "3-Day Listening Practice",
    description:
      "Three days of listening before fixing - hear the person, the pressure, and the pattern before you answer.",
    totalDays: 3,
    mode: MODE_KEYS.LIFE,
    days: [
      {
        day: 1,
        scripture: "James 1:19",
        principleKey: "challenges.listening3day.day1.principle",
        promptKey: "challenges.listening3day.day1.prompt",
        practiceKey: "challenges.listening3day.day1.practice",
        principle: "Let every person be quick to hear, slow to speak, slow to anger.",
        prompt: "In your next conversation, listen without planning your reply until the other person finishes.",
        practice: "Ask one clarifying question before giving advice and wait for the full answer.",
      },
      {
        day: 2,
        scripture: "Proverbs 18:13",
        principleKey: "challenges.listening3day.day2.principle",
        promptKey: "challenges.listening3day.day2.prompt",
        practiceKey: "challenges.listening3day.day2.practice",
        principle: "If one gives an answer before he hears, it is his folly and shame.",
        prompt: "Notice where you usually interrupt, defend, or speed up. Write one sentence about what you want to change.",
        practice: "Reflect back what you heard before responding in your own words.",
      },
      {
        day: 3,
        scripture: "Proverbs 20:5",
        principleKey: "challenges.listening3day.day3.principle",
        promptKey: "challenges.listening3day.day3.prompt",
        practiceKey: "challenges.listening3day.day3.practice",
        principle: "The purpose in a man's heart is like deep water, but a man of understanding will draw it out.",
        prompt: "Choose one real question and ask it slowly. Stay curious until the answer is fully heard.",
        practice: "End one conversation by summarizing what you learned in one sentence.",
      },
    ],
  },
  {
    id: "repair-4day",
    titleKey: "challenges.repair4day.title",
    descriptionKey: "challenges.repair4day.description",
    title: "4-Day Repair Practice",
    description:
      "Four days of repair - own your part, say the hard thing, and take one concrete step toward peace.",
    totalDays: 4,
    mode: MODE_KEYS.LIFE,
    days: [
      {
        day: 1,
        scripture: "Matthew 5:23-24",
        principleKey: "challenges.repair4day.day1.principle",
        promptKey: "challenges.repair4day.day1.prompt",
        practiceKey: "challenges.repair4day.day1.practice",
        principle: "First be reconciled to your brother, and then come and offer your gift.",
        prompt: "Name one relationship or message that needs repair. What is the smallest honest first move?",
        practice: "Write or send one initiating apology or reconnection, even if it is brief.",
      },
      {
        day: 2,
        scripture: "Ephesians 4:26-27",
        principleKey: "challenges.repair4day.day2.principle",
        promptKey: "challenges.repair4day.day2.prompt",
        practiceKey: "challenges.repair4day.day2.practice",
        principle: "Be angry and do not sin; do not let the sun go down on your anger.",
        prompt: "What resentment or delay is letting a wound stay open? Write what you can release today.",
        practice: "Release one grievance in prayer and let it go, without rehearsing it again.",
      },
      {
        day: 3,
        scripture: "James 5:16",
        principleKey: "challenges.repair4day.day3.principle",
        promptKey: "challenges.repair4day.day3.prompt",
        practiceKey: "challenges.repair4day.day3.practice",
        principle: "Confess your sins to one another and pray for one another, that you may be healed.",
        prompt: "Confess what needs to be named clearly and without performance. Keep it simple and true.",
        practice: "Name the truth plainly to a trusted person and ask for prayer.",
      },
      {
        day: 4,
        scripture: "Romans 12:18",
        principleKey: "challenges.repair4day.day4.principle",
        promptKey: "challenges.repair4day.day4.prompt",
        practiceKey: "challenges.repair4day.day4.practice",
        principle: "If possible, so far as it depends on you, live peaceably with all.",
        prompt: "What does peace require from you now - a boundary, a follow-up, or a final check-in?",
        practice: "Take one peace-making next step and keep it small enough to finish today.",
      },
    ],
  },
  {
    id: "generosity-7day",
    titleKey: "challenges.generosity7day.title",
    descriptionKey: "challenges.generosity7day.description",
    title: "7-Day Generosity Practice",
    description:
      "Seven days of giving from freedom - offer time, money, attention, and skill with margin, not pressure.",
    totalDays: 7,
    mode: MODE_KEYS.GENEROSITY,
    days: [
      {
        day: 1,
        scripture: "Proverbs 11:25",
        principleKey: "challenges.generosity7day.day1.principle",
        promptKey: "challenges.generosity7day.day1.prompt",
        practiceKey: "challenges.generosity7day.day1.practice",
        principle: "Whoever brings blessing will be enriched, and one who waters will himself be watered.",
        prompt: "Where can you give from what you already have, even if the gift is small?",
        practice: "Offer one small act of generosity today and notice how it feels.",
      },
      {
        day: 2,
        scripture: "2 Corinthians 8:12",
        principleKey: "challenges.generosity7day.day2.principle",
        promptKey: "challenges.generosity7day.day2.prompt",
        practiceKey: "challenges.generosity7day.day2.practice",
        principle: "If the readiness is there, it is acceptable according to what a person has, not according to what he does not have.",
        prompt: "What is your present capacity, honestly? Write the line between generosity and overcommitment.",
        practice: "Define your giving margin in one sentence and keep it visible.",
      },
      {
        day: 3,
        scripture: "Acts 20:35",
        principleKey: "challenges.generosity7day.day3.principle",
        promptKey: "challenges.generosity7day.day3.prompt",
        practiceKey: "challenges.generosity7day.day3.practice",
        principle: "It is more blessed to give than to receive.",
        prompt: "Choose one person who would be encouraged by a practical gift of help, time, or encouragement.",
        practice: "Give one useful, practical gift that solves a real problem.",
      },
      {
        day: 4,
        scripture: "Proverbs 19:17",
        principleKey: "challenges.generosity7day.day4.principle",
        promptKey: "challenges.generosity7day.day4.prompt",
        practiceKey: "challenges.generosity7day.day4.practice",
        principle: "Whoever is generous to the poor lends to the Lord.",
        prompt: "What hidden need around you is easy to miss? Ask what mercy looks like there.",
        practice: "Meet one unnoticed need without announcing it.",
      },
      {
        day: 5,
        scripture: "1 Timothy 6:17-19",
        principleKey: "challenges.generosity7day.day5.principle",
        promptKey: "challenges.generosity7day.day5.prompt",
        practiceKey: "challenges.generosity7day.day5.practice",
        principle: "Set their hope on God, who richly provides us with everything to enjoy.",
        prompt: "What would it look like to enjoy what you have without grasping for more?",
        practice: "Practice contentment before spending by waiting 24 hours on one purchase.",
      },
      {
        day: 6,
        scripture: "2 Corinthians 9:11",
        principleKey: "challenges.generosity7day.day6.principle",
        promptKey: "challenges.generosity7day.day6.prompt",
        practiceKey: "challenges.generosity7day.day6.practice",
        principle: "You will be enriched in every way to be generous in every way.",
        prompt: "Can you bless someone with a note, meal, or skill that costs little but helps much?",
        practice: "Give something that multiplies joy and can be passed on.",
      },
      {
        day: 7,
        scripture: "Deuteronomy 15:10",
        principleKey: "challenges.generosity7day.day7.principle",
        promptKey: "challenges.generosity7day.day7.prompt",
        practiceKey: "challenges.generosity7day.day7.practice",
        principle: "You shall give to him freely, and your heart shall not be grudging when you give to him.",
        prompt: "End this week by naming one way generosity made you freer.",
        practice: "Name one way giving made room in you and record it.",
      },
    ],
  },
  {
    id: "attention-fast-5day",
    titleKey: "challenges.attentionFast5day.title",
    descriptionKey: "challenges.attentionFast5day.description",
    title: "5-Day Attention Fast",
    description:
      "Five days of reclaiming attention - trim noise, recover focus, and notice what forms you.",
    totalDays: 5,
    mode: MODE_KEYS.PURPOSE,
    days: [
      {
        day: 1,
        scripture: "Psalm 90:12",
        principleKey: "challenges.attentionFast5day.day1.principle",
        promptKey: "challenges.attentionFast5day.day1.prompt",
        practiceKey: "challenges.attentionFast5day.day1.practice",
        principle: "Teach us to number our days that we may get a heart of wisdom.",
        prompt: "Where is your attention leaking most easily? Name one app, habit, or tab to check first.",
        practice: "Track one distraction trigger and write what set it off.",
      },
      {
        day: 2,
        scripture: "Proverbs 4:23",
        principleKey: "challenges.attentionFast5day.day2.principle",
        promptKey: "challenges.attentionFast5day.day2.prompt",
        practiceKey: "challenges.attentionFast5day.day2.practice",
        principle: "Keep your heart with all vigilance, for from it flow the springs of life.",
        prompt: "What inputs are shaping your mood more than you want them to? Write one boundary.",
        practice: "Set one screen boundary for today and keep it for one hour.",
      },
      {
        day: 3,
        scripture: "Matthew 6:22-23",
        principleKey: "challenges.attentionFast5day.day3.principle",
        promptKey: "challenges.attentionFast5day.day3.prompt",
        practiceKey: "challenges.attentionFast5day.day3.practice",
        principle: "If your eye is healthy, your whole body will be full of light.",
        prompt: "Choose one thing to keep your attention clear - a room, meal, walk, or prayer - and do it without multitasking.",
        practice: "Do one thing single-tasked for ten uninterrupted minutes.",
      },
      {
        day: 4,
        scripture: "Romans 12:2",
        principleKey: "challenges.attentionFast5day.day4.principle",
        promptKey: "challenges.attentionFast5day.day4.prompt",
        practiceKey: "challenges.attentionFast5day.day4.practice",
        principle: "Do not be conformed to this world, but be transformed by the renewal of your mind.",
        prompt: "What thought pattern do you want to resist? Replace it with one truth you can remember.",
        practice: "Replace one noisy input with quiet and notice the shift.",
      },
      {
        day: 5,
        scripture: "Philippians 4:8",
        principleKey: "challenges.attentionFast5day.day5.principle",
        promptKey: "challenges.attentionFast5day.day5.prompt",
        practiceKey: "challenges.attentionFast5day.day5.practice",
        principle: "Whatever is true, honorable, just, pure, lovely, commendable - think about these things.",
        prompt: "End the fast by naming what is true, honorable, just, pure, lovely, and commendable in your day.",
        practice: "Notice one good thing without reaching for your phone, then write it down.",
      },
    ],
  },
  {
    id: "hidden-service-5day",
    titleKey: "challenges.hiddenService5day.title",
    descriptionKey: "challenges.hiddenService5day.description",
    title: "5-Day Hidden Service Practice",
    description:
      "Five days of secret service - do good quietly, without needing a spotlight.",
    totalDays: 5,
    mode: MODE_KEYS.LIFE,
    days: [
      {
        day: 1,
        scripture: "Matthew 6:3-4",
        principleKey: "challenges.hiddenService5day.day1.principle",
        promptKey: "challenges.hiddenService5day.day1.prompt",
        practiceKey: "challenges.hiddenService5day.day1.practice",
        principle: "Do not let your left hand know what your right hand is doing.",
        prompt: "Choose one kindness that no one needs to know about.",
        practice: "Do one quiet good deed that no one can trace back to you.",
      },
      {
        day: 2,
        scripture: "Galatians 5:13",
        principleKey: "challenges.hiddenService5day.day2.principle",
        promptKey: "challenges.hiddenService5day.day2.prompt",
        practiceKey: "challenges.hiddenService5day.day2.practice",
        principle: "Through love serve one another.",
        prompt: "What help can you offer without controlling the outcome?",
        practice: "Serve someone without naming it publicly or posting about it.",
      },
      {
        day: 3,
        scripture: "1 Peter 4:10",
        principleKey: "challenges.hiddenService5day.day3.principle",
        promptKey: "challenges.hiddenService5day.day3.prompt",
        practiceKey: "challenges.hiddenService5day.day3.practice",
        principle: "As each has received a gift, use it to serve one another.",
        prompt: "What gift, skill, or strength can you put in motion for someone else today?",
        practice: "Use one gift for someone else's benefit and leave the spotlight off.",
      },
      {
        day: 4,
        scripture: "Colossians 3:23-24",
        principleKey: "challenges.hiddenService5day.day4.principle",
        promptKey: "challenges.hiddenService5day.day4.prompt",
        practiceKey: "challenges.hiddenService5day.day4.practice",
        principle: "Whatever you do, work heartily, as for the Lord and not for men.",
        prompt: "How can you do one ordinary task with wholehearted care, even if nobody notices?",
        practice: "Do one hidden task with care as if it were the only thing you did today.",
      },
      {
        day: 5,
        scripture: "Hebrews 6:10",
        principleKey: "challenges.hiddenService5day.day5.principle",
        promptKey: "challenges.hiddenService5day.day5.prompt",
        practiceKey: "challenges.hiddenService5day.day5.practice",
        principle: "God is not unjust so as to overlook your work and the love that you have shown for his name.",
        prompt: "Name one way God may already be seeing your quiet faithfulness.",
        practice: "Write down one unseen act of faithfulness before the day ends.",
      },
    ],
  },
  {
    id: "read-with-me-7day",
    titleKey: "challenges.readWithMe7day.title",
    descriptionKey: "challenges.readWithMe7day.description",
    title: "Read with Me",
    description:
      "Seven days of shared reading - set a clear pace, notice what the book is asking of you, and make space for honest conversation.",
    totalDays: 7,
    mode: MODE_KEYS.PURPOSE,
    days: [
      {
        day: 1,
        scripture: "Proverbs 18:15",
        principleKey: "challenges.readWithMe7day.day1.principle",
        promptKey: "challenges.readWithMe7day.day1.prompt",
        practiceKey: "challenges.readWithMe7day.day1.practice",
        principle: "An intelligent heart acquires knowledge, and the ear of the wise seeks knowledge.",
        prompt: "Choose the book and write why this read matters right now. What are you hoping it will clarify or stir in you?",
        practice: "Name the book, the reason you chose it, and the change you hope to see.",
      },
      {
        day: 2,
        scripture: "James 1:19",
        principleKey: "challenges.readWithMe7day.day2.principle",
        promptKey: "challenges.readWithMe7day.day2.prompt",
        practiceKey: "challenges.readWithMe7day.day2.practice",
        principle: "Let every person be quick to hear, slow to speak, slow to anger.",
        prompt: "Read the opening portion slowly. What is one sentence that deserves a second look before you move on?",
        practice: "Mark one sentence that you want to return to instead of rushing past it.",
      },
      {
        day: 3,
        scripture: "Proverbs 4:7",
        principleKey: "challenges.readWithMe7day.day3.principle",
        promptKey: "challenges.readWithMe7day.day3.prompt",
        practiceKey: "challenges.readWithMe7day.day3.practice",
        principle: "Wisdom is the principal thing; therefore get wisdom.",
        prompt: "What is the book teaching you to value? Write one insight that feels both sharp and useful.",
        practice: "Write one insight in plain language, as if you were explaining it to a friend.",
      },
      {
        day: 4,
        scripture: "Psalm 119:105",
        principleKey: "challenges.readWithMe7day.day4.principle",
        promptKey: "challenges.readWithMe7day.day4.prompt",
        practiceKey: "challenges.readWithMe7day.day4.practice",
        principle: "Your word is a lamp to my feet and a light to my path.",
        prompt: "Which idea in the book feels like light for your next step, and which idea still needs testing?",
        practice: "Separate one clear light from one still-uncertain idea.",
      },
      {
        day: 5,
        scripture: "Acts 17:11",
        principleKey: "challenges.readWithMe7day.day5.principle",
        promptKey: "challenges.readWithMe7day.day5.prompt",
        practiceKey: "challenges.readWithMe7day.day5.practice",
        principle: "They received the word with all eagerness, examining the Scriptures daily to see if these things were so.",
        prompt: "Share one line with someone else and ask what they hear in it. What changes when you say it out loud?",
        practice: "Bring one quote into conversation and listen for the response.",
      },
      {
        day: 6,
        scripture: "Colossians 3:16",
        principleKey: "challenges.readWithMe7day.day6.principle",
        promptKey: "challenges.readWithMe7day.day6.prompt",
        practiceKey: "challenges.readWithMe7day.day6.practice",
        principle: "Let the word of Christ dwell in you richly, teaching and admonishing one another in all wisdom.",
        prompt: "What does this book want to shape in your habits, relationships, or decisions, not just your thoughts?",
        practice: "Write one concrete place where the book should change your practice.",
      },
      {
        day: 7,
        scripture: "2 Timothy 2:15",
        principleKey: "challenges.readWithMe7day.day7.principle",
        promptKey: "challenges.readWithMe7day.day7.prompt",
        practiceKey: "challenges.readWithMe7day.day7.practice",
        principle: "Do your best to present yourself to God as one approved, a worker who has no need to be ashamed, rightly handling the word of truth.",
        prompt: "Summarize the book in one paragraph. What is the next faithful step you want to take because of it?",
        practice: "Write your one-paragraph takeaway and the next faithful step it points toward.",
      },
    ],
  },
];

export function getChallengeById(id: string): ChallengeDefinition | undefined {
  return challengeDefinitions.find((c) => c.id === id);
}
