import { MODE_KEYS, type Mode } from "@/lib/mode-keys";

export type ChallengeId =
  | "gratitude-3day"
  | "shared-encouragement-3day"
  | "waiting-5day"
  | "stewardship-7day"
  | "sabbath-rest-5day"
  | "listening-3day"
  | "repair-4day"
  | "generosity-7day"
  | "attention-fast-5day"
  | "hidden-service-5day"
  | "read-with-me-7day";

export type ChallengeDayPrompt = {
  day: number;
  scripture: string;
  principleKey: string;
  promptKey: string;
  practiceKey: string;
  principle: string;
  prompt: string;
  practice: string;
};

export type ChallengeDefinition = {
  id: ChallengeId;
  titleKey: string;
  descriptionKey: string;
  title: string;
  description: string;
  totalDays: number;
  mode: Mode;
  days: ChallengeDayPrompt[];
};

export const challengeDefinitions: ChallengeDefinition[] = [
  {
    id: "gratitude-3day",
    titleKey: "challenges.gratitude3day.title",
    descriptionKey: "challenges.gratitude3day.description",
    title: "",
    description: "",
    totalDays: 3,
    mode: MODE_KEYS.LIFE,
    days: [
      {
        day: 1,
        scripture: "1 Thessalonians 5:18",
        principleKey: "challenges.gratitude3day.day1.principle",
        promptKey: "challenges.gratitude3day.day1.prompt",
        practiceKey: "challenges.gratitude3day.day1.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 2,
        scripture: "Psalm 107:1",
        principleKey: "challenges.gratitude3day.day2.principle",
        promptKey: "challenges.gratitude3day.day2.prompt",
        practiceKey: "challenges.gratitude3day.day2.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 3,
        scripture: "Philippians 4:11",
        principleKey: "challenges.gratitude3day.day3.principle",
        promptKey: "challenges.gratitude3day.day3.prompt",
        practiceKey: "challenges.gratitude3day.day3.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
    ],
  },
  {
    id: "shared-encouragement-3day",
    titleKey: "challenges.sharedEncouragement3day.title",
    descriptionKey: "challenges.sharedEncouragement3day.description",
    title: "",
    description: "",
    totalDays: 3,
    mode: MODE_KEYS.LIFE,
    days: [
      {
        day: 1,
        scripture: "Hebrews 10:24-25",
        principleKey: "challenges.sharedEncouragement3day.day1.principle",
        promptKey: "challenges.sharedEncouragement3day.day1.prompt",
        practiceKey: "challenges.sharedEncouragement3day.day1.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 2,
        scripture: "Proverbs 27:17",
        principleKey: "challenges.sharedEncouragement3day.day2.principle",
        promptKey: "challenges.sharedEncouragement3day.day2.prompt",
        practiceKey: "challenges.sharedEncouragement3day.day2.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 3,
        scripture: "Colossians 3:16",
        principleKey: "challenges.sharedEncouragement3day.day3.principle",
        promptKey: "challenges.sharedEncouragement3day.day3.prompt",
        practiceKey: "challenges.sharedEncouragement3day.day3.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
    ],
  },
  {
    id: "waiting-5day",
    titleKey: "challenges.waiting5day.title",
    descriptionKey: "challenges.waiting5day.description",
    title: "",
    description: "",
    totalDays: 5,
    mode: MODE_KEYS.PURPOSE,
    days: [
      {
        day: 1,
        scripture: "Psalm 27:14",
        principleKey: "challenges.waiting5day.day1.principle",
        promptKey: "challenges.waiting5day.day1.prompt",
        practiceKey: "challenges.waiting5day.day1.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 2,
        scripture: "Proverbs 4:25-26",
        principleKey: "challenges.waiting5day.day2.principle",
        promptKey: "challenges.waiting5day.day2.prompt",
        practiceKey: "challenges.waiting5day.day2.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 3,
        scripture: "Isaiah 40:31",
        principleKey: "challenges.waiting5day.day3.principle",
        promptKey: "challenges.waiting5day.day3.prompt",
        practiceKey: "challenges.waiting5day.day3.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 4,
        scripture: "James 1:5",
        principleKey: "challenges.waiting5day.day4.principle",
        promptKey: "challenges.waiting5day.day4.prompt",
        practiceKey: "challenges.waiting5day.day4.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 5,
        scripture: "Proverbs 3:5-6",
        principleKey: "challenges.waiting5day.day5.principle",
        promptKey: "challenges.waiting5day.day5.prompt",
        practiceKey: "challenges.waiting5day.day5.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
    ],
  },
  {
    id: "stewardship-7day",
    titleKey: "challenges.stewardship7day.title",
    descriptionKey: "challenges.stewardship7day.description",
    title: "",
    description: "",
    totalDays: 7,
    mode: MODE_KEYS.MONEY,
    days: [
      {
        day: 1,
        scripture: "Deuteronomy 8:18",
        principleKey: "challenges.stewardship7day.day1.principle",
        promptKey: "challenges.stewardship7day.day1.prompt",
        practiceKey: "challenges.stewardship7day.day1.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 2,
        scripture: "Proverbs 21:5",
        principleKey: "challenges.stewardship7day.day2.principle",
        promptKey: "challenges.stewardship7day.day2.prompt",
        practiceKey: "challenges.stewardship7day.day2.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 3,
        scripture: "Luke 16:10",
        principleKey: "challenges.stewardship7day.day3.principle",
        promptKey: "challenges.stewardship7day.day3.prompt",
        practiceKey: "challenges.stewardship7day.day3.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 4,
        scripture: "Romans 13:8",
        principleKey: "challenges.stewardship7day.day4.principle",
        promptKey: "challenges.stewardship7day.day4.prompt",
        practiceKey: "challenges.stewardship7day.day4.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 5,
        scripture: "2 Corinthians 9:7",
        principleKey: "challenges.stewardship7day.day5.principle",
        promptKey: "challenges.stewardship7day.day5.prompt",
        practiceKey: "challenges.stewardship7day.day5.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 6,
        scripture: "Matthew 6:24",
        principleKey: "challenges.stewardship7day.day6.principle",
        promptKey: "challenges.stewardship7day.day6.prompt",
        practiceKey: "challenges.stewardship7day.day6.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 7,
        scripture: "1 Timothy 6:6",
        principleKey: "challenges.stewardship7day.day7.principle",
        promptKey: "challenges.stewardship7day.day7.prompt",
        practiceKey: "challenges.stewardship7day.day7.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
    ],
  },
  {
    id: "sabbath-rest-5day",
    titleKey: "challenges.sabbathRest5day.title",
    descriptionKey: "challenges.sabbathRest5day.description",
    title: "",
    description: "",
    totalDays: 5,
    mode: MODE_KEYS.WORK,
    days: [
      {
        day: 1,
        scripture: "Exodus 20:8-10",
        principleKey: "challenges.sabbathRest5day.day1.principle",
        promptKey: "challenges.sabbathRest5day.day1.prompt",
        practiceKey: "challenges.sabbathRest5day.day1.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 2,
        scripture: "Mark 2:27",
        principleKey: "challenges.sabbathRest5day.day2.principle",
        promptKey: "challenges.sabbathRest5day.day2.prompt",
        practiceKey: "challenges.sabbathRest5day.day2.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 3,
        scripture: "Psalm 46:10",
        principleKey: "challenges.sabbathRest5day.day3.principle",
        promptKey: "challenges.sabbathRest5day.day3.prompt",
        practiceKey: "challenges.sabbathRest5day.day3.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 4,
        scripture: "Luke 10:41-42",
        principleKey: "challenges.sabbathRest5day.day4.principle",
        promptKey: "challenges.sabbathRest5day.day4.prompt",
        practiceKey: "challenges.sabbathRest5day.day4.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
      {
        day: 5,
        scripture: "Isaiah 58:13-14",
        principleKey: "challenges.sabbathRest5day.day5.principle",
        promptKey: "challenges.sabbathRest5day.day5.prompt",
        practiceKey: "challenges.sabbathRest5day.day5.practice",
        principle: "",
        prompt: "",
        practice: "",
      },
    ],
  },
  {
    id: "listening-3day",
    titleKey: "challenges.listening3day.title",
    descriptionKey: "challenges.listening3day.description",
    title: "Listening Practice",
    description: "Three days to slow down, listen first, and hear what lies beneath the first answer.",
    totalDays: 3,
    mode: MODE_KEYS.LIFE,
    days: [
      {
        day: 1,
        scripture: "James 1:19",
        principleKey: "challenges.listening3day.day1.principle",
        promptKey: "challenges.listening3day.day1.prompt",
        practiceKey: "challenges.listening3day.day1.practice",
        principle: "Let every person be quick to hear, slow to speak, slow to anger.",
        prompt: "Who or what needs your first full attention today?",
        practice: "Listen before answering once today.",
      },
      {
        day: 2,
        scripture: "Proverbs 18:13",
        principleKey: "challenges.listening3day.day2.principle",
        promptKey: "challenges.listening3day.day2.prompt",
        practiceKey: "challenges.listening3day.day2.practice",
        principle: "If one gives an answer before he hears, it is his folly and shame.",
        prompt: "What question are you rushing past?",
        practice: "Pause before you respond.",
      },
      {
        day: 3,
        scripture: "Proverbs 20:5",
        principleKey: "challenges.listening3day.day3.principle",
        promptKey: "challenges.listening3day.day3.prompt",
        practiceKey: "challenges.listening3day.day3.practice",
        principle: "The purpose in a man's heart is like deep water, but a man of understanding will draw it out.",
        prompt: "Where would a better question help more than a quick opinion?",
        practice: "Ask one slower, wiser question.",
      },
    ],
  },
  {
    id: "repair-4day",
    titleKey: "challenges.repair4day.title",
    descriptionKey: "challenges.repair4day.description",
    title: "Repair Practice",
    description: "Four days to name hurt honestly, lower defensiveness, and move toward repair.",
    totalDays: 4,
    mode: MODE_KEYS.LIFE,
    days: [
      {
        day: 1,
        scripture: "Matthew 5:23-24",
        principleKey: "challenges.repair4day.day1.principle",
        promptKey: "challenges.repair4day.day1.prompt",
        practiceKey: "challenges.repair4day.day1.practice",
        principle: "First be reconciled to your brother.",
        prompt: "Who needs your attention because something is unresolved?",
        practice: "Name the relationship that needs repair.",
      },
      {
        day: 2,
        scripture: "Ephesians 4:26-27",
        principleKey: "challenges.repair4day.day2.principle",
        promptKey: "challenges.repair4day.day2.prompt",
        practiceKey: "challenges.repair4day.day2.practice",
        principle: "Be angry and do not sin; do not let the sun go down on your anger.",
        prompt: "Where has anger been left to simmer?",
        practice: "Take one step before the sun sets.",
      },
      {
        day: 3,
        scripture: "James 5:16",
        principleKey: "challenges.repair4day.day3.principle",
        promptKey: "challenges.repair4day.day3.prompt",
        practiceKey: "challenges.repair4day.day3.practice",
        principle: "Confess your sins to one another and pray for one another.",
        prompt: "What confession or apology would make the next conversation more honest?",
        practice: "Write the apology you have been avoiding.",
      },
      {
        day: 4,
        scripture: "Romans 12:18",
        principleKey: "challenges.repair4day.day4.principle",
        promptKey: "challenges.repair4day.day4.prompt",
        practiceKey: "challenges.repair4day.day4.practice",
        principle: "If possible, so far as it depends on you, live peaceably with all.",
        prompt: "What is the most faithful peace you can pursue without pretending everything is fine?",
        practice: "Choose peace as far as it depends on you.",
      },
    ],
  },
  {
    id: "generosity-7day",
    titleKey: "challenges.generosity7day.title",
    descriptionKey: "challenges.generosity7day.description",
    title: "Generosity Practice",
    description: "Seven days of giving from conviction, not pressure, while honoring capacity and wise limits.",
    totalDays: 7,
    mode: MODE_KEYS.GENEROSITY,
    days: [
      {
        day: 1,
        scripture: "Proverbs 11:25",
        principleKey: "challenges.generosity7day.day1.principle",
        promptKey: "challenges.generosity7day.day1.prompt",
        practiceKey: "challenges.generosity7day.day1.practice",
        principle: "A generous person will be enriched, and one who waters will himself be watered.",
        prompt: "Where have you received more than you notice?",
        practice: "Notice one place abundance wants to move.",
      },
      {
        day: 2,
        scripture: "2 Corinthians 8:12",
        principleKey: "challenges.generosity7day.day2.principle",
        promptKey: "challenges.generosity7day.day2.prompt",
        practiceKey: "challenges.generosity7day.day2.practice",
        principle: "It is acceptable according to what a person has, not according to what he does not have.",
        prompt: "What is a generous amount for this season, not an ideal season?",
        practice: "Name a proportion that fits your capacity.",
      },
      {
        day: 3,
        scripture: "Acts 20:35",
        principleKey: "challenges.generosity7day.day3.principle",
        promptKey: "challenges.generosity7day.day3.prompt",
        practiceKey: "challenges.generosity7day.day3.practice",
        principle: "It is more blessed to give than to receive.",
        prompt: "Who could be strengthened by what is already in your hand?",
        practice: "Give something helpful without fanfare.",
      },
      {
        day: 4,
        scripture: "Proverbs 19:17",
        principleKey: "challenges.generosity7day.day4.principle",
        promptKey: "challenges.generosity7day.day4.prompt",
        practiceKey: "challenges.generosity7day.day4.practice",
        principle: "Whoever is generous to the poor lends to the Lord.",
        prompt: "What act of mercy would you like to remember instead of fear?",
        practice: "Write one way kindness can be practical.",
      },
      {
        day: 5,
        scripture: "1 Timothy 6:17-19",
        principleKey: "challenges.generosity7day.day5.principle",
        promptKey: "challenges.generosity7day.day5.prompt",
        practiceKey: "challenges.generosity7day.day5.practice",
        principle: "Set your hope on God, who richly provides us with everything to enjoy.",
        prompt: "What does hope look like when riches are not the center?",
        practice: "Set your hope on something sturdier than money.",
      },
      {
        day: 6,
        scripture: "2 Corinthians 9:11",
        principleKey: "challenges.generosity7day.day6.principle",
        promptKey: "challenges.generosity7day.day6.prompt",
        practiceKey: "challenges.generosity7day.day6.practice",
        principle: "You will be enriched in every way to be generous in every way.",
        prompt: "Where does gratitude make giving feel freer?",
        practice: "Give thanks for what you can share.",
      },
      {
        day: 7,
        scripture: "Deuteronomy 15:10",
        principleKey: "challenges.generosity7day.day7.principle",
        promptKey: "challenges.generosity7day.day7.prompt",
        practiceKey: "challenges.generosity7day.day7.practice",
        principle: "Because of this the Lord your God will bless you in all your work and in all that you undertake.",
        prompt: "What gift feels cheerful and sustainable right now?",
        practice: "Choose the next generous step with joy.",
      },
    ],
  },
  {
    id: "attention-fast-5day",
    titleKey: "challenges.attentionFast5day.title",
    descriptionKey: "challenges.attentionFast5day.description",
    title: "Attention Fast",
    description: "Five days to clear noise, recover focus, and choose what deserves attention.",
    totalDays: 5,
    mode: MODE_KEYS.PURPOSE,
    days: [
      {
        day: 1,
        scripture: "Psalm 90:12",
        principleKey: "challenges.attentionFast5day.day1.principle",
        promptKey: "challenges.attentionFast5day.day1.prompt",
        practiceKey: "challenges.attentionFast5day.day1.practice",
        principle: "Teach us to number our days that we may get a heart of wisdom.",
        prompt: "Where is your time leaking away?",
        practice: "Name one attention leak.",
      },
      {
        day: 2,
        scripture: "Proverbs 4:23",
        principleKey: "challenges.attentionFast5day.day2.principle",
        promptKey: "challenges.attentionFast5day.day2.prompt",
        practiceKey: "challenges.attentionFast5day.day2.practice",
        principle: "Keep your heart with all vigilance, for from it flow the springs of life.",
        prompt: "What is shaping your inner life without permission?",
        practice: "Guard one boundary around attention.",
      },
      {
        day: 3,
        scripture: "Matthew 6:22-23",
        principleKey: "challenges.attentionFast5day.day3.principle",
        promptKey: "challenges.attentionFast5day.day3.prompt",
        practiceKey: "challenges.attentionFast5day.day3.practice",
        principle: "The eye is the lamp of the body.",
        prompt: "What brings clarity, and what clouds it?",
        practice: "Let your attention rest on one clear thing.",
      },
      {
        day: 4,
        scripture: "Romans 12:2",
        principleKey: "challenges.attentionFast5day.day4.principle",
        promptKey: "challenges.attentionFast5day.day4.prompt",
        practiceKey: "challenges.attentionFast5day.day4.practice",
        principle: "Be transformed by the renewal of your mind.",
        prompt: "What pattern is normal but not wise?",
        practice: "Refuse one noisy pattern today.",
      },
      {
        day: 5,
        scripture: "Philippians 4:8",
        principleKey: "challenges.attentionFast5day.day5.principle",
        promptKey: "challenges.attentionFast5day.day5.prompt",
        practiceKey: "challenges.attentionFast5day.day5.practice",
        principle: "Whatever is true, honorable, just, pure, lovely, and commendable, think about these things.",
        prompt: "What is true, honorable, and worth keeping in view?",
        practice: "Name one thing worth your attention.",
      },
    ],
  },
  {
    id: "hidden-service-5day",
    titleKey: "challenges.hiddenService5day.title",
    descriptionKey: "challenges.hiddenService5day.description",
    title: "Hidden Service",
    description: "Five days to serve quietly, release credit, and notice faithfulness no one needs to see.",
    totalDays: 5,
    mode: MODE_KEYS.LIFE,
    days: [
      {
        day: 1,
        scripture: "Matthew 6:3-4",
        principleKey: "challenges.hiddenService5day.day1.principle",
        promptKey: "challenges.hiddenService5day.day1.prompt",
        practiceKey: "challenges.hiddenService5day.day1.practice",
        principle: "Your Father who sees in secret will reward you.",
        prompt: "Where can you do good without announcing it?",
        practice: "Choose one hidden act of service.",
      },
      {
        day: 2,
        scripture: "Galatians 5:13",
        principleKey: "challenges.hiddenService5day.day2.principle",
        promptKey: "challenges.hiddenService5day.day2.prompt",
        practiceKey: "challenges.hiddenService5day.day2.practice",
        principle: "Through love serve one another.",
        prompt: "How can freedom become loving action instead of self-focus?",
        practice: "Serve in a way no one needs to praise.",
      },
      {
        day: 3,
        scripture: "1 Peter 4:10",
        principleKey: "challenges.hiddenService5day.day3.principle",
        promptKey: "challenges.hiddenService5day.day3.prompt",
        practiceKey: "challenges.hiddenService5day.day3.practice",
        principle: "As each has received a gift, use it to serve one another.",
        prompt: "What gift can you use to help someone else today?",
        practice: "Use one gift to bless another.",
      },
      {
        day: 4,
        scripture: "Colossians 3:23-24",
        principleKey: "challenges.hiddenService5day.day4.principle",
        promptKey: "challenges.hiddenService5day.day4.prompt",
        practiceKey: "challenges.hiddenService5day.day4.practice",
        principle: "Whatever you do, work heartily, as for the Lord and not for men.",
        prompt: "What changes when you serve for God rather than applause?",
        practice: "Work with steady, unseen faithfulness.",
      },
      {
        day: 5,
        scripture: "Hebrews 6:10",
        principleKey: "challenges.hiddenService5day.day5.principle",
        promptKey: "challenges.hiddenService5day.day5.prompt",
        practiceKey: "challenges.hiddenService5day.day5.practice",
        principle: "God is not unjust so as to overlook your work and the love you have shown.",
        prompt: "Who has been quietly helped by your consistency?",
        practice: "Notice the good that has already been done.",
      },
    ],
  },
  {
    id: "read-with-me-7day",
    titleKey: "challenges.readWithMe7day.title",
    descriptionKey: "challenges.readWithMe7day.description",
    title: "Reading Practice",
    description: "Seven days of careful reading, asking what is true, and letting wisdom shape your hearing.",
    totalDays: 7,
    mode: MODE_KEYS.PURPOSE,
    days: [
      {
        day: 1,
        scripture: "Proverbs 18:15",
        principleKey: "challenges.readWithMe7day.day1.principle",
        promptKey: "challenges.readWithMe7day.day1.prompt",
        practiceKey: "challenges.readWithMe7day.day1.practice",
        principle: "An intelligent heart acquires knowledge, and the ear of the wise seeks knowledge.",
        prompt: "What do you want to understand more deeply?",
        practice: "Read one passage with full attention.",
      },
      {
        day: 2,
        scripture: "James 1:19",
        principleKey: "challenges.readWithMe7day.day2.principle",
        promptKey: "challenges.readWithMe7day.day2.prompt",
        practiceKey: "challenges.readWithMe7day.day2.practice",
        principle: "Let every person be quick to hear, slow to speak, slow to anger.",
        prompt: "What would it look like to be quick to hear and slow to speak?",
        practice: "Listen before you explain.",
      },
      {
        day: 3,
        scripture: "Proverbs 4:7",
        principleKey: "challenges.readWithMe7day.day3.principle",
        promptKey: "challenges.readWithMe7day.day3.prompt",
        practiceKey: "challenges.readWithMe7day.day3.practice",
        principle: "The beginning of wisdom is this: Get wisdom.",
        prompt: "Where do you need wisdom more than more information?",
        practice: "Choose wisdom over speed.",
      },
      {
        day: 4,
        scripture: "Psalm 119:105",
        principleKey: "challenges.readWithMe7day.day4.principle",
        promptKey: "challenges.readWithMe7day.day4.prompt",
        practiceKey: "challenges.readWithMe7day.day4.practice",
        principle: "Your word is a lamp to my feet and a light to my path.",
        prompt: "What is the lamp for the next step, not the whole map?",
        practice: "Let one line guide the next step.",
      },
      {
        day: 5,
        scripture: "Acts 17:11",
        principleKey: "challenges.readWithMe7day.day5.principle",
        promptKey: "challenges.readWithMe7day.day5.prompt",
        practiceKey: "challenges.readWithMe7day.day5.practice",
        principle: "They received the word with all eagerness, examining the Scriptures daily.",
        prompt: "What would it mean to test what you hear with care?",
        practice: "Verify before you absorb.",
      },
      {
        day: 6,
        scripture: "Colossians 3:16",
        principleKey: "challenges.readWithMe7day.day6.principle",
        promptKey: "challenges.readWithMe7day.day6.prompt",
        practiceKey: "challenges.readWithMe7day.day6.practice",
        principle: "Let the word of Christ dwell in you richly.",
        prompt: "What word needs to dwell richly in you today?",
        practice: "Sit with one passage a little longer.",
      },
      {
        day: 7,
        scripture: "2 Timothy 2:15",
        principleKey: "challenges.readWithMe7day.day7.principle",
        promptKey: "challenges.readWithMe7day.day7.prompt",
        practiceKey: "challenges.readWithMe7day.day7.practice",
        principle: "Do your best to present yourself to God as one approved, rightly handling the word of truth.",
        prompt: "What does faithful handling of truth look like now?",
        practice: "Read with care, patience, and humility.",
      },
    ],
  },
];

export function getChallengeById(id: string): ChallengeDefinition | undefined {
  return challengeDefinitions.find((c) => c.id === id);
}
