import { THEME_KEYS } from "@/lib/theme-keys";
import type { Mode } from "@/lib/mode-keys";
import type { WisdomEntryData } from "@/lib/wisdom-data";

export type ScriptureCounselEntry = WisdomEntryData & {
  modes: Mode[];
};

export const scriptureCounselIndex: ScriptureCounselEntry[] = [
  {
    theme: THEME_KEYS.COUNSEL,
    scripture: "Proverbs 3:5-6",
    principle: "Trust in the Lord reshapes planning by submitting the path to him.",
    context: "Proverbs calls the wise person to lean less on isolated self-confidence and more on reverent dependence.",
    application: "When a decision feels heavy, bring the path before God, name what you do not know, and choose the next step that can be walked honestly.",
    keywords: ["trust", "guidance", "direction", "planning", "discernment", "path", "uncertainty"],
    emotions: ["confusion", "fear", "pressure", "hope"],
    questions: [
      "Where am I leaning only on my own understanding?",
      "What part of this path needs to be acknowledged before God?",
      "What next step is faithful even if the whole road is not visible?",
    ],
    modes: ["Purpose", "Work", "Money", "Life"],
  },
  {
    theme: THEME_KEYS.DILIGENCE,
    scripture: "James 1:5",
    principle: "Wisdom can be asked for humbly when discernment is lacking.",
    context: "James writes to pressured believers and invites them to seek wisdom from God rather than pretend certainty.",
    application: "Do not rush to sound certain. Ask for wisdom, gather counsel, and let the decision be formed with humility.",
    keywords: ["wisdom", "ask", "discernment", "unclear", "guidance", "decision"],
    emotions: ["uncertainty", "anxiety", "humility"],
    questions: [
      "What wisdom do I actually need before acting?",
      "Have I asked God plainly for wisdom here?",
      "Who could help me see what I am missing?",
    ],
    modes: ["Purpose", "Work", "Money", "Generosity", "Life"],
  },
  {
    theme: THEME_KEYS.COUNSEL,
    scripture: "Proverbs 11:14",
    principle: "Wise guidance protects people from avoidable collapse.",
    context: "Proverbs treats counsel as protection, especially when a decision affects more than one person.",
    application: "Before a high-stakes yes, invite people who can test your assumptions without flattering your urgency.",
    keywords: ["counsel", "guidance", "advice", "mentor", "community", "safety", "plans"],
    emotions: ["urgency", "confidence", "confusion"],
    questions: [
      "Who has enough wisdom and distance to test this decision?",
      "What counsel would I be tempted to avoid?",
      "Have I confused privacy with wisdom?",
    ],
    modes: ["Work", "Money", "Purpose", "Generosity"],
  },
  {
    theme: THEME_KEYS.COUNSEL,
    scripture: "Proverbs 19:20-21",
    principle: "Receiving counsel trains the heart to honor the Lord's purpose over personal plans.",
    context: "The proverb holds human planning and divine purpose together without despising either.",
    application: "Make your plan visible, let it be corrected, and hold it with open hands rather than clenched control.",
    keywords: ["plans", "purpose", "counsel", "correction", "future", "calling"],
    emotions: ["ambition", "uncertainty", "control"],
    questions: [
      "What part of my plan needs correction?",
      "Am I willing to be taught before I decide?",
      "What would change if God's purpose mattered more than my preferred timing?",
    ],
    modes: ["Purpose", "Work", "Money"],
  },
  {
    theme: THEME_KEYS.COST_COUNTING,
    scripture: "Luke 14:28-30",
    principle: "Commitment should be preceded by sober cost counting.",
    context: "Jesus uses ordinary building wisdom to expose the danger of enthusiastic beginnings without realistic follow-through.",
    application: "Write down costs, limits, obligations, and what happens if the decision takes longer than expected.",
    keywords: ["cost", "count", "business", "startup", "commitment", "runway", "risk", "plan"],
    emotions: ["excitement", "pressure", "impatience"],
    questions: [
      "What is the cost if this takes twice as long?",
      "What obligation would I be accepting?",
      "What smaller experiment could reveal the truth first?",
    ],
    modes: ["Work", "Money", "Purpose"],
  },
  {
    theme: THEME_KEYS.DILIGENCE,
    scripture: "Proverbs 16:3",
    principle: "Work becomes steadier when it is committed to the Lord.",
    context: "Proverbs does not erase planning; it orders planning under faithful dependence.",
    application: "Before moving, commit the work, motives, timing, and outcome to God, then act with disciplined clarity.",
    keywords: ["work", "plans", "commit", "career", "business", "stability", "calling"],
    emotions: ["ambition", "anxiety", "hope"],
    questions: [
      "What motive in this work needs to be committed to God?",
      "What would faithful steadiness look like this week?",
      "What outcome am I trying to control?",
    ],
    modes: ["Work", "Purpose", "Money"],
  },
  {
    theme: THEME_KEYS.DILIGENCE,
    scripture: "Colossians 3:23-24",
    principle: "Work can be offered to the Lord rather than performed for human approval alone.",
    context: "Paul reframes ordinary labor by locating its deepest accountability before Christ.",
    application: "Do excellent work without making praise, title, or recognition the source of your identity.",
    keywords: ["work", "career", "approval", "performance", "calling", "service", "diligence"],
    emotions: ["approval", "weariness", "ambition"],
    questions: [
      "Whose approval is quietly ruling this decision?",
      "What would faithful work look like without applause?",
      "Is this role forming love and integrity or only performance?",
    ],
    modes: ["Work", "Purpose", "Life"],
  },
  {
    theme: THEME_KEYS.DILIGENCE,
    scripture: "Proverbs 22:29",
    principle: "Skillful, diligent work has a public weight over time.",
    context: "The proverb honors competence, practice, and excellence without turning status into identity.",
    application: "Invest in skill, reliability, and craft instead of chasing shortcuts or titles.",
    keywords: ["skill", "diligence", "career", "craft", "excellence", "promotion", "work"],
    emotions: ["ambition", "comparison", "impatience"],
    questions: [
      "What skill would make this path more faithful?",
      "Am I chasing recognition before formation?",
      "What quiet discipline would compound over time?",
    ],
    modes: ["Work", "Purpose"],
  },
  {
    theme: THEME_KEYS.DILIGENCE,
    scripture: "Proverbs 13:11",
    principle: "Steady gain is wiser than wealth gathered by shortcuts.",
    context: "Proverbs contrasts fast, fragile gain with patient accumulation and faithful work.",
    application: "Be suspicious of hype, secrecy, and pressure. Prefer transparent, patient, understandable paths.",
    keywords: ["wealth", "investment", "quick", "hype", "shortcut", "saving", "gain", "money"],
    emotions: ["fomo", "greed", "urgency", "envy"],
    questions: [
      "Is this path understandable and transparent?",
      "Would I still want this without the promise of quick gain?",
      "What patient habit would be wiser?",
    ],
    modes: ["Money", "Work"],
  },
  {
    theme: THEME_KEYS.DILIGENCE,
    scripture: "Proverbs 21:5",
    principle: "Diligent planning tends toward abundance while haste tends toward lack.",
    context: "This proverb warns that speed can feel productive while quietly weakening judgment.",
    application: "Slow down, write the plan, test assumptions, and refuse pressure that cannot survive scrutiny.",
    keywords: ["plan", "budget", "haste", "impulse", "saving", "investment", "decision"],
    emotions: ["urgency", "panic", "excitement"],
    questions: [
      "What would I choose if I were not hurried?",
      "What plan can be tested before money moves?",
      "Which assumption needs evidence?",
    ],
    modes: ["Money", "Work", "Purpose"],
  },
  {
    theme: THEME_KEYS.STEWARDSHIP,
    scripture: "1 Timothy 6:17-19",
    principle: "Wealth is uncertain, so hope belongs in God and resources should be used for good.",
    context: "Paul addresses those with resources and redirects them from pride to generosity and eternal perspective.",
    application: "Build responsibly, but do not let savings, income, or assets become your security or identity.",
    keywords: ["wealth", "rich", "security", "hope", "generosity", "money", "stewardship"],
    emotions: ["pride", "fear", "security", "comparison"],
    questions: [
      "Where am I placing hope that belongs in God?",
      "How can resources serve good rather than ego?",
      "What would generous security look like?",
    ],
    modes: ["Money", "Generosity"],
  },
  {
    theme: THEME_KEYS.CONTENTMENT,
    scripture: "Hebrews 13:5",
    principle: "Contentment grows where God's presence is trusted more than money.",
    context: "Hebrews connects freedom from the love of money with the promise of God's faithful presence.",
    application: "Name enough, practice gratitude, and resist the lie that more money is the only path to peace.",
    keywords: ["contentment", "money", "enough", "security", "comparison", "greed"],
    emotions: ["scarcity", "envy", "fear", "restlessness"],
    questions: [
      "What am I asking money to provide emotionally?",
      "What is enough in this season?",
      "Where do I need to trust God's presence today?",
    ],
    modes: ["Money", "Life"],
  },
  {
    theme: THEME_KEYS.CONTENTMENT,
    scripture: "Matthew 6:19-21",
    principle: "Treasure reveals and trains the heart.",
    context: "Jesus teaches that storing treasure is never merely financial; it forms love, attention, and worship.",
    application: "Look at where money, time, and desire are accumulating, because those patterns show what is shaping your heart.",
    keywords: ["treasure", "heart", "money", "priority", "desire", "values"],
    emotions: ["desire", "envy", "ambition"],
    questions: [
      "What does my spending say I treasure?",
      "Where is my heart being trained?",
      "What investment would align with eternal value?",
    ],
    modes: ["Money", "Generosity", "Purpose"],
  },
  {
    theme: THEME_KEYS.DEBT,
    scripture: "Romans 13:8",
    principle: "Love is the continuing debt that should govern obligations.",
    context: "Paul urges believers to honor obligations while making love the central duty.",
    application: "Take financial obligations seriously, and do not let borrowing crowd out love, integrity, or responsibility.",
    keywords: ["debt", "owe", "obligation", "loan", "love", "responsibility"],
    emotions: ["stress", "pressure", "shame"],
    questions: [
      "What obligation would this create?",
      "Would this debt limit my ability to love responsibly?",
      "What repayment path is honest?",
    ],
    modes: ["Money", "Generosity", "Life"],
  },
  {
    theme: THEME_KEYS.GENEROSITY,
    scripture: "Acts 20:35",
    principle: "Giving carries a blessedness that grasping cannot produce.",
    context: "Paul remembers Jesus' teaching as he commends humble labor and care for the weak.",
    application: "Let generosity be concrete and joyful, but keep it tied to truthful capacity and love.",
    keywords: ["give", "giving", "generosity", "help", "support", "charity", "blessing"],
    emotions: ["joy", "guilt", "gratitude"],
    questions: [
      "Is this giving free or pressured?",
      "Who is being strengthened by this gift?",
      "What capacity do I need to tell the truth about?",
    ],
    modes: ["Generosity", "Money", "Life"],
  },
  {
    theme: THEME_KEYS.GENEROSITY,
    scripture: "1 John 3:17-18",
    principle: "Love becomes visible when compassion takes truthful action.",
    context: "John refuses a love that remains only verbal when a real need is visible and capacity exists.",
    application: "When you can help, move beyond sentiment. When you cannot, be honest and do not perform compassion.",
    keywords: ["help", "need", "family", "support", "love", "action", "compassion"],
    emotions: ["guilt", "compassion", "pressure"],
    questions: [
      "What need is actually in front of me?",
      "What action would be loving and truthful?",
      "Am I avoiding help or overpromising help?",
    ],
    modes: ["Generosity", "Life", "Money"],
  },
  {
    theme: THEME_KEYS.GENEROSITY,
    scripture: "2 Corinthians 8:12-14",
    principle: "Generosity is measured with willingness and proportion, not pressure beyond capacity.",
    context: "Paul commends eager giving while also acknowledging fairness, capacity, and mutual care.",
    application: "Give from what you have, not from guilt about what you do not have. Sustainable generosity tells the truth.",
    keywords: ["giving", "capacity", "sustainable", "fairness", "support", "family", "church"],
    emotions: ["guilt", "pressure", "joy"],
    questions: [
      "What do I actually have capacity to give?",
      "Is this willingness or compulsion?",
      "How can generosity and responsibility both be honored?",
    ],
    modes: ["Generosity", "Money"],
  },
  {
    theme: THEME_KEYS.GENEROSITY,
    scripture: "Galatians 6:2-5",
    principle: "Love carries burdens, but each person also bears responsible load.",
    context: "Paul holds communal care and personal responsibility together.",
    application: "Help where love calls you, but do not confuse rescue, enabling, and responsibility.",
    keywords: ["burden", "family", "support", "boundaries", "responsibility", "help", "enable"],
    emotions: ["guilt", "resentment", "compassion", "pressure"],
    questions: [
      "Is this a burden to help carry or a load they must bear?",
      "What boundary would make love truthful?",
      "Am I rescuing to avoid discomfort?",
    ],
    modes: ["Generosity", "Life", "Money"],
  },
  {
    theme: THEME_KEYS.PROVISION_AND_ANXIETY,
    scripture: "1 Peter 5:6-7",
    principle: "Anxiety can be cast on God because his care is real.",
    context: "Peter speaks to suffering believers and joins humility under God with active release of anxiety.",
    application: "Name the burden honestly, entrust it to God, and take the next responsible step without carrying tomorrow in your body today.",
    keywords: ["anxiety", "worry", "care", "fear", "burden", "stress", "humility"],
    emotions: ["anxiety", "fear", "overwhelm"],
    questions: [
      "What anxiety am I still trying to carry alone?",
      "What can be cast on God right now?",
      "What is today's responsible step?",
    ],
    modes: ["Life", "Money", "Purpose", "Work"],
  },
  {
    theme: THEME_KEYS.PROVISION_AND_ANXIETY,
    scripture: "Philippians 4:6-7",
    principle: "Prayerful dependence guards the heart better than anxious control.",
    context: "Paul writes from hardship and invites believers to bring requests to God with thanksgiving.",
    application: "Turn the worry into a concrete prayer, add gratitude, then act from guarded peace rather than panic.",
    keywords: ["anxiety", "prayer", "peace", "worry", "request", "thanksgiving"],
    emotions: ["anxiety", "panic", "fear"],
    questions: [
      "What request needs to become prayer instead of rumination?",
      "What can I thank God for honestly?",
      "What would guarded peace change about my pace?",
    ],
    modes: ["Life", "Money", "Purpose", "Work"],
  },
  {
    theme: THEME_KEYS.PROVISION_AND_ANXIETY,
    scripture: "Psalm 23:1-6",
    principle: "The Lord's shepherding presence steadies need, fear, and restoration.",
    context: "The psalm pictures God as shepherd, guide, host, protector, and restorer.",
    application: "When you feel driven, return to the Shepherd's pace: receive care, walk the next path, and refuse to be ruled by fear.",
    keywords: ["rest", "guidance", "fear", "provision", "shepherd", "peace", "restoration"],
    emotions: ["fear", "weariness", "loneliness", "anxiety"],
    questions: [
      "Where do I need to receive care rather than drive harder?",
      "What valley am I walking through with God, not alone?",
      "What would restoration look like today?",
    ],
    modes: ["Life", "Purpose", "Work"],
  },
  {
    theme: THEME_KEYS.PROVISION_AND_ANXIETY,
    scripture: "Isaiah 41:10",
    principle: "God's presence answers fear with strength, help, and upholding.",
    context: "Isaiah speaks comfort to God's people in weakness and displacement.",
    application: "Do not treat fear as the final authority. Let God's promised presence slow your body and strengthen the next faithful action.",
    keywords: ["fear", "strength", "help", "presence", "discouraged", "weak"],
    emotions: ["fear", "discouragement", "weakness"],
    questions: [
      "What fear is speaking loudest?",
      "What help do I need to receive?",
      "What action would be possible if I were upheld?",
    ],
    modes: ["Life", "Purpose", "Work", "Money"],
  },
  {
    theme: THEME_KEYS.CONTENTMENT,
    scripture: "Romans 12:2",
    principle: "Discernment grows through renewed thinking, not conformity to pressure.",
    context: "Paul frames transformation as a whole-life offering that learns to test what pleases God.",
    application: "Notice the voices shaping you, then step back long enough for renewed judgment to form.",
    keywords: ["discernment", "renewal", "pressure", "conformity", "purpose", "mind", "calling"],
    emotions: ["pressure", "confusion", "restlessness"],
    questions: [
      "What pressure am I being conformed by?",
      "What thought pattern needs renewal?",
      "What would help me test this decision before acting?",
    ],
    modes: ["Purpose", "Work", "Life"],
  },
  {
    theme: THEME_KEYS.CONTENTMENT,
    scripture: "Micah 6:8",
    principle: "God's will is never detached from justice, mercy, and humble walking.",
    context: "Micah condenses covenant faithfulness into a lived posture before God and neighbor.",
    application: "Test the decision by whether it strengthens justice, mercy, humility, and faithful walking.",
    keywords: ["justice", "mercy", "humility", "calling", "purpose", "ethics", "decision"],
    emotions: ["conviction", "confusion", "ambition"],
    questions: [
      "Does this path help me do justice?",
      "Where does mercy belong in this decision?",
      "Would this choice make me more humble before God?",
    ],
    modes: ["Purpose", "Work", "Generosity", "Life"],
  },
  {
    theme: THEME_KEYS.CONTENTMENT,
    scripture: "Ephesians 2:10",
    principle: "Calling is received as prepared good work, not manufactured identity.",
    context: "Paul grounds good works in grace and God's workmanship, not self-salvation.",
    application: "Look for faithful work already being prepared before you, without making productivity your worth.",
    keywords: ["calling", "purpose", "identity", "work", "good works", "grace"],
    emotions: ["restlessness", "hope", "pressure"],
    questions: [
      "What good work is already in front of me?",
      "Am I trying to earn identity through usefulness?",
      "What grace-grounded step can I take?",
    ],
    modes: ["Purpose", "Work", "Life"],
  },
  {
    theme: THEME_KEYS.CONTENTMENT,
    scripture: "Psalm 37:3-7",
    principle: "Faithful waiting is active trust, not passivity.",
    context: "The psalm counsels trust, delight, commitment, and stillness before the Lord when outcomes feel uncertain.",
    application: "Do the good you know to do, commit the way to God, and resist forcing clarity before its time.",
    keywords: ["wait", "trust", "timing", "patience", "direction", "peace"],
    emotions: ["impatience", "longing", "uncertainty"],
    questions: [
      "What good can I do while I wait?",
      "What way needs to be committed to the Lord?",
      "Where am I forcing timing?",
    ],
    modes: ["Purpose", "Work", "Money", "Life"],
  },
  {
    theme: THEME_KEYS.RECOVERY,
    scripture: "Matthew 11:28-30",
    principle: "Jesus invites the weary into his yoke, not into more driven self-rescue.",
    context: "Jesus speaks rest to burdened people and describes his way as gentle and lowly.",
    application: "When exhaustion is driving the decision, slow down and receive a gentler pace before choosing.",
    keywords: ["rest", "burnout", "weary", "burden", "gentle", "pace", "work"],
    emotions: ["weariness", "burnout", "overwhelm"],
    questions: [
      "Am I deciding from rest or exhaustion?",
      "What burden am I carrying that Jesus did not assign?",
      "What would a gentler yoke change today?",
    ],
    modes: ["Life", "Work", "Purpose"],
  },
  {
    theme: THEME_KEYS.RECOVERY,
    scripture: "Mark 6:31",
    principle: "Rest can be a faithful response to crowded demands.",
    context: "Jesus calls his disciples away to rest after intense ministry and need around them.",
    application: "Do not make constant availability the measure of faithfulness. Some wisdom comes after rest.",
    keywords: ["rest", "busy", "burnout", "work", "ministry", "capacity", "demands"],
    emotions: ["exhaustion", "pressure", "guilt"],
    questions: [
      "What demand is crowding out rest?",
      "Would this decision look different after sleep?",
      "Where do I need permission to be finite?",
    ],
    modes: ["Work", "Life", "Generosity"],
  },
  {
    theme: THEME_KEYS.FREEDOM,
    scripture: "Galatians 5:1",
    principle: "Freedom in Christ should not be surrendered to a new yoke of slavery.",
    context: "Paul warns believers not to return to bondage after receiving freedom in Christ.",
    application: "Ask whether the decision increases faithful freedom or creates bondage to approval, debt, addiction, or fear.",
    keywords: ["freedom", "bondage", "approval", "addiction", "debt", "fear", "slavery"],
    emotions: ["fear", "pressure", "shame"],
    questions: [
      "What yoke would this decision put on me?",
      "Where is freedom being threatened?",
      "What would it mean to stand firm?",
    ],
    modes: ["Life", "Money", "Work"],
  },
  {
    theme: THEME_KEYS.FREEDOM,
    scripture: "John 8:31-32",
    principle: "Freedom is connected to abiding in Jesus' word and receiving truth.",
    context: "Jesus ties discipleship, truth, and freedom together rather than treating freedom as mere self-expression.",
    application: "Bring the hidden or distorted part of the decision into truth; freedom begins where falsehood loses cover.",
    keywords: ["truth", "freedom", "hidden", "discipleship", "honesty", "accountability"],
    emotions: ["shame", "fear", "relief"],
    questions: [
      "What truth needs to be named?",
      "Where am I calling avoidance freedom?",
      "How can I abide in Jesus' word here?",
    ],
    modes: ["Life", "Purpose", "Work"],
  },
  {
    theme: THEME_KEYS.CONFESSION,
    scripture: "1 John 1:9",
    principle: "Confession meets God's faithful forgiveness and cleansing.",
    context: "John resists denial and invites honest confession before a faithful and just God.",
    application: "Do not hide failure under vague shame. Confess specifically, receive mercy, and take the next truthful step.",
    keywords: ["confession", "forgiveness", "cleansing", "sin", "failure", "mercy"],
    emotions: ["shame", "guilt", "hope"],
    questions: [
      "What needs to be confessed specifically?",
      "Am I hiding in shame instead of receiving mercy?",
      "What repair step follows confession?",
    ],
    modes: ["Life"],
  },
  {
    theme: THEME_KEYS.RECOVERY,
    scripture: "Psalm 51:10-12",
    principle: "Restoration asks for a clean heart and a steady spirit, not image management.",
    context: "David prays after grave sin, seeking inward renewal and restored joy.",
    application: "Move from concealment to repentance, then ask God for a renewed heart and steady obedience.",
    keywords: ["restore", "repentance", "renew", "heart", "failure", "recovery"],
    emotions: ["shame", "grief", "hope"],
    questions: [
      "What am I trying to manage instead of confess?",
      "What would a renewed spirit do next?",
      "Who can help me walk in truth?",
    ],
    modes: ["Life"],
  },
  {
    theme: THEME_KEYS.PURITY,
    scripture: "2 Timothy 2:22",
    principle: "Fleeing distorted desire is paired with pursuing righteousness in community.",
    context: "Paul gives Timothy both an avoidance and a pursuit, with companions who call on the Lord.",
    application: "Do not only resist temptation; replace it with pursuit, community, and concrete escape routes.",
    keywords: ["temptation", "purity", "flee", "community", "desire", "accountability"],
    emotions: ["temptation", "shame", "resolve"],
    questions: [
      "What do I need to flee without negotiating?",
      "What good pursuit should replace the pattern?",
      "Who can pursue righteousness with me?",
    ],
    modes: ["Life"],
  },
  {
    theme: THEME_KEYS.PURITY,
    scripture: "Psalm 119:9-11",
    principle: "God's word guards the way when it is treasured in the heart.",
    context: "The psalm links a clean way with seeking God and storing up his word.",
    application: "Put Scripture where temptation usually begins: attention, memory, imagination, and habit.",
    keywords: ["purity", "word", "heart", "temptation", "habit", "attention"],
    emotions: ["temptation", "longing", "resolve"],
    questions: [
      "Where does temptation usually begin for me?",
      "What verse needs to be stored up this week?",
      "What habit would guard my way?",
    ],
    modes: ["Life"],
  },
  {
    theme: THEME_KEYS.FREEDOM,
    scripture: "1 Corinthians 10:13",
    principle: "Temptation is not ultimate; God provides endurance and a way out.",
    context: "Paul encourages believers that temptation is real but not unique, sovereign, or hopeless.",
    application: "Look for the exit early: change the environment, contact help, and act before desire gathers force.",
    keywords: ["temptation", "escape", "way out", "endurance", "addiction", "freedom"],
    emotions: ["temptation", "pressure", "hope"],
    questions: [
      "Where is the way out right now?",
      "What environment needs to change?",
      "Who can I contact before I am overwhelmed?",
    ],
    modes: ["Life"],
  },
  {
    theme: THEME_KEYS.RECOVERY,
    scripture: "Romans 8:1",
    principle: "In Christ, conviction is not condemnation.",
    context: "Paul announces freedom from condemnation as part of life in the Spirit.",
    application: "Let conviction lead to repentance and repair, but refuse shame that says you are beyond mercy.",
    keywords: ["shame", "condemnation", "mercy", "guilt", "identity", "recovery"],
    emotions: ["shame", "guilt", "despair", "hope"],
    questions: [
      "Am I hearing conviction or condemnation?",
      "What repair step does mercy make possible?",
      "What identity truth do I need to receive?",
    ],
    modes: ["Life"],
  },
  {
    theme: THEME_KEYS.RECOVERY,
    scripture: "2 Corinthians 12:9",
    principle: "God's grace meets weakness with sufficient power.",
    context: "Paul learns that weakness can become a place where Christ's power rests on him.",
    application: "Do not wait to be strong before asking for help. Bring weakness into grace and structure support around it.",
    keywords: ["weakness", "grace", "strength", "help", "recovery", "limits"],
    emotions: ["weakness", "shame", "weariness"],
    questions: [
      "What weakness am I hiding?",
      "How might grace meet me there?",
      "What support structure would honor my limits?",
    ],
    modes: ["Life", "Work"],
  },
  {
    theme: THEME_KEYS.COUNSEL,
    scripture: "Matthew 18:15-17",
    principle: "Conflict should move toward truthful repair, not avoidance or public escalation.",
    context: "Jesus gives a path for addressing sin directly, with increasing communal wisdom when needed.",
    application: "Start with honest, private truth where safe and appropriate, and seek wise help if repair requires it.",
    keywords: ["conflict", "relationship", "repair", "truth", "conversation", "boundaries"],
    emotions: ["anger", "fear", "hurt"],
    questions: [
      "What truth needs to be spoken directly?",
      "Is this safe to address privately?",
      "Who can help if repair requires witnesses or counsel?",
    ],
    modes: ["Life", "Work"],
  },
  {
    theme: THEME_KEYS.COUNSEL,
    scripture: "Ephesians 4:15",
    principle: "Truth and love belong together in mature speech.",
    context: "Paul describes growth into Christlike maturity through truthful, loving speech.",
    application: "Do not choose between honesty and gentleness. Say what is true in a way that seeks restoration.",
    keywords: ["truth", "love", "communication", "conflict", "maturity", "relationship"],
    emotions: ["fear", "anger", "tension"],
    questions: [
      "What truth must not be avoided?",
      "How can love shape the way I say it?",
      "What outcome would maturity seek?",
    ],
    modes: ["Life", "Work", "Generosity"],
  },
  {
    theme: THEME_KEYS.CONTENTMENT,
    scripture: "Matthew 7:24-27",
    principle: "A life built on Jesus' words can withstand pressure.",
    context: "Jesus ends the Sermon on the Mount by contrasting hearing with obedient building.",
    application: "Test the decision by whether it builds obedience or merely responds to emotion, image, or speed.",
    keywords: ["foundation", "obedience", "pressure", "storm", "decision", "wisdom"],
    emotions: ["pressure", "fear", "urgency"],
    questions: [
      "What foundation is this decision building on?",
      "What would obedience look like, not just hearing?",
      "Would this hold under pressure?",
    ],
    modes: ["Purpose", "Life", "Work", "Money"],
  },
  {
    theme: THEME_KEYS.CONTENTMENT,
    scripture: "Psalm 1:1-3",
    principle: "A fruitful life is shaped by delight, meditation, and rootedness.",
    context: "The psalm contrasts a life formed by God's instruction with a life carried by surrounding counsel.",
    application: "Notice whose counsel is shaping you, and build rhythms that root you before visible fruit is demanded.",
    keywords: ["formation", "wisdom", "counsel", "fruit", "habits", "meditation"],
    emotions: ["restlessness", "comparison", "longing"],
    questions: [
      "Whose counsel is forming me?",
      "What rhythm would root me in God's word?",
      "Am I demanding fruit without roots?",
    ],
    modes: ["Purpose", "Life", "Work"],
  },
  {
    theme: THEME_KEYS.STEWARDSHIP,
    scripture: "Genesis 2:15",
    principle: "Human work begins as stewardship: cultivating and keeping what is entrusted.",
    context: "Before the fall, work is given as a vocation of care, cultivation, and responsibility.",
    application: "Ask what has been entrusted to you to cultivate, protect, and serve, not only what you can gain.",
    keywords: ["work", "stewardship", "calling", "cultivate", "responsibility", "creation"],
    emotions: ["purpose", "ambition", "confusion"],
    questions: [
      "What has been entrusted to me to cultivate?",
      "What needs protection, not just growth?",
      "How does this work serve more than my ambition?",
    ],
    modes: ["Work", "Purpose", "Money"],
  },
  {
    theme: THEME_KEYS.STEWARDSHIP,
    scripture: "1 Corinthians 4:2",
    principle: "Stewards are called to faithfulness.",
    context: "Paul describes entrusted responsibility in terms of reliable faithfulness before God.",
    application: "Measure the decision by faithfulness with what is entrusted, not only by visible success.",
    keywords: ["steward", "faithfulness", "responsibility", "trust", "management", "money", "work"],
    emotions: ["pressure", "ambition", "fear"],
    questions: [
      "What does faithfulness require here?",
      "What has actually been entrusted to me?",
      "Am I chasing success at the expense of reliability?",
    ],
    modes: ["Money", "Work", "Purpose", "Generosity"],
  },
  {
    theme: THEME_KEYS.CONTENTMENT,
    scripture: "Luke 12:15",
    principle: "Life does not consist in the abundance of possessions.",
    context: "Jesus warns against covetousness before telling a parable about wealth without rich life toward God.",
    application: "Do not let possessions, salary, or lifestyle become the measure of life. Ask what the decision is doing to your soul.",
    keywords: ["possessions", "greed", "wealth", "lifestyle", "comparison", "salary"],
    emotions: ["envy", "greed", "restlessness"],
    questions: [
      "What am I tempted to measure life by?",
      "What desire is being enlarged by this choice?",
      "How can I become rich toward God?",
    ],
    modes: ["Money", "Purpose", "Life"],
  },
  {
    theme: THEME_KEYS.GENEROSITY,
    scripture: "Proverbs 3:27-28",
    principle: "Do not withhold good when it is truly in your power to act.",
    context: "Proverbs presses timely neighbor-love where capacity and opportunity are real.",
    application: "If help is wise and within capacity, do not hide behind delay. If it is not in your power, say so truthfully.",
    keywords: ["help", "neighbor", "withhold", "capacity", "timely", "support"],
    emotions: ["hesitation", "guilt", "compassion"],
    questions: [
      "Is it truly in my power to help?",
      "Am I delaying what love requires?",
      "What truthful limit needs to be named?",
    ],
    modes: ["Generosity", "Life", "Money"],
  },
  {
    theme: THEME_KEYS.PROVISION_AND_ANXIETY,
    scripture: "Lamentations 3:22-24",
    principle: "God's mercies are new in the morning, so hope can begin again.",
    context: "In grief and ruin, the poet remembers the Lord's steadfast love and faithfulness.",
    application: "When yesterday feels heavy, receive today's mercy and take the next small faithful step.",
    keywords: ["mercy", "hope", "morning", "grief", "faithfulness", "begin again"],
    emotions: ["grief", "discouragement", "hope"],
    questions: [
      "What mercy is available for today?",
      "Where do I need to begin again?",
      "What small step matches hope?",
    ],
    modes: ["Life", "Purpose"],
  },
  {
    theme: THEME_KEYS.RECOVERY,
    scripture: "Hebrews 10:24-25",
    principle: "Faithfulness is strengthened by gathered encouragement.",
    context: "Hebrews urges believers not to isolate but to stir one another toward love and good works.",
    application: "If isolation is weakening you, move toward trusted people who can encourage concrete obedience.",
    keywords: ["community", "encouragement", "isolation", "accountability", "church", "habits"],
    emotions: ["loneliness", "discouragement", "shame"],
    questions: [
      "Where has isolation weakened me?",
      "Who can stir me toward love and good works?",
      "What gathering or conversation should I not neglect?",
    ],
    modes: ["Life", "Purpose", "Work"],
  },
  {
    theme: THEME_KEYS.COUNSEL,
    scripture: "Ecclesiastes 4:9-12",
    principle: "Companionship provides help, resilience, and protection.",
    context: "Ecclesiastes observes the practical goodness of not walking alone.",
    application: "Do not carry a major decision alone. Invite trustworthy companions who can help you up if you fall.",
    keywords: ["companionship", "counsel", "alone", "support", "resilience", "friendship"],
    emotions: ["loneliness", "pressure", "fear"],
    questions: [
      "Where am I trying to walk alone?",
      "Who can help me stand if this gets hard?",
      "What support would make this decision wiser?",
    ],
    modes: ["Life", "Work", "Purpose", "Money"],
  },
];
