import enTranslations from "@/locales/en.json";
import type { LanguageCode } from "@/lib/localization";

type RuntimePanelCopy = {
  timelineReady: string;
  nextInDecisions: string;
  decisionNextTitleDefault: string;
  decisionNextBodyActive: string;
  decisionNextBodyEmpty: string;
  decisionCompanionHeading: string;
  decisionCompanionSub: string;
  ruleOfLife: string;
  ruleOfLifePrincipleSingular: string;
  ruleOfLifePrinciplePlural: string;
  ruleOfLifeSummary: string;
  decisionPracticeLine: string;
  nextInReflect: string;
  reflectNextTitleDefault: string;
  reflectNextTitleActive: string;
  reflectNextBodyDefault: string;
  reflectNextBodyActive: string;
  reflectIntro: string;
  wisdomCheck: string;
  wisdomCheckSummaryDefault: string;
  wisdomCheckUrgency: string;
  wisdomCheckSlower: string;
  decisionScan: string;
  reflectionHistory: string;
  savedReflectionSingular: string;
  savedReflectionPlural: string;
  reflectionHistorySummaryActive: string;
  reflectionHistorySummaryDefault: string;
  nextInLibrary: string;
  libraryNextTitleDefault: string;
  libraryNextBodySearch: string;
  libraryTryPrefix: string;
  libraryDescription: string;
  fullWisdomLibrary: string;
  moreAnchors: string;
};

const runtimePanelCopy: Partial<Record<LanguageCode, RuntimePanelCopy>> = {
  en: enTranslations.runtimePanel as RuntimePanelCopy,
  tl: {
    timelineReady: "Handa na ang iyong timeline para subaybayan ang mga desisyon, pattern, payo, at pagkatuto.",
    nextInDecisions: "Susunod sa Mga Desisyon",
    decisionNextTitleDefault: "Pangalanan ang desisyong may pressure",
    decisionNextBodyActive: "I-update ang payo, gastos, paghihintay, at mga palatandaan ng kapayapaan upang magkaroon ng totoong timeline ang desisyon.",
    decisionNextBodyEmpty: "Magsimula sa isang desisyon at sa pressure na kaakibat nito. Susubaybayan ni Aletheia ang karunungan, payo, at kahandaan sa paglipas ng panahon.",
    decisionCompanionHeading: "Subaybayan ang desisyon hanggang may sapat na panahon ang karunungan upang kumilos.",
    decisionCompanionSub: "Memorya, payo, paghihintay, pag-export ng buod, at isang mahinahong signal ng kahandaan para sa mahahalagang pagpili.",
    ruleOfLife: "Rule of Life",
    ruleOfLifePrincipleSingular: "prinsipyo",
    ruleOfLifePrinciplePlural: "mga prinsipyo",
    ruleOfLifeSummary: "Ang mga personal na prinsipyo ay malapit lang, ngunit nakatiklop hanggang humuhubog ka na ng isang desisyon.",
    decisionPracticeLine: "Pangalanan kung ano ang sapat para sa panahong ito",
    nextInReflect: "Susunod sa Pagninilay",
    reflectNextTitleDefault: "Magsimula sa isang tapat na pangungusap",
    reflectNextTitleActive: "Tapusin ang pagninilay sa harap mo",
    reflectNextBodyDefault: "Gamitin ang Wisdom Check para sa mabilis na pagtingin ng discernment, o isulat ang napapansin mo tungkol sa pera, trabaho, takot, pagkamapagbigay, o bilis.",
    reflectNextBodyActive: "I-save ang napapansin mo habang sariwa pa ang insight.",
    reflectIntro: "Gamitin ang Wisdom Check para pabagalin ang desisyon, at i-save ang napapansin mo bago lumipas ang sandali.",
    wisdomCheck: "Wisdom Check",
    wisdomCheckSummaryDefault: "Buksan kapag ang desisyon ay kailangang mabilis na suriin.",
    wisdomCheckUrgency: "napansing urgency",
    wisdomCheckSlower: "mas mabagal ang pressure",
    decisionScan: "Pagsusuri ng desisyon",
    reflectionHistory: "Kasaysayan ng pagninilay",
    savedReflectionSingular: "naka-save na pagninilay",
    savedReflectionPlural: "mga naka-save na pagninilay",
    reflectionHistorySummaryActive: "Buksan ang mga nakaraang pagninilay kapag gusto mong balikan ang paglago.",
    reflectionHistorySummaryDefault: "Mananatili rito ang mga nakaraang pagninilay kapag na-save na.",
    nextInLibrary: "Susunod sa Aklatan",
    libraryNextTitleDefault: "Maghanap ng isang tema ng karunungan",
    libraryNextBodySearch: "Buksan ang isang reperensiya ng Kasulatan upang basahin ang konteksto ng sipi at kung bakit ito mahalaga dito.",
    libraryTryPrefix: "Subukan",
    libraryDescription: "Isang piniling balon ng karunungan na may mga application note ayon sa wika at mga label ng pampublikong domain na salin.",
    fullWisdomLibrary: "Buong aklatan ng karunungan",
    moreAnchors: "mas maraming angkla",
  },
  ar: {
    timelineReady: "الخط الزمني جاهز لتتبع القرارات والأنماط والمشورة والتعلم.",
    nextInDecisions: "التالي في القرارات",
    decisionNextTitleDefault: "سمِّ القرار تحت الضغط",
    decisionNextBodyActive: "حدِّث المشورة والكلفة والانتظار وعلامات السلام حتى يكون للقرار خط زمني حقيقي.",
    decisionNextBodyEmpty: "ابدأ بقرار واحد والضغط المرتبط به. ستتبع Aletheia الحكمة والمشورة والاستعداد عبر الزمن.",
    decisionCompanionHeading: "تتبّع القرار حتى تحظى الحكمة بوقت لتعمل.",
    decisionCompanionSub: "الذاكرة، المشورة، الانتظار، تصدير الملخص، وإشارة هادئة للاستعداد للقرارات الكبيرة.",
    ruleOfLife: "قاعدة الحياة",
    ruleOfLifePrincipleSingular: "مبدأ",
    ruleOfLifePrinciplePlural: "مبادئ",
    ruleOfLifeSummary: "تبقى المبادئ الشخصية قريبة، لكنها مطوية حتى تبدأ بتشكيل قرار.",
    decisionPracticeLine: "سمِّ ما يكفي لهذه المرحلة",
    nextInReflect: "التالي في التأمل",
    reflectNextTitleDefault: "ابدأ بجملة صادقة واحدة",
    reflectNextTitleActive: "أكمل التأمل أمامك",
    reflectNextBodyDefault: "استخدم فحص الحكمة لمسح سريع للتمييز، أو اكتب ما تلاحظه عن المال أو العمل أو الخوف أو الكرم أو الوتيرة.",
    reflectNextBodyActive: "احفظ ما تلاحظه ما دام الإلهام ما يزال طازجًا.",
    reflectIntro: "استخدم فحص الحكمة لإبطاء القرار، ثم احفظ ما تلاحظه قبل أن تمر اللحظة.",
    wisdomCheck: "فحص الحكمة",
    wisdomCheckSummaryDefault: "افتحه عندما يحتاج القرار إلى فحص سريع للتمييز.",
    wisdomCheckUrgency: "تم رصد استعجال",
    wisdomCheckSlower: "الضغط يبدو أهدأ",
    decisionScan: "فحص القرار",
    reflectionHistory: "سجل التأمل",
    savedReflectionSingular: "تأمل محفوظ",
    savedReflectionPlural: "تأملات محفوظة",
    reflectionHistorySummaryActive: "افتح تأملاتك السابقة عندما تريد مراجعة النمو.",
    reflectionHistorySummaryDefault: "ستبقى التأملات السابقة هنا بعد حفظها.",
    nextInLibrary: "التالي في المكتبة",
    libraryNextTitleDefault: "ابحث عن موضوع حكمة واحد",
    libraryNextBodySearch: "افتح مرجعًا كتابيًا لقراءة سياق المقطع ولماذا يهم هنا.",
    libraryTryPrefix: "جرّب",
    libraryDescription: "قاعدة حكمة منتقاة مع ملاحظات تطبيق تراعي اللغة وعلامات الترجمة العامة.",
    fullWisdomLibrary: "مكتبة الحكمة الكاملة",
    moreAnchors: "مزيد من المراسي",
  },
  hi: {
    timelineReady: "आपकी टाइमलाइन निर्णयों, पैटर्न, सलाह और सीख को ट्रैक करने के लिए तैयार है।",
    nextInDecisions: "निर्णयों में अगला",
    decisionNextTitleDefault: "दबाव के बीच निर्णय का नाम दीजिए",
    decisionNextBodyActive: "सलाह, लागत, प्रतीक्षा, और शांति के संकेत अपडेट कीजिए ताकि निर्णय के पास एक वास्तविक timeline हो।",
    decisionNextBodyEmpty: "एक निर्णय और उससे जुड़ा दबाव लेकर शुरू कीजिए। Aletheia समय के साथ बुद्धि, सलाह, और readiness को ट्रैक करेगा।",
    decisionCompanionHeading: "निर्णय को तब तक ट्रैक कीजिए जब तक बुद्धि को काम करने का समय न मिल जाए।",
    decisionCompanionSub: "Memory, सलाह, प्रतीक्षा, summary export, और बड़े विकल्पों के लिए एक शांत readiness signal.",
    ruleOfLife: "जीवन-नियम",
    ruleOfLifePrincipleSingular: "सिद्धांत",
    ruleOfLifePrinciplePlural: "सिद्धांत",
    ruleOfLifeSummary: "व्यक्तिगत सिद्धांत पास रहते हैं, लेकिन तब तक folded रहते हैं जब तक आप किसी निर्णय को आकार नहीं दे रहे हों।",
    decisionPracticeLine: "इस मौसम के लिए पर्याप्त क्या है, उसे नाम दीजिए",
    nextInReflect: "चिंतन में अगला",
    reflectNextTitleDefault: "एक ईमानदार वाक्य से शुरू कीजिए",
    reflectNextTitleActive: "अपने सामने चल रहे चिंतन को पूरा कीजिए",
    reflectNextBodyDefault: "Wisdom Check का उपयोग करके त्वरित discernment scan कीजिए, या लिखिए कि धन, काम, डर, उदारता, या गति के बारे में आप क्या देख रहे हैं।",
    reflectNextBodyActive: "जो आप देख रहे हैं उसे तब तक सहेजिए जब तक insight ताज़ा है।",
    reflectIntro: "Wisdom Check का उपयोग करके निर्णय को धीमा कीजिए, फिर क्षण बीतने से पहले जो आप देखते हैं उसे सहेजिए।",
    wisdomCheck: "Wisdom Check",
    wisdomCheckSummaryDefault: "जब किसी निर्णय को त्वरित discernment scan चाहिए, तब खोलिए।",
    wisdomCheckUrgency: "urgency महसूस हुई",
    wisdomCheckSlower: "pressure धीमी लग रही है",
    decisionScan: "निर्णय स्कैन",
    reflectionHistory: "चिंतन इतिहास",
    savedReflectionSingular: "सहेजा गया चिंतन",
    savedReflectionPlural: "सहेजे गए चिंतन",
    reflectionHistorySummaryActive: "विकास की समीक्षा करना चाहें, तो पुराने चिंतन खोलिए।",
    reflectionHistorySummaryDefault: "सहेजे जाने के बाद पुराने चिंतन यहीं रहेंगे।",
    nextInLibrary: "पुस्तकालय में अगला",
    libraryNextTitleDefault: "एक बुद्धि-विषय खोजिए",
    libraryNextBodySearch: "एक शास्त्र-संदर्भ खोलिए ताकि उस अंश का संदर्भ और उसका महत्व यहाँ पढ़ सकें।",
    libraryTryPrefix: "आजमाइए",
    libraryDescription: "एक चुनी हुई ज्ञान-आधार, जिसमें भाषा-सचेत application notes और सार्वजनिक-डोमेन अनुवाद labels हैं।",
    fullWisdomLibrary: "पूर्ण ज्ञान-पुस्तकालय",
    moreAnchors: "और आधार",
  },
  es: {
    timelineReady: "Tu línea de tiempo está lista para registrar decisiones, patrones, consejo y aprendizaje.",
    nextInDecisions: "Siguiente en Decisiones",
    decisionNextTitleDefault: "Nombra la decision bajo presion",
    decisionNextBodyActive: "Actualiza consejo, costo, espera y paz para que la decision tenga una linea de tiempo real.",
    decisionNextBodyEmpty: "Empieza con una decision y la presion asociada. Aletheia seguira sabiduria, consejo y preparacion con el tiempo.",
    decisionCompanionHeading: "Sigue la decision hasta que la sabiduria tenga tiempo de obrar.",
    decisionCompanionSub: "Memoria, consejo, espera, exportacion de resumen y una senal tranquila de preparacion para decisiones importantes.",
    ruleOfLife: "Regla de vida",
    ruleOfLifePrincipleSingular: "principio",
    ruleOfLifePrinciplePlural: "principios",
    ruleOfLifeSummary: "Los principios personales quedan cerca, pero colapsados hasta que estes moldeando una decision.",
    decisionPracticeLine: "Nombra lo que es suficiente para esta temporada",
    nextInReflect: "Siguiente en Reflexion",
    reflectNextTitleDefault: "Comienza con una frase honesta",
    reflectNextTitleActive: "Termina la reflexion frente a ti",
    reflectNextBodyDefault: "Usa Chequeo de sabiduria para un escaneo rapido de discernimiento, o escribe lo que notas sobre dinero, trabajo, temor, generosidad o ritmo.",
    reflectNextBodyActive: "Guarda lo que estas notando mientras la intuicion aun esta fresca.",
    reflectIntro: "Usa Chequeo de sabiduria para bajar el ritmo de una decision, luego guarda lo que notas antes de que pase el momento.",
    wisdomCheck: "Chequeo de sabiduria",
    wisdomCheckSummaryDefault: "Abre cuando una decision necesite un escaneo rapido de discernimiento.",
    wisdomCheckUrgency: "urgencia detectada",
    wisdomCheckSlower: "la presion parece mas calmada",
    decisionScan: "Escaneo de decision",
    reflectionHistory: "Historial de reflexion",
    savedReflectionSingular: "reflexion guardada",
    savedReflectionPlural: "reflexiones guardadas",
    reflectionHistorySummaryActive: "Abre tus reflexiones pasadas cuando quieras revisar crecimiento.",
    reflectionHistorySummaryDefault: "Las reflexiones pasadas quedaran aqui una vez guardadas.",
    nextInLibrary: "Siguiente en Biblioteca",
    libraryNextTitleDefault: "Busca un tema de sabiduria",
    libraryNextBodySearch: "Abre una referencia biblica para leer el contexto del pasaje y por que importa aqui.",
    libraryTryPrefix: "Prueba",
    libraryDescription: "Una base de sabiduria curada con notas de aplicacion segun idioma y etiquetas de traduccion de dominio publico.",
    fullWisdomLibrary: "Biblioteca completa de sabiduria",
    moreAnchors: "anclas mas",
  },
  fr: {
    timelineReady: "Votre chronologie est prête à suivre les décisions, les schémas, le conseil et l’apprentissage.",
    nextInDecisions: "Suite dans Decisions",
    decisionNextTitleDefault: "Nommez la decision sous pression",
    decisionNextBodyActive: "Mettez a jour conseil, cout, attente et paix pour donner une vraie chronologie a la decision.",
    decisionNextBodyEmpty: "Commencez avec une decision et la pression associee. Aletheia suivra sagesse, conseil et preparation dans le temps.",
    decisionCompanionHeading: "Suivez la decision jusqu'a ce que la sagesse ait le temps d'agir.",
    decisionCompanionSub: "Memoire, conseil, attente, export de resume et signal calme de preparation pour les grands choix.",
    ruleOfLife: "Regle de vie",
    ruleOfLifePrincipleSingular: "principe",
    ruleOfLifePrinciplePlural: "principes",
    ruleOfLifeSummary: "Les principes personnels restent proches, mais reduits tant que vous ne faconnez pas une decision.",
    decisionPracticeLine: "Nomme ce qui est suffisant pour cette saison",
    nextInReflect: "Suite dans Reflexion",
    reflectNextTitleDefault: "Commencez par une phrase honnete",
    reflectNextTitleActive: "Terminez la reflexion devant vous",
    reflectNextBodyDefault: "Utilisez Verification de sagesse pour un scan rapide de discernement, ou ecrivez ce que vous remarquez sur l'argent, le travail, la peur, la generosite ou le rythme.",
    reflectNextBodyActive: "Enregistrez ce que vous remarquez pendant que l'intuition est encore fraiche.",
    reflectIntro: "Utilisez Verification de sagesse pour ralentir une decision, puis enregistrez ce que vous remarquez avant que le moment ne passe.",
    wisdomCheck: "Verification de sagesse",
    wisdomCheckSummaryDefault: "Ouvrez quand une decision a besoin d'un scan rapide de discernement.",
    wisdomCheckUrgency: "urgence detectee",
    wisdomCheckSlower: "la pression semble plus calme",
    decisionScan: "Scan de decision",
    reflectionHistory: "Historique de reflexion",
    savedReflectionSingular: "reflexion enregistree",
    savedReflectionPlural: "reflexions enregistrees",
    reflectionHistorySummaryActive: "Ouvrez vos reflexions passees quand vous voulez revoir la croissance.",
    reflectionHistorySummaryDefault: "Les reflexions passees resteront ici une fois enregistrees.",
    nextInLibrary: "Suite dans Bibliotheque",
    libraryNextTitleDefault: "Recherchez un theme de sagesse",
    libraryNextBodySearch: "Ouvrez une reference biblique pour lire le contexte du passage et pourquoi cela compte ici.",
    libraryTryPrefix: "Essayez",
    libraryDescription: "Une base de sagesse choisie avec des notes d'application selon la langue et des etiquettes de traduction du domaine public.",
    fullWisdomLibrary: "Bibliotheque complete de sagesse",
    moreAnchors: "ancrages de plus",
  },
  pt: {
    timelineReady: "Sua linha do tempo está pronta para acompanhar decisões, padrões, conselho e aprendizado.",
    nextInDecisions: "Proximo em Decisoes",
    decisionNextTitleDefault: "Nomeie a decisao sob pressao",
    decisionNextBodyActive: "Atualize conselho, custo, espera e paz para que a decisao tenha uma linha do tempo real.",
    decisionNextBodyEmpty: "Comece com uma decisao e a pressao ligada a ela. Aletheia vai acompanhar sabedoria, conselho e prontidao ao longo do tempo.",
    decisionCompanionHeading: "Acompanhe a decisao ate que a sabedoria tenha tempo para agir.",
    decisionCompanionSub: "Memoria, conselho, espera, exportacao de resumo e um sinal calmo de prontidao para escolhas importantes.",
    ruleOfLife: "Regra de vida",
    ruleOfLifePrincipleSingular: "principio",
    ruleOfLifePrinciplePlural: "principios",
    ruleOfLifeSummary: "Principios pessoais ficam por perto, mas recolhidos ate voce estar moldando uma decisao.",
    decisionPracticeLine: "Nomeie o que e suficiente para esta temporada",
    nextInReflect: "Proximo em Reflexao",
    reflectNextTitleDefault: "Comece com uma frase honesta",
    reflectNextTitleActive: "Conclua a reflexao diante de voce",
    reflectNextBodyDefault: "Use Verificacao de sabedoria para um exame rapido de discernimento, ou escreva o que voce percebe sobre dinheiro, trabalho, medo, generosidade ou ritmo.",
    reflectNextBodyActive: "Salve o que voce esta percebendo enquanto o insight ainda esta fresco.",
    reflectIntro: "Use Verificacao de sabedoria para desacelerar uma decisao e salve o que voce percebe antes que o momento passe.",
    wisdomCheck: "Verificacao de sabedoria",
    wisdomCheckSummaryDefault: "Abra quando uma decisao precisar de um exame rapido de discernimento.",
    wisdomCheckUrgency: "urgencia percebida",
    wisdomCheckSlower: "a pressao parece mais calma",
    decisionScan: "Exame de decisao",
    reflectionHistory: "Historico de reflexao",
    savedReflectionSingular: "reflexao salva",
    savedReflectionPlural: "reflexoes salvas",
    reflectionHistorySummaryActive: "Abra reflexoes passadas quando quiser revisar crescimento.",
    reflectionHistorySummaryDefault: "Reflexoes passadas ficarao aqui apos salvar.",
    nextInLibrary: "Proximo na Biblioteca",
    libraryNextTitleDefault: "Pesquise um tema de sabedoria",
    libraryNextBodySearch: "Abra uma referencia biblica para ler o contexto da passagem e por que ela importa aqui.",
    libraryTryPrefix: "Tente",
    libraryDescription: "Uma base de sabedoria curada com notas de aplicacao por idioma e rotulos de traducoes em dominio publico.",
    fullWisdomLibrary: "Biblioteca completa de sabedoria",
    moreAnchors: "ancoras a mais",
  },
  de: {
    timelineReady: "Deine Zeitleiste ist bereit, Entscheidungen, Muster, Rat und Lernen im Blick zu behalten.",
    nextInDecisions: "Als Nächstes in Entscheidungen",
    decisionNextTitleDefault: "Benenne die Entscheidung unter Druck",
    decisionNextBodyActive: "Aktualisiere Rat, Kosten, Warten und Frieden, damit die Entscheidung eine echte Zeitleiste hat.",
    decisionNextBodyEmpty: "Beginne mit einer Entscheidung und dem dazugehörigen Druck. Aletheia verfolgt Weisheit, Rat und Bereitschaft über die Zeit.",
    decisionCompanionHeading: "Verfolge die Entscheidung, bis Weisheit Zeit hatte zu wirken.",
    decisionCompanionSub: "Speicher, Rat, Warten, Zusammenfassungsexport und ein ruhiges Bereitschaftssignal für große Entscheidungen.",
    ruleOfLife: "Lebensregel",
    ruleOfLifePrincipleSingular: "Prinzip",
    ruleOfLifePrinciplePlural: "Prinzipien",
    ruleOfLifeSummary: "Persönliche Prinzipien bleiben nah, aber eingeklappt, bis du eine Entscheidung formst.",
    decisionPracticeLine: "Benenne, was fur diese Saison genug ist",
    nextInReflect: "Als Nächstes in Reflexion",
    reflectNextTitleDefault: "Beginne mit einem ehrlichen Satz",
    reflectNextTitleActive: "Beende die Reflexion vor dir",
    reflectNextBodyDefault: "Nutze Weisheitscheck fur einen schnellen Unterscheidungs-Scan oder schreibe auf, was du uber Geld, Arbeit, Angst, Großzugigkeit oder Tempo bemerkst.",
    reflectNextBodyActive: "Speichere, was du bemerkst, solange die Einsicht noch frisch ist.",
    reflectIntro: "Nutze Weisheitscheck, um eine Entscheidung zu verlangsamen, und speichere dann, was du bemerkst, bevor der Moment vergeht.",
    wisdomCheck: "Weisheitscheck",
    wisdomCheckSummaryDefault: "Öffne es, wenn eine Entscheidung einen schnellen Unterscheidungs-Scan braucht.",
    wisdomCheckUrgency: "Dringlichkeit erkannt",
    wisdomCheckSlower: "Druck wirkt ruhiger",
    decisionScan: "Entscheidungs-Scan",
    reflectionHistory: "Reflexionsverlauf",
    savedReflectionSingular: "gespeicherte Reflexion",
    savedReflectionPlural: "gespeicherte Reflexionen",
    reflectionHistorySummaryActive: "Öffne vergangene Reflexionen, wenn du Wachstum prüfen willst.",
    reflectionHistorySummaryDefault: "Vergangene Reflexionen bleiben hier, sobald sie gespeichert sind.",
    nextInLibrary: "Als Nächstes in Bibliothek",
    libraryNextTitleDefault: "Suche ein Weisheitsthema",
    libraryNextBodySearch: "Öffne eine Bibelstelle, um den Kontext der Passage und ihre Bedeutung hier zu sehen.",
    libraryTryPrefix: "Versuche",
    libraryDescription: "Eine kuratierte Weisheitsbasis mit sprachsensiblen Anwendungshinweisen und Labels für gemeinfreie Übersetzungen.",
    fullWisdomLibrary: "Vollständige Weisheitsbibliothek",
    moreAnchors: "weitere Anker",
  },
  yo: {
    timelineReady: "Àkójọpọ̀ rẹ ti ṣetan láti tọ́pa àwọn ìpinnu, àwọn àpẹẹrẹ, ìmọ̀ràn, àti ẹ̀kọ́.",
    nextInDecisions: "Eto to nbo ninu Ipinnu",
    decisionNextTitleDefault: "So ipinnu to wa labẹ titẹ",
    decisionNextBodyActive: "Tun imoaran, iye owo, idaduro ati alaafia se ki ipinnu naa ni itan-akoko gidi.",
    decisionNextBodyEmpty: "Bere pelu ipinnu kan ati titẹ to so mọ ọ. Aletheia yoo maa tele ogbon, imoaran ati imurasile lori akoko.",
    decisionCompanionHeading: "Tele ipinnu naa titi ogbon yoo fi ni akoko lati sise.",
    decisionCompanionSub: "Irántí, imoaran, idaduro, gbigbejade akosile ati ami imurasile idakẹjẹ fun awon yiyan pataki.",
    ruleOfLife: "Ofin Igbesiaye",
    ruleOfLifePrincipleSingular: "ilana",
    ruleOfLifePrinciplePlural: "awon ilana",
    ruleOfLifeSummary: "Awon ilana ara eni wa nitosi, sugbon won wa ni pipade titi ti o fi n se agbekale ipinnu.",
    decisionPracticeLine: "So ohun to to fun asiko yi",
    nextInReflect: "Eto to nbo ninu Ironu",
    reflectNextTitleDefault: "Bere pelu gbolohun otito kan",
    reflectNextTitleActive: "Pari ironu to wa niwaju re",
    reflectNextBodyDefault: "Lo Ayewo ogbon fun ayewo iyara, tabi ko ohun ti o n ri nipa owo, ise, iberu, ofe ati iyara.",
    reflectNextBodyActive: "Fi ohun ti o n ri pamọ nigba ti imo naa tun n gbona.",
    reflectIntro: "Lo Ayewo ogbon lati din iyara ipinnu ku, ki o si fi ohun ti o n ri pamọ ki akoko naa to lo.",
    wisdomCheck: "Ayewo ogbon",
    wisdomCheckSummaryDefault: "Si i nigba ti ipinnu ba nilo ayewo iyara.",
    wisdomCheckUrgency: "a ti ri ijakule iyara",
    wisdomCheckSlower: "titẹ naa dabi pe o rọra",
    decisionScan: "Ayewo ipinnu",
    reflectionHistory: "Itan ironu",
    savedReflectionSingular: "ironu ti a fipamo",
    savedReflectionPlural: "awon ironu ti a fipamo",
    reflectionHistorySummaryActive: "Si awon ironu tele nigba ti o ba fe tun wo idagbasoke.",
    reflectionHistorySummaryDefault: "Awon ironu tele yoo wa nibi nigbati a ba fipamo won.",
    nextInLibrary: "Eto to nbo ninu Ile-ikawe",
    libraryNextTitleDefault: "Wa koko-oro ogbon kan",
    libraryNextBodySearch: "Si itọkasi iwe-mimo kan lati ka ayika gbolohun ati idi to fi se pataki nibi.",
    libraryTryPrefix: "Gbiyanju",
    libraryDescription: "Ibi-ipamọ ogbon ti a yan pẹlu awon alaye ohun elo to ba ede mu ati awon aami itumọ agbegbe gbangba.",
    fullWisdomLibrary: "Ile-ikawe ogbon kikun",
    moreAnchors: "awon oran afikun",
  },
  ig: {
    timelineReady: "Usoro oge gị dị njikere ịdekọ mkpebi, usoro, ndụmọdụ na mmụta.",
    nextInDecisions: "Ihe na-esote na Mkpebi",
    decisionNextTitleDefault: "Kowa mkpebi di n'okpuru nrụgide",
    decisionNextBodyActive: "Megharia nduzi, onu ahia, ichere na udo ka mkpebi nwee usoro oge eziokwu.",
    decisionNextBodyEmpty: "Bido na mkpebi otu na nrụgide ya. Aletheia ga-eso amamihe, nduzi na njikere n'oge.",
    decisionCompanionHeading: "Soro mkpebi ahu ruo mgbe amamihe nwere oge isoro oru.",
    decisionCompanionSub: "Ncheta, nduzi, ichere, ibupu nchikota, na akara njikere di juru nwayoo maka nhọrọ di mkpa.",
    ruleOfLife: "Iwu Ndụ",
    ruleOfLifePrincipleSingular: "usoro",
    ruleOfLifePrinciplePlural: "usoro",
    ruleOfLifeSummary: "Uzo ndu onwe onye na-anọ nso, mana a na-emechi ha ruo mgbe i na-akpụ mkpebi.",
    decisionPracticeLine: "Kowa ihe zuru ezu maka oge a",
    nextInReflect: "Ihe na-esote na Ntụgharị uche",
    reflectNextTitleDefault: "Bido na ahiriokwu eziokwu otu",
    reflectNextTitleActive: "Mechaa ntughari uche di n'ihu gi",
    reflectNextBodyDefault: "Jiri Nyocha amamihe maka nyocha ngwa ngwa, ma obu dee ihe i na-ahuta gbasara ego, oru, egwu, mmesa aka, ma obu ije.",
    reflectNextBodyActive: "Chekwaa ihe i na-ahuta mgbe nghota ka di ohuru.",
    reflectIntro: "Jiri Nyocha amamihe mee ka mkpebi jupụta nwayoo, wee chekwaa ihe i na-ahuta tupu oge gafee.",
    wisdomCheck: "Nyocha amamihe",
    wisdomCheckSummaryDefault: "Mepee ya mgbe mkpebi choro nyocha ngwa ngwa.",
    wisdomCheckUrgency: "a huru ngwa ngwa",
    wisdomCheckSlower: "nrụgide yiri ka o na-ala nwayoo",
    decisionScan: "Nyocha mkpebi",
    reflectionHistory: "Akuko ntughari uche",
    savedReflectionSingular: "ntughari uche echekwara",
    savedReflectionPlural: "ntughari uche echekwara",
    reflectionHistorySummaryActive: "Meghee ntughari uche gara aga mgbe ichoro ilele uto.",
    reflectionHistorySummaryDefault: "Ntughari uche gara aga ga-anoro ebe a mgbe echekwara ya.",
    nextInLibrary: "Ihe na-esote na Oba Akwukwo",
    libraryNextTitleDefault: "Chọọ isiokwu amamihe otu",
    libraryNextBodySearch: "Meghee akwukwo nso bibul ka i gụọ gburugburu amaokwu na ihe kpatara o ji di mkpa n'ebe a.",
    libraryTryPrefix: "Gbalịa",
    libraryDescription: "Ogige amamihe ahọpụtara nwere ihe omume dabere na asusu na akara ntughari nke ndi mmadu nile.",
    fullWisdomLibrary: "Oba akwukwo amamihe zuru oke",
    moreAnchors: "mkporo ozo",
  },
  ha: {
    timelineReady: "Jadawalin lokacinka ya shirya don bin sawun shawarwari, alamu, shawara da koyo.",
    nextInDecisions: "Na gaba a Shawara",
    decisionNextTitleDefault: "Sanya sunan shawarar da ke karkashin matsin lamba",
    decisionNextBodyActive: "Sabunta shawara, kudi, jira da salama domin shawarar ta samu jadawalin lokaci na gaskiya.",
    decisionNextBodyEmpty: "Fara da shawara daya da matsin da ke tattare da ita. Aletheia za ta bi hikima, shawara da shirye-shirye a tsawon lokaci.",
    decisionCompanionHeading: "Bi shawarar har sai hikima ta samu lokacin aiki.",
    decisionCompanionSub: "Ƙwaƙwalwa, shawara, jira, fitar da takaitawa, da alamar shirye-shirye mai nutsuwa don manyan zaɓuɓɓuka.",
    ruleOfLife: "Ka'idar Rayuwa",
    ruleOfLifePrincipleSingular: "ka'ida",
    ruleOfLifePrinciplePlural: "ka'idoji",
    ruleOfLifeSummary: "Ka'idojin mutum suna nan kusa, amma a rufe suke har sai kana tsara shawara.",
    decisionPracticeLine: "Sanya sunan abin da ya isa ga wannan kakar",
    nextInReflect: "Na gaba a Tunani",
    reflectNextTitleDefault: "Fara da jimla guda daya mai gaskiya",
    reflectNextTitleActive: "Kammala tunanin da ke gabanka",
    reflectNextBodyDefault: "Yi amfani da Duba hikima don duba gaggawa, ko rubuta abin da kake lura da shi game da kuɗi, aiki, tsoro, karimci ko sauri.",
    reflectNextBodyActive: "Ajiye abin da kake lura da shi yayin da fahimtar ke sabo.",
    reflectIntro: "Yi amfani da Duba hikima don rage saurin shawara, sannan ka ajiye abin da ka lura da shi kafin lokacin ya wuce.",
    wisdomCheck: "Duba hikima",
    wisdomCheckSummaryDefault: "Buɗe shi idan shawara na bukatar dubawa cikin sauri.",
    wisdomCheckUrgency: "an lura da gaggawa",
    wisdomCheckSlower: "matsin lamba ya yi sanyi",
    decisionScan: "Duba shawara",
    reflectionHistory: "Tarihin tunani",
    savedReflectionSingular: "tunanin da aka ajiye",
    savedReflectionPlural: "tunanin da aka ajiye",
    reflectionHistorySummaryActive: "Buɗe tunanin da suka gabata idan kana son duba ci gaba.",
    reflectionHistorySummaryDefault: "Tunanin da suka gabata za su tsaya a nan bayan an ajiye su.",
    nextInLibrary: "Na gaba a Laburare",
    libraryNextTitleDefault: "Nemi jigon hikima guda",
    libraryNextBodySearch: "Buɗe nassin Littafi Mai Tsarki don karanta mahallin ayar da dalilin muhimmancinsa a nan.",
    libraryTryPrefix: "Gwada",
    libraryDescription: "Tarin hikima da aka tace tare da bayanan amfani masu la'akari da harshe da alamun fassarar yankin jama'a.",
    fullWisdomLibrary: "Cikakken laburaren hikima",
    moreAnchors: "ƙarin ginshiƙai",
  },
};

export function runtimeCopyFor(language: LanguageCode): RuntimePanelCopy {
  return runtimePanelCopy[language] ?? runtimePanelCopy.en!;
}

