"use client";

import enTranslations from "@/locales/en.json";
import type { LanguageCode } from "@/lib/localization";

type View = "companion" | "decisions" | "reflect" | "library" | "account";

export const uiText: Partial<Record<
  LanguageCode,
  {
    nav: Record<View, string>;
    decideShort: string;
    guardrails: string;
    guardrailItems: string[];
    wisdomMode: string;
    currentLens: string;
    offline: string;
    languageSelect: string;
    bibleSelect: string;
    account: string;
    askTitle: string;
    askIntro: string;
    yourQuestion: string;
    askButton: string;
    startHere: string;
    ready: string;
    whatModeFor: string;
    deepChecks: string;
    blindSpots: string;
    maturitySignals: string;
    modeGuidance: string;
    change: string;
    showDetails: string;
    hideDetails: string;
    modeGuidancePreview: string;
    trustLayer: string;
    preferencesTitle: string;
    language: string;
    region: string;
    bible: string;
    voiceControls: string;
    available: string;
    englishFallback: string;
    greetingMorning?: string;
    greetingAfternoon?: string;
    greetingEvening?: string;
    greetingFallback?: string;
    greetingIntent?: string;
    personalizedPriority?: string;
    whatNext?: string;
    whatNextBody?: string;
    personalizationNudgeTitle?: string;
    personalizationNudgeBody?: string;
    personalizationNudgeAction?: string;
    continueDecision?: string;
    askOneQuestion?: string;
    askOneQuestionBody?: string;
    askNewQuestion?: string;
    askNewQuestionBody?: string;
    reflectToday?: string;
    reviewPattern?: string;
    enableNotifications?: string;
    enableSync?: string;
    notificationPromptBody?: string;
    syncDevicesBody?: string;
    startDecision?: string;
    startDecisionBody?: string;
    tinyPractice?: string;
    todaysCompanion?: string;
    todayPrefix?: string;
    wisdomPrinciple?: string;
    reflectionQuestion?: string;
    whatINotice?: string;
    context?: string;
    application?: string;
    carryThisToday?: string;
    carryWithMe?: string;
    carryCard?: string;
    createCard?: string;
    createWisdomPostcard?: string;
    carryScriptureForWeek?: string;
    scriptureMemory?: string;
    clearScriptureMemory?: string;
    weeklyWisdomReview?: string;
    weeklyReviewTitle?: string;
    weeklyReviewBody?: string;
    todayScriptureLabel?: string;
    todayQuestionLabel?: string;
    todayActionsLabel?: string;
    weeklyReviewHeading?: string;
    weeklyReviewLastWeekLabel?: string;
    diveDeep?: string;
    backToQuickRead?: string;
    questionsThisWeek?: string;
    reflectionsThisWeek?: string;
    gratitudeThisWeek?: string;
    decisionsThisWeek?: string;
    nextFaithfulStep?: string;
    askAboutThis?: string;
    saveToRuleOfLife?: string;
    carryingToday?: string;
    currentCounsel?: string;
    modeShapesCounsel?: string;
    trackThisDecision?: string;
    saveAsReflection?: string;
    createCounselSummary?: string;
    goDeeper?: string;
    waitThreeDays?: string;
    shareAnswerPrompt?: string;
    sharePrivacyNote?: string;
    shareAletheia?: string;
    feedbackQuestion?: string;
    feedbackHelpful?: string;
    feedbackMildlyHelpful?: string;
    feedbackTooVague?: string;
    feedbackTooPreachy?: string;
    feedbackNotRelevant?: string;
    badgesFormation?: string;
    firstReflectionSaved?: string;
    firstDecisionTracked?: string;
    answerReadyGuestTitle?: string;
    answerReadyGuestBody?: string;
    soughtCounsel?: string;
    waitingModeUsed?: string;
    ruleOfLifeCreated?: string;
    notificationsEnabled?: string;
    sevenDaysPractice?: string;
    formationNote?: string;
    milestoneShareTitle?: string;
    milestoneShareBody?: string;
    welcomeCounsel?: string;
    trustScriptureBody?: string;
    trustBoundaryBody?: string;
    trustMemoryBody?: string;
    trustConnectedDataBody?: string;
    accountNextEyebrow?: string;
    accountNextReviewSyncFormation?: string;
    accountNextSignInPortable?: string;
    accountNextActiveBody?: string;
    accountNextSyncBody?: string;
    accountNextGuestBody?: string;
    accountManageSummary?: string;
    accountSignedInAs?: string;
    accountSignInOrGuest?: string;
    accountSyncActive?: string;
    accountNotificationsNotEnabled?: string;
    accountGuestSummary?: string;
    accountPreferencesEyebrow?: string;
    accountPreferencesSummary?: string;
    counselGuestSignInTitle?: string;
    counselGuestSignInBody?: string;
    accountContextActive?: string;
    accountContextPaused?: string;
    accountArea?: string;
    accountAreas?: string;
    accountAdded?: string;
    accountManualContextSummary?: string;
    accountDailyWisdomEnabled?: string;
    accountNotificationsSummaryEnabled?: string;
    accountNotificationsSummaryDisabled?: string;
    accountInstallTitle?: string;
    accountInstallSummary?: string;
    accountInstallEyebrow?: string;
    accountInviteTitle?: string;
    accountInviteSummary?: string;
    accountInviteEyebrow?: string;
    accountHistoryConversations?: string;
    accountHistoryDecisions?: string;
    accountHistoryReflections?: string;
    accountHistorySummary?: string;
    accountStatConversations?: string;
    accountStatDecisions?: string;
    accountStatJournalEntries?: string;
    accountHistoryEmptyBody?: string;
    accountTrustPostureTitle?: string;
    accountTrustPostureSummary?: string;
    accountBoundariesTitle?: string;
    accountBoundariesSummary?: string;
    accountBoundariesBody?: string;
    accountFormationPrefix?: string;
    accountQuietMilestoneSingular?: string;
    accountQuietMilestonePlural?: string;
    accountFormationSummary?: string;
  }
>> = {
  en: enTranslations,
  es: {
    nav: { companion: "Inicio", decisions: "Decisiones", reflect: "Reflexión", library: "Biblioteca", account: "Cuenta" },
    decideShort: "Decidir",
    guardrails: "Límites",
    guardrailItems: ["Nunca predice resultados financieros.", "Nunca inventa referencias bíblicas.", "Anima a buscar apoyo humano ante lenguaje de autolesión, adicción o crisis."],
    wisdomMode: "Modo de sabiduría",
    currentLens: "Enfoque actual",
    offline: "Sin conexión",
    languageSelect: "Cambiar idioma",
    bibleSelect: "Cambiar traducción bíblica",
    account: "Cuenta",
    askTitle: "Pregunta a Aletheia",
    askIntro: "Empieza con una pregunta honesta. Aletheia ayuda a bajar la prisa y discernir con claridad.",
    yourQuestion: "Tu pregunta",
    askButton: "Preguntar",
    startHere: "Empieza aquí",
    ready: "Listo",
    whatModeFor: "Para qué sirve este modo",
    deepChecks: "Revisiones profundas",
    blindSpots: "Puntos ciegos",
    maturitySignals: "Señales de madurez",
    modeGuidance: "Guía del modo",
    change: "Cambiar",
    showDetails: "Mostrar detalles",
    hideDetails: "Ocultar detalles",
    modeGuidancePreview: "Mantén esta vista enfocada. Expande cuando quieras revisar señales profundas, puntos ciegos y madurez.",
    trustLayer: "Capa de confianza",
    preferencesTitle: "Idioma y región",
    language: "Idioma",
    region: "Región",
    bible: "Biblia",
    voiceControls: "Controles de voz",
    available: "Disponible",
    englishFallback: "Recurso en inglés",
    todaysCompanion: "Compañero de hoy",
    todayPrefix: "Hoy",
    wisdomPrinciple: "Principio de sabiduría",
    tinyPractice: "Práctica breve",
    reflectionQuestion: "Pregunta",
    whatINotice: "Lo que noto",
    context: "Contexto",
    application: "Aplicación",
    carryThisToday: "Lleva esto hoy",
    todayScriptureLabel: "Escritura",
    todayQuestionLabel: "Pregunta de hoy",
    todayActionsLabel: "Acciones de hoy",
    weeklyReviewHeading: "Tu revisión semanal",
    weeklyReviewLastWeekLabel: "La semana pasada",
    weeklyWisdomReview: "Revisión semanal de sabiduría",
    weeklyReviewTitle: "Una mirada tranquila a tu semana",
    weeklyReviewBody: "Sin rachas ni presión. Solo observa cómo {pattern} ha ido dando forma a tu discernimiento.",
    carryWithMe: "Llevar conmigo",
    askAboutThis: "Preguntar sobre esto",
    saveToRuleOfLife: "Guardar como regla de vida",
    carryingToday: "Llevando hoy",
    accountNextEyebrow: "Siguiente en Cuenta",
    accountNextReviewSyncFormation: "Revisar sincronización y formación",
    accountNextSignInPortable: "Inicia sesión para hacer Aletheia portátil",
    accountNextActiveBody: "Tu cuenta está activa. Revisa preferencias, historial y formación cuando lo necesites.",
    accountNextSyncBody: "La sincronización está activa. Activa una notificación diaria tranquila si este dispositivo debe recibirla.",
    accountNextGuestBody: "Usa Google o correo para sincronizar decisiones, reflexiones, preferencias, consejería y notificaciones entre dispositivos.",
    accountManageSummary: "Gestiona inicio de sesión, sincronización, idioma, notificaciones, historial y formación sin saturar al acompañante de sabiduría.",
    accountSignedInAs: "Sesión iniciada como",
    accountSignInOrGuest: "Inicia sesión o continúa como invitado",
    accountSyncActive: "Sincronización activa.",
    accountNotificationsNotEnabled: "Notificaciones aún no activadas.",
    accountGuestSummary: "El inicio de sesión con Google y correo mantiene portátil tu historial, preferencias, decisiones y notificaciones.",
    accountPreferencesEyebrow: "Preferencias",
    accountPreferencesSummary: "Idioma, traducción bíblica, apariencia, región y voz se quedan aquí para que el Acompañante se mantenga sereno.",
    accountContextActive: "Contexto activo",
    accountContextPaused: "Contexto en pausa",
    accountArea: "área",
    accountAreas: "áreas",
    accountAdded: "agregadas",
    accountManualContextSummary: "El contexto manual es opcional y privado. Agrega solo lo que deba moldear el consejo de Aletheia.",
    accountDailyWisdomEnabled: "Sabiduría diaria activada",
    accountNotificationsSummaryEnabled: "Aletheia usará tu preferencia de horario local guardada.",
    accountNotificationsSummaryDisabled: "Activa un aviso diario tranquilo cuando este dispositivo esté listo.",
    accountInstallTitle: "Agrega Aletheia a tu pantalla de inicio",
    accountInstallSummary: "Las instrucciones de instalación quedan ocultas hasta que alguien necesite la configuración tipo app.",
    accountInstallEyebrow: "Instalar Aletheia",
    accountInviteTitle: "Invita a alguien en privado",
    accountInviteSummary: "Comparte solo el enlace de Aletheia; nunca preguntas privadas, diarios o consejos por defecto.",
    accountInviteEyebrow: "Invitar a alguien",
    accountHistoryConversations: "conversaciones",
    accountHistoryDecisions: "decisiones",
    accountHistoryReflections: "reflexiones",
    accountHistorySummary: "El historial se mantiene plegado hasta que quieras revisar lo guardado.",
    accountStatConversations: "Conversaciones",
    accountStatDecisions: "Decisiones",
    accountStatJournalEntries: "Entradas de diario",
    accountHistoryEmptyBody: "Empieza con una pregunta honesta o una decisión bajo presión. Aletheia mantendrá el registro sobrio y útil.",
    accountTrustPostureTitle: "Postura de confianza y privacidad",
    accountTrustPostureSummary: "Límites, fuentes bíblicas, datos guardados y postura de compartición están disponibles sin saturar la página.",
    accountBoundariesTitle: "Límites de Aletheia",
    accountBoundariesSummary: "Los límites de seguridad de la app se mantienen visibles cuando hacen falta, sin estorbar constantemente.",
    accountBoundariesBody: "Estas restricciones te protegen de consejos dañinos de IA y mantienen a Aletheia fiel a su propósito.",
    accountFormationPrefix: "Formación",
    accountQuietMilestoneSingular: "hito sereno",
    accountQuietMilestonePlural: "hitos serenos",
    accountFormationSummary: "La formación es un registro sereno de práctica, no un marcador.",
  },
  fr: {
    nav: { companion: "Accueil", decisions: "Décisions", reflect: "Réflexion", library: "Bibliothèque", account: "Compte" },
    decideShort: "Décider",
    guardrails: "Garde-fous",
    guardrailItems: ["Ne prédit jamais les résultats financiers.", "N’invente jamais de références bibliques.", "Encourage un soutien humain en cas de propos d’automutilation, d’addiction ou de crise."],
    wisdomMode: "Mode sagesse",
    currentLens: "Angle actuel",
    offline: "Hors ligne",
    languageSelect: "Changer de langue",
    bibleSelect: "Changer de traduction biblique",
    account: "Compte",
    askTitle: "Demander à Aletheia",
    askIntro: "Commence par une question honnête. Aletheia ralentit le moment et aide à discerner clairement.",
    yourQuestion: "Ta question",
    askButton: "Demander",
    startHere: "Commencer ici",
    ready: "Prêt",
    whatModeFor: "À quoi sert ce mode",
    deepChecks: "Vérifications profondes",
    blindSpots: "Angles morts",
    maturitySignals: "Signes de maturité",
    modeGuidance: "Repères du mode",
    change: "Changer",
    showDetails: "Afficher les détails",
    hideDetails: "Masquer les détails",
    modeGuidancePreview: "Garde cette vue concentrée. Déploie-la pour voir les vérifications profondes, angles morts et signes de maturité.",
    trustLayer: "Couche de confiance",
    preferencesTitle: "Langue et région",
    language: "Langue",
    region: "Région",
    bible: "Bible",
    voiceControls: "Commandes vocales",
    available: "Disponible",
    englishFallback: "Repli anglais",
    todaysCompanion: "Compagnon du jour",
    todayPrefix: "Aujourd'hui",
    wisdomPrinciple: "Principe de sagesse",
    tinyPractice: "Petite pratique",
    reflectionQuestion: "Question",
    whatINotice: "Ce que je remarque",
    context: "Contexte",
    application: "Application",
    carryThisToday: "À porter aujourd'hui",
    todayScriptureLabel: "Écriture",
    todayQuestionLabel: "Question du jour",
    todayActionsLabel: "Actions du jour",
    weeklyReviewHeading: "Votre revue hebdomadaire",
    weeklyReviewLastWeekLabel: "La semaine dernière",
    weeklyWisdomReview: "Revue hebdomadaire de sagesse",
    weeklyReviewTitle: "Un regard calme sur votre semaine",
    weeklyReviewBody: "Sans série ni pression. Observez simplement comment {pattern} façonne votre discernement.",
    carryWithMe: "Porter avec moi",
    askAboutThis: "Questionner cela",
    saveToRuleOfLife: "Ajouter à ma règle de vie",
    carryingToday: "Porté aujourd'hui",
    accountNextEyebrow: "À venir dans Compte",
    accountNextReviewSyncFormation: "Vérifier la synchronisation et la formation",
    accountNextSignInPortable: "Connectez-vous pour rendre Aletheia portable",
    accountNextActiveBody: "Votre compte est actif. Consultez préférences, historique et jalons de formation quand nécessaire.",
    accountNextSyncBody: "La synchronisation est active. Activez une invite quotidienne discrète si cet appareil doit la recevoir.",
    accountNextGuestBody: "Utilisez Google ou l'e-mail pour synchroniser décisions, réflexions, préférences, conseil et notifications entre appareils.",
    accountManageSummary: "Gérez connexion, synchronisation, langue, notifications, historique et jalons de formation sans encombrer le compagnon de sagesse.",
    accountSignedInAs: "Connecté en tant que",
    accountSignInOrGuest: "Se connecter ou continuer en invité",
    accountSyncActive: "Synchronisation active.",
    accountNotificationsNotEnabled: "Notifications pas encore activées.",
    accountGuestSummary: "La connexion Google et e-mail garde votre historique, vos préférences, vos décisions et notifications portables.",
    accountPreferencesEyebrow: "Préférences",
    accountPreferencesSummary: "Langue, traduction biblique, apparence, région et voix restent ici pour garder le Compagnon apaisé.",
    accountContextActive: "Contexte actif",
    accountContextPaused: "Contexte en pause",
    accountArea: "zone",
    accountAreas: "zones",
    accountAdded: "ajoutées",
    accountManualContextSummary: "Le contexte manuel est optionnel et privé. Ajoutez seulement ce qui doit façonner le conseil d'Aletheia.",
    accountDailyWisdomEnabled: "Sagesse quotidienne activée",
    accountNotificationsSummaryEnabled: "Aletheia utilisera votre préférence horaire locale enregistrée.",
    accountNotificationsSummaryDisabled: "Activez une invite quotidienne discrète quand cet appareil est prêt.",
    accountInstallTitle: "Ajouter Aletheia à l'écran d'accueil",
    accountInstallSummary: "Les instructions d'installation restent discrètes jusqu'au moment où elles sont utiles.",
    accountInstallEyebrow: "Installer Aletheia",
    accountInviteTitle: "Inviter quelqu'un en privé",
    accountInviteSummary: "Partagez uniquement le lien Aletheia, jamais les questions privées, journaux ou conseils par défaut.",
    accountInviteEyebrow: "Inviter quelqu'un",
    accountHistoryConversations: "conversations",
    accountHistoryDecisions: "décisions",
    accountHistoryReflections: "réflexions",
    accountHistorySummary: "L'historique reste replié jusqu'au moment où vous voulez revoir ce qui est enregistré.",
    accountStatConversations: "Conversations",
    accountStatDecisions: "Décisions",
    accountStatJournalEntries: "Entrées de journal",
    accountHistoryEmptyBody: "Commencez par une question honnête ou une décision sous pression. Aletheia gardera l'historique sobre et utile.",
    accountTrustPostureTitle: "Posture confiance et confidentialité",
    accountTrustPostureSummary: "Limites, sources scripturaires, données enregistrées et posture de partage restent accessibles sans surcharger la page.",
    accountBoundariesTitle: "Garde-fous d'Aletheia",
    accountBoundariesSummary: "Les limites de sécurité de l'app restent visibles au besoin, sans gêner en permanence.",
    accountBoundariesBody: "Ces limites vous protègent des conseils IA nuisibles et gardent Aletheia fidèle à sa mission.",
    accountFormationPrefix: "Formation",
    accountQuietMilestoneSingular: "jalon discret",
    accountQuietMilestonePlural: "jalons discrets",
    accountFormationSummary: "La formation est un suivi serein de la pratique, pas un tableau de score.",
  },
  pt: {
    nav: { companion: "Início", decisions: "Decisões", reflect: "Refletir", library: "Biblioteca", account: "Conta" },
    decideShort: "Decidir",
    guardrails: "Limites",
    guardrailItems: ["Nunca prevê resultados financeiros.", "Nunca inventa referências bíblicas.", "Incentiva apoio humano diante de fala sobre autoagressão, vício ou crise."],
    wisdomMode: "Modo de sabedoria",
    currentLens: "Lente atual",
    offline: "Offline",
    languageSelect: "Mudar idioma",
    bibleSelect: "Mudar tradução bíblica",
    account: "Conta",
    askTitle: "Pergunte à Aletheia",
    askIntro: "Comece com uma pergunta honesta. Aletheia ajuda a desacelerar e discernir com clareza.",
    yourQuestion: "Sua pergunta",
    askButton: "Perguntar",
    startHere: "Comece aqui",
    ready: "Pronto",
    whatModeFor: "Para que serve este modo",
    deepChecks: "Verificações profundas",
    blindSpots: "Pontos cegos",
    maturitySignals: "Sinais de maturidade",
    modeGuidance: "Guia do modo",
    change: "Alterar",
    showDetails: "Mostrar detalhes",
    hideDetails: "Ocultar detalhes",
    modeGuidancePreview: "Mantenha esta visão focada. Expanda quando quiser ver verificações profundas, pontos cegos e sinais de maturidade.",
    trustLayer: "Camada de confiança",
    preferencesTitle: "Idioma e região",
    language: "Idioma",
    region: "Região",
    bible: "Bíblia",
    voiceControls: "Controles de voz",
    available: "Disponível",
    englishFallback: "Recurso em inglês",
    greetingMorning: "Bom dia",
    greetingAfternoon: "Boa tarde",
    greetingEvening: "Boa noite",
    greetingFallback: "Bem-vindo de volta",
    greetingIntent: "Vamos escolher um próximo passo sábio hoje.",
    personalizedPriority: "Prioridade personalizada",
    whatNext: "O que devo fazer a seguir?",
    whatNextBody: "Aletheia escolhe primeiro uma ação sábia. O campo de pergunta e os controles de modo ficam logo abaixo quando você quiser começar algo novo.",
    continueDecision: "Continuar com esta decisão",
    askOneQuestion: "Fazer uma pergunta",
    askOneQuestionBody: "Comece com a pressão ou decisão que você está carregando agora.",
    askNewQuestion: "Fazer uma nova pergunta",
    askNewQuestionBody: "O campo Companion e os modos de sabedoria estão logo abaixo.",
    reflectToday: "Refletir sobre hoje",
    reviewPattern: "Revisar um padrão",
    enableNotifications: "Ativar notificações",
    enableSync: "Ativar sincronização",
    notificationPromptBody: "Receba um lembrete diário de sabedoria em silêncio.",
    syncDevicesBody: "Mantenha decisões e reflexões em todos os dispositivos.",
    startDecision: "Iniciar uma decisão",
    startDecisionBody: "Rastreie uma escolha importante ao longo do tempo.",
    todaysCompanion: "Companheiro de hoje",
    todayPrefix: "Hoje",
    wisdomPrinciple: "Princípio de sabedoria",
    tinyPractice: "Pequena prática",
    reflectionQuestion: "Pergunta",
    whatINotice: "O que percebo",
    context: "Contexto",
    application: "Aplicação",
    carryThisToday: "Leve isto hoje",
    todayScriptureLabel: "Escritura",
    todayQuestionLabel: "Pergunta de hoje",
    todayActionsLabel: "Ações de hoje",
    weeklyReviewHeading: "Sua revisão semanal",
    weeklyReviewLastWeekLabel: "Na semana passada",
    weeklyWisdomReview: "Revisão semanal de sabedoria",
    weeklyReviewTitle: "Um olhar tranquilo sobre a sua semana",
    weeklyReviewBody: "Sem sequências nem pressão. Apenas perceba como {pattern} tem moldado o seu discernimento.",
    carryWithMe: "Levar comigo",
    askAboutThis: "Perguntar sobre isto",
    saveToRuleOfLife: "Salvar como regra de vida",
    carryingToday: "Levando hoje",
    currentCounsel: "Conselho atual",
    modeShapesCounsel: "está moldando este conselho em torno de",
    trackThisDecision: "Rastrear esta decisão",
    saveAsReflection: "Salvar como reflexão",
    createCounselSummary: "Criar resumo para conselheiro",
    goDeeper: "Aprofundar mais",
    waitThreeDays: "Esperar 3 dias",
    shareAnswerPrompt: "Compartilhe Aletheia com alguém que possa se beneficiar deste tipo de conselho.",
    sharePrivacyNote: "Isso compartilha apenas o link do app, não sua pergunta nem a resposta privada de Aletheia.",
    shareAletheia: "Compartilhar Aletheia",
    feedbackQuestion: "Este conselho foi útil?",
    feedbackHelpful: "Útil",
    feedbackMildlyHelpful: "Um pouco útil",
    feedbackTooVague: "Muito vago",
    feedbackTooPreachy: "Muito pregador",
    feedbackNotRelevant: "Não relevante",
    badgesFormation: "Distintivos / Formação",
    firstReflectionSaved: "Primeira reflexão salva",
    firstDecisionTracked: "Primeira decisão rastreada",
    soughtCounsel: "Buscou conselho",
    waitingModeUsed: "Modo de espera usado",
    ruleOfLifeCreated: "Regra de vida criada",
    notificationsEnabled: "Notificações ativadas",
    sevenDaysPractice: "7 dias de prática de sabedoria",
    formationNote: "Estes são sinais silenciosos de formação, não pontos a perseguir. O primeiro marco geralmente começa salvando uma reflexão.",
    milestoneShareTitle: "Conhece alguém tomando uma decisão importante?",
    milestoneShareBody: "Você pode convidá-los para Aletheia sem compartilhar nada privado de sua conta.",
    welcomeCounsel:
      "Traga uma decisão real, pressão ou pergunta sobre dinheiro. Responderei da biblioteca de sabedoria curada, com clareza emocional e sem promessas financeiras.",
    trustScriptureBody:
      "As referências bíblicas vêm da biblioteca de sabedoria curada de Aletheia. Se um versículo aparecer, você pode tocá-lo para ver o contexto e por que importa.",
    trustBoundaryBody:
      "Aletheia não prometerá resultados, não preverá mercados, não afirmará certeza divina, nem substituirá o conselho qualificado financeiro, legal, fiscal, médico ou pastoral.",
    trustMemoryBody:
      "A memória conectada ajuda na continuidade entre decisões, reflexões, conselho e regras de vida. Deve tornar a orientação mais pessoal sem expor detalhes privados desnecessariamente.",
    trustConnectedDataBody:
      "Futuras integrações de saúde, finanças ou dispositivos devem ser permissão por permissão, desativadas por padrão e limitadas aos dados exatos que o usuário escolher conectar.",
    accountNextEyebrow: "A seguir na Conta",
    accountNextReviewSyncFormation: "Rever sincronização e formação",
    accountNextSignInPortable: "Entre para levar Aletheia com você",
    accountNextActiveBody: "Sua conta está ativa. Revise preferências, histórico e marcos de formação quando precisar.",
    accountNextSyncBody: "A sincronização está ativa. Ative um lembrete diário discreto de sabedoria se este dispositivo deve recebê-lo.",
    accountNextGuestBody: "Use Google ou email para sincronizar decisões, reflexões, preferências, conselhos e notificações entre dispositivos.",
    accountManageSummary: "Gerencie login, sincronização, idioma, notificações, histórico e marcos de formação sem lotar o companheiro de sabedoria.",
    accountSignedInAs: "Conectado como",
    accountSignInOrGuest: "Entrar ou continuar como convidado",
    accountSyncActive: "Sincronização ativa.",
    accountNotificationsNotEnabled: "Notificações ainda não ativadas.",
    accountGuestSummary: "O login por Google e email mantém histórico, preferências, decisões e notificações portáteis.",
    accountPreferencesEyebrow: "Preferências",
    accountPreferencesSummary: "Idioma, tradução bíblica, aparência, região e voz ficam aqui para que o Companheiro permaneça sereno.",
    accountContextActive: "Contexto ativo",
    accountContextPaused: "Contexto pausado",
    accountArea: "área",
    accountAreas: "áreas",
    accountAdded: "adicionadas",
    accountManualContextSummary: "O contexto manual é opcional e privado. Adicione apenas o que deve moldar o conselho da Aletheia.",
    accountDailyWisdomEnabled: "Sabedoria diária ativada",
    accountNotificationsSummaryEnabled: "Aletheia usará sua preferência local de horário já salva.",
    accountNotificationsSummaryDisabled: "Ative um lembrete diário discreto quando este dispositivo estiver pronto.",
    accountInstallTitle: "Adicione Aletheia à tela inicial",
    accountInstallSummary: "As instruções de instalação ficam discretas até alguém precisar da experiência de app.",
    accountInstallEyebrow: "Instalar Aletheia",
    accountInviteTitle: "Convide alguém em privado",
    accountInviteSummary: "Compartilhe apenas o link da Aletheia, nunca perguntas privadas, diários ou conselhos por padrão.",
    accountInviteEyebrow: "Convidar alguém",
    accountHistoryConversations: "conversas",
    accountHistoryDecisions: "decisões",
    accountHistoryReflections: "reflexões",
    accountHistorySummary: "O histórico permanece recolhido até você querer revisar o que foi salvo.",
    accountStatConversations: "Conversas",
    accountStatDecisions: "Decisões",
    accountStatJournalEntries: "Entradas de diário",
    accountHistoryEmptyBody: "Comece com uma pergunta honesta ou uma decisão sob pressão. Aletheia manterá o registro sóbrio e útil.",
    accountTrustPostureTitle: "Postura de confiança e privacidade",
    accountTrustPostureSummary: "Limites, origem das escrituras, dados salvos e postura de compartilhamento ficam disponíveis sem sobrecarregar a página.",
    accountBoundariesTitle: "Limites de proteção da Aletheia",
    accountBoundariesSummary: "Os limites de segurança do app ficam visíveis quando necessários, sem atrapalhar o tempo todo.",
    accountBoundariesBody: "Essas restrições protegem você de conselhos nocivos de IA e mantêm Aletheia fiel ao seu propósito.",
    accountFormationPrefix: "Formação",
    accountQuietMilestoneSingular: "marco silencioso",
    accountQuietMilestonePlural: "marcos silenciosos",
    accountFormationSummary: "A formação é um registro calmo de prática, não um placar.",
  },
  de: {
    nav: { companion: "Start", decisions: "Entscheidungen", reflect: "Reflektieren", library: "Bibliothek", account: "Konto" },
    decideShort: "Entscheiden",
    guardrails: "Leitplanken",
    guardrailItems: ["Sagt keine finanziellen Ergebnisse voraus.", "Erfindet keine Bibelstellen.", "Ermutigt bei Selbstverletzung, Sucht oder Krisensprache zu menschlicher Hilfe."],
    wisdomMode: "Weisheitsmodus",
    currentLens: "Aktuelle Perspektive",
    offline: "Offline",
    languageSelect: "Sprache ändern",
    bibleSelect: "Bibelübersetzung ändern",
    account: "Konto",
    askTitle: "Aletheia fragen",
    askIntro: "Beginne mit einer ehrlichen Frage. Aletheia verlangsamt den Moment und hilft dir klarer zu prüfen.",
    yourQuestion: "Deine Frage",
    askButton: "Fragen",
    startHere: "Hier beginnen",
    ready: "Bereit",
    whatModeFor: "Wofür dieser Modus ist",
    deepChecks: "Tiefe Prüfungen",
    blindSpots: "Blinde Flecken",
    maturitySignals: "Reifezeichen",
    modeGuidance: "Modus-Hinweise",
    change: "Ändern",
    showDetails: "Details zeigen",
    hideDetails: "Details ausblenden",
    modeGuidancePreview: "Halte diese Ansicht fokussiert. Erweitere sie, wenn du tiefere Prüfungen, blinde Flecken und Reifezeichen sehen möchtest.",
    trustLayer: "Vertrauensebene",
    preferencesTitle: "Sprache und Region",
    language: "Sprache",
    region: "Region",
    bible: "Bibel",
    voiceControls: "Sprachsteuerung",
    available: "Verfügbar",
    englishFallback: "Englischer Rückgriff",
    personalizedPriority: "Persönliche Priorität",
    whatNext: "Was sollte ich als Nächstes tun?",
    whatNextBody: "Aletheia zeigt zuerst einen weisen nächsten Schritt. Das Fragefeld und die Modi bleiben direkt darunter erreichbar.",
    continueDecision: "Diese Entscheidung fortsetzen",
    askOneQuestion: "Eine Frage stellen",
    askOneQuestionBody: "Beginne mit dem Druck oder der Entscheidung, die du gerade trägst.",
    askNewQuestion: "Neue Frage stellen",
    askNewQuestionBody: "Das Fragefeld und die Weisheitsmodi sind direkt darunter.",
    reflectToday: "Heute reflektieren",
    reviewPattern: "Muster prüfen",
    enableNotifications: "Benachrichtigungen aktivieren",
    enableSync: "Synchronisierung aktivieren",
    startDecision: "Entscheidung beginnen",
    startDecisionBody: "Verfolge eine wichtige Entscheidung über Zeit.",
    tinyPractice: "Kleine Übung",
    todaysCompanion: "Begleiter für heute",
    todayPrefix: "Heute",
    wisdomPrinciple: "Weisheitsprinzip",
    reflectionQuestion: "Frage",
    whatINotice: "Was ich bemerke",
    context: "Kontext",
    application: "Anwendung",
    carryThisToday: "Heute mitnehmen",
    todayScriptureLabel: "Bibelstelle",
    todayQuestionLabel: "Frage von heute",
    todayActionsLabel: "Aktionen für heute",
    weeklyReviewHeading: "Dein Wochenrückblick",
    weeklyReviewLastWeekLabel: "Letzte Woche",
    weeklyWisdomReview: "Wöchentliche Weisheitsrückschau",
    weeklyReviewTitle: "Ein ruhiger Blick auf deine Woche",
    weeklyReviewBody: "Ohne Serien oder Druck. Achte einfach darauf, wie {pattern} dein Urteilsvermögen geprägt hat.",
    carryWithMe: "Mitnehmen",
    askAboutThis: "Dazu fragen",
    saveToRuleOfLife: "Als Lebensregel speichern",
    carryingToday: "Heute trägst du",
    currentCounsel: "Aktueller Rat",
    modeShapesCounsel: "Modus prägt diesen Rat mit der Perspektive",
    trackThisDecision: "Diese Entscheidung verfolgen",
    saveAsReflection: "Als Reflexion speichern",
    createCounselSummary: "Zusammenfassung für Ratgeber erstellen",
    goDeeper: "Tiefer gehen",
    waitThreeDays: "3 Tage warten",
    shareAnswerPrompt: "Teile Aletheia mit jemandem, dem diese Art von Rat helfen könnte.",
    sharePrivacyNote: "Dabei wird nur der App-Link geteilt, nicht deine Frage oder private Antwort.",
    shareAletheia: "Aletheia teilen",
    feedbackQuestion: "War dieser Rat hilfreich?",
    feedbackHelpful: "Hilfreich",
    feedbackMildlyHelpful: "Etwas hilfreich",
    feedbackTooVague: "Zu vage",
    feedbackTooPreachy: "Zu predigend",
    feedbackNotRelevant: "Nicht passend",
    badgesFormation: "Meilensteine / Formung",
    firstReflectionSaved: "Erste Reflexion gespeichert",
    firstDecisionTracked: "Erste Entscheidung verfolgt",
    soughtCounsel: "Rat gesucht",
    waitingModeUsed: "Wartemodus genutzt",
    ruleOfLifeCreated: "Lebensregel erstellt",
    notificationsEnabled: "Benachrichtigungen aktiviert",
    sevenDaysPractice: "7 Tage Weisheitspraxis",
    formationNote: "Das sind ruhige Zeichen von Formung, keine Punktejagd. Der erste Meilenstein beginnt meist mit einer gespeicherten Reflexion.",
    milestoneShareTitle: "Kennst du jemanden vor einer wichtigen Entscheidung?",
    milestoneShareBody: "Du kannst Aletheia empfehlen, ohne private Inhalte aus deinem Konto zu teilen.",
    accountNextEyebrow: "Als Nächstes im Konto",
    accountNextReviewSyncFormation: "Synchronisierung und Formung prüfen",
    accountNextSignInPortable: "Melde dich an, um Aletheia mobil mitzunehmen",
    accountNextActiveBody: "Dein Konto ist aktiv. Prüfe bei Bedarf Einstellungen, Verlauf und Formungs-Meilensteine.",
    accountNextSyncBody: "Synchronisierung ist aktiv. Aktiviere einen ruhigen täglichen Impuls, wenn dieses Gerät ihn erhalten soll.",
    accountNextGuestBody: "Nutze Google oder E-Mail, um Entscheidungen, Reflexionen, Einstellungen, Beratung und Benachrichtigungen geräteübergreifend zu synchronisieren.",
    accountManageSummary: "Verwalte Anmeldung, Synchronisierung, Sprache, Benachrichtigungen, Verlauf und Formungs-Meilensteine, ohne den Weisheitsbegleiter zu überladen.",
    accountSignedInAs: "Angemeldet als",
    accountSignInOrGuest: "Anmelden oder als Gast fortfahren",
    accountSyncActive: "Synchronisierung aktiv.",
    accountNotificationsNotEnabled: "Benachrichtigungen noch nicht aktiviert.",
    accountGuestSummary: "Google- und E-Mail-Anmeldung halten Verlauf, Einstellungen, Entscheidungen und Benachrichtigungen portabel.",
    accountPreferencesEyebrow: "Einstellungen",
    accountPreferencesSummary: "Sprache, Bibelübersetzung, Erscheinungsbild, Region und Stimme bleiben hier, damit der Begleiter ruhig bleibt.",
    accountContextActive: "Kontext aktiv",
    accountContextPaused: "Kontext pausiert",
    accountArea: "Bereich",
    accountAreas: "Bereiche",
    accountAdded: "hinzugefügt",
    accountManualContextSummary: "Manueller Kontext ist optional und privat. Füge nur hinzu, was Aletheias Beratung prägen soll.",
    accountDailyWisdomEnabled: "Tägliche Weisheit aktiviert",
    accountNotificationsSummaryEnabled: "Aletheia verwendet deine gespeicherte lokale Zeitpräferenz.",
    accountNotificationsSummaryDisabled: "Aktiviere einen ruhigen täglichen Impuls, wenn dieses Gerät bereit ist.",
    accountInstallTitle: "Aletheia zum Startbildschirm hinzufügen",
    accountInstallSummary: "Installationshinweise bleiben kompakt, bis jemand die app-ähnliche Einrichtung braucht.",
    accountInstallEyebrow: "Aletheia installieren",
    accountInviteTitle: "Jemanden privat einladen",
    accountInviteSummary: "Teile nur den Aletheia-Link, niemals standardmäßig private Fragen, Journale oder Beratung.",
    accountInviteEyebrow: "Jemanden einladen",
    accountHistoryConversations: "Gespräche",
    accountHistoryDecisions: "Entscheidungen",
    accountHistoryReflections: "Reflexionen",
    accountHistorySummary: "Der Verlauf bleibt eingeklappt, bis du Gespeichertes ansehen willst.",
    accountStatConversations: "Gespräche",
    accountStatDecisions: "Entscheidungen",
    accountStatJournalEntries: "Journaleinträge",
    accountHistoryEmptyBody: "Starte mit einer ehrlichen Frage oder einer Entscheidung unter Druck. Aletheia hält den Verlauf ruhig und nützlich.",
    accountTrustPostureTitle: "Vertrauens- und Datenschutzhaltung",
    accountTrustPostureSummary: "Grenzen, Schriftquellen, gespeicherte Daten und Freigabehaltung sind verfügbar, ohne die Seite zu überladen.",
    accountBoundariesTitle: "Aletheias Leitplanken",
    accountBoundariesSummary: "Die Sicherheitsgrenzen der App bleiben sichtbar, wenn sie gebraucht werden, ohne ständig im Weg zu sein.",
    accountBoundariesBody: "Diese Grenzen schützen dich vor schädlichen KI-Ratschlägen und halten Aletheia seiner Aufgabe treu.",
    accountFormationPrefix: "Formung",
    accountQuietMilestoneSingular: "ruhiger Meilenstein",
    accountQuietMilestonePlural: "ruhige Meilensteine",
    accountFormationSummary: "Formung ist ein ruhiger Praxisverlauf, keine Punktetafel.",
  },
  yo: {
    nav: { companion: "Ilé", decisions: "Ìpinnu", reflect: "Ìrònú", library: "Ilé ìkàwé", account: "Àkọọlẹ" },
    decideShort: "Pinnu",
    guardrails: "Ààlà",
    guardrailItems: ["Kì í sọ abajade owó di àsọtẹ́lẹ̀.", "Kì í dá ìtọ́kasí Bíbélì sílẹ̀.", "Ó gba níyànjú láti wá ìmọ̀ràn fún ìpinnu ńlá."],
    wisdomMode: "Ipo ọgbọ́n",
    currentLens: "Ìwòye lọwọlọwọ",
    offline: "Ko si nẹ́tíwọ́ọ̀kì",
    languageSelect: "Yí èdè padà",
    bibleSelect: "Yí ìtumọ̀ Bíbélì padà",
    account: "Àkọọlẹ",
    askTitle: "Béèrè lọ́wọ́ Aletheia",
    askIntro: "Bẹrẹ pẹ̀lú ìbéèrè olóòtítọ́ kan. Aletheia máa ràn ọ́ lọ́wọ́ láti dákẹ́ kí o sì mọ̀ ìtọnisọna.",
    yourQuestion: "Ìbéèrè rẹ",
    askButton: "Béèrè",
    startHere: "Bẹrẹ níbí",
    ready: "Ṣetán",
    whatModeFor: "Ohun tí ipo yìí wúlò fún",
    deepChecks: "Àyẹ̀wò jinlẹ̀",
    blindSpots: "Àwọn ibi tí a lè má rí",
    maturitySignals: "Àmì ìdagbasoke",
    modeGuidance: "Ìtọ́nisọ́nà ipo",
    change: "Yí padà",
    showDetails: "Fi àlàyé hàn",
    hideDetails: "Pa àlàyé mọ́",
    modeGuidancePreview: "Jẹ́ kí ojú-ìwòye yìí dojú kọ ohun pàtàkì. Ṣí i síi nígbà tí o bá fẹ́ àyẹ̀wò jinlẹ̀, ibi tí a lè má rí, àti àmì ìdagbasoke.",
    trustLayer: "Ìpele ìgbẹ́kẹ̀lé",
    preferencesTitle: "Èdè àti agbègbè",
    language: "Èdè",
    region: "Agbègbè",
    bible: "Bíbélì",
    voiceControls: "Ìṣàkóso ohùn",
    available: "Wà",
    englishFallback: "Ìpadà sí Gẹ̀ẹ́sì",
    greetingMorning: "Ẹ káàrọ̀",
    greetingAfternoon: "Ẹ káàsán",
    greetingEvening: "Ẹ káalẹ́",
    greetingFallback: "Ẹ ku àbọ̀",
    greetingIntent: "Ẹ jẹ́ ká yan ìgbésẹ̀ ọgbọ́n tó tẹ̀lé lónìí.",
    personalizedPriority: "Ohun pàtàkì fún ọ",
    whatNext: "Kí ni mo yẹ kí n ṣe lẹ́yìn èyí?",
    whatNextBody: "Aletheia ń yan ìgbésẹ̀ ọgbọ́n kan kọ́kọ́. Apoti ìbéèrè àti àwọn ipo ọgbọ́n wà ní isalẹ nígbà tí o bá fẹ́ bẹ̀rẹ̀ ohun tuntun.",
    continueDecision: "Tẹ̀síwájú pẹ̀lú ìpinnu yìí",
    askOneQuestion: "Béèrè ìbéèrè kan",
    askOneQuestionBody: "Bẹrẹ pẹ̀lú ìpinnu tàbí ìrù tí o ń gbé báyìí.",
    askNewQuestion: "Béèrè ìbéèrè tuntun",
    askNewQuestionBody: "Apoti Companion àti àwọn ipo ọgbọ́n wà ní isalẹ.",
    reflectToday: "Ronú lónìí",
    reviewPattern: "Ṣàyẹ̀wò àwòṣe kan",
    enableNotifications: "Tan ìfitónilétí sí",
    enableSync: "Tan ìmúpọ̀ sí",
    notificationPromptBody: "Gba ìrántí ọgbọ́n ojoojúmọ́ kan ní ìdákẹ́jẹ.",
    syncDevicesBody: "Jẹ́ kí àwọn ìpinnu àti ìrònú rẹ wà lórí gbogbo ẹrọ rẹ.",
    startDecision: "Bẹrẹ ìpinnu kan",
    startDecisionBody: "Tọ́pa ìpinnu pàtàkì kan nípasẹ̀ àkókò.",
    tinyPractice: "Ìṣe kékeré",
    todaysCompanion: "Alábàákẹ́gbẹ́ oni",
    todayPrefix: "Lónìí",
    wisdomPrinciple: "Ìlànà ọgbọ́n",
    reflectionQuestion: "Ìbéèrè",
    whatINotice: "Ohun tí mo ń rí",
    context: "Àyíká",
    application: "Ìmúlò",
    carryThisToday: "Gbé èyí lọ lónìí",
    todayScriptureLabel: "Ìwé mímọ́",
    todayQuestionLabel: "Ìbéèrè lónìí",
    todayActionsLabel: "Àwọn ìṣe lónìí",
    weeklyReviewHeading: "Àfọ̀wọ̀sẹ̀ rẹ",
    weeklyReviewLastWeekLabel: "Ọ̀sẹ̀ tó kọjá",
    weeklyWisdomReview: "Àfọ̀wọ̀sẹ̀ ọgbọ́n",
    weeklyReviewTitle: "Ìwọ̀ pẹ̀lú ìdákẹ́jẹ sí ọ̀sẹ̀ rẹ",
    weeklyReviewBody: "Laisi ìtẹ̀síwájú tàbí titẹ. Ṣàkíyèsí bí {pattern} ṣe ń dá ìmúlò ọgbọ́n rẹ láàrin.",
    carryWithMe: "Gbé e pẹ̀lú mi",
    askAboutThis: "Béèrè nípa èyí",
    saveToRuleOfLife: "Fi sí Ofin ìgbé-ayé",
    carryingToday: "Ohun tí o ń gbé lónìí",
    currentCounsel: "Ìmọ̀ràn lọwọlọwọ",
    modeShapesCounsel: "ń wo ìmọ̀ràn yìí láti",
    trackThisDecision: "Tọ́pa ìpinnu yìí",
    saveAsReflection: "Fi pamọ́ gẹ́gẹ́ bí ìrònú",
    createCounselSummary: "Ṣẹ̀dá àkótán fún olùdámọ̀ràn",
    goDeeper: "Lọ jinlẹ̀ síi",
    waitThreeDays: "Dúró ọjọ́ mẹ́ta",
    shareAnswerPrompt: "Pin Aletheia pẹ̀lú ẹni tí irú ìmọ̀ràn yìí lè ràn lọ́wọ́.",
    sharePrivacyNote: "Èyí máa pin ọna asopọ app nìkan, kì í ṣe ìbéèrè rẹ tàbí ìdáhùn ikọ̀kọ̀.",
    shareAletheia: "Pin Aletheia",
    feedbackQuestion: "Ṣé ìmọ̀ràn yìí wúlò?",
    feedbackHelpful: "Ó wúlò",
    feedbackMildlyHelpful: "Ó wúlò díẹ̀",
    feedbackTooVague: "Ó ṣòro láti lóye",
    feedbackTooPreachy: "Ó dà bí ìwàásù jù",
    feedbackNotRelevant: "Kò bá a mu",
    badgesFormation: "Àwọn àmì ìdagbasoke",
    firstReflectionSaved: "Ìrònú àkọ́kọ́ ti fipamọ́",
    firstDecisionTracked: "Ìpinnu àkọ́kọ́ ti tọ́pa",
    soughtCounsel: "Wá ìmọ̀ràn",
    waitingModeUsed: "Ipo ìdúró ti lo",
    ruleOfLifeCreated: "Ofin ìgbé-ayé ti dá",
    notificationsEnabled: "Ìfitónilétí ti tan",
    sevenDaysPractice: "Ọjọ́ méje ti ìṣe ọgbọ́n",
    formationNote: "Ìwọ̀nyí jẹ́ àmì ìdagbasoke pẹ̀lẹ́, kì í ṣe àmì ìdíje. Ìgbésẹ̀ àkọ́kọ́ sábà máa ń bẹ̀rẹ̀ pẹ̀lú fífi ìrònú kan pamọ́.",
    milestoneShareTitle: "Ṣé o mọ ẹni tí ó ń ṣe ìpinnu pàtàkì?",
    milestoneShareBody: "O lè pè é sí Aletheia láì pin ohunkóhun ikọ̀kọ̀ láti àkọọlẹ rẹ.",
    welcomeCounsel:
      "Mú ìpinnu gidi, ìrù, tàbí ìbéèrè owó wá. Èmi yóò dáhùn láti inú ilé ìkàwé ọgbọ́n tí a ṣètò, pẹ̀lú ìmọ̀lára tó mọ́ àti láì ṣe ìlérí owó.",
    trustScriptureBody:
      "Àwọn ìtọ́kasí Bíbélì wá láti inú ilé ìkàwé ọgbọ́n Aletheia. Bí ẹsẹ kan bá hàn, o lè tẹ̀ ẹ́ láti rí àyíká rẹ àti ìdí tí ó fi ṣe pàtàkì.",
    trustBoundaryBody:
      "Aletheia kì í ṣe ìlérí abajade, kì í sọ ọjà di àsọtẹ́lẹ̀, kì í sọ ìdánilójú Ọlọ́run tí kò sí, kì í sì rọ́pò ìmọ̀ràn amọ̀ja nípa owó, òfin, owó-orí, ìlera, tàbí ìtọ́sọ́nà olùṣọ́.",
    trustMemoryBody:
      "Ìrántí fún ẹni tí ó wọlé ń ran ìpinnu, ìrònú, ìmọ̀ràn, àti òfin ìgbé-ayé lọwọ láti tẹ̀síwájú. Ó yẹ kí ìtọ́sọ́nà jẹ́ ti ara ẹni láì ṣí ìkọ̀kọ̀ sílẹ̀ láìnídí.",
    trustConnectedDataBody:
      "Ìsopọ̀ ọjọ́ iwájú sí ìlera, owó, tàbí ẹrọ gbọdọ̀ jẹ́ pẹ̀lú àṣẹ kọọkan, pa a sílẹ̀ ní ìbẹ̀rẹ̀, kí ó sì lo data gangan tí olumulo yan nìkan.",
    accountNextEyebrow: "Ohun tó tẹ̀lé nínú Àkọọ́lẹ̀",
    accountNextReviewSyncFormation: "Ṣàyẹ̀wò ìmúpọ̀ àti ìdàgbàsókè",
    accountNextSignInPortable: "Wọlé láti mú Aletheia bá ọ lọ",
    accountNextActiveBody: "Àkọọ́lẹ̀ rẹ ti ṣiṣẹ́. Ṣàyẹ̀wò àwọn ìfẹ́ràn, ìtàn àti àwọn àmì ìdàgbàsókè nígbà tí o bá nílò rẹ.",
    accountNextSyncBody: "Ìmúpọ̀ ti ṣiṣẹ́. Tan ìrántí ọgbọ́n ojoojúmọ́ pẹ̀lẹ́ sílẹ̀ bí ẹ̀rọ yìí yẹ kí ó máa gba a.",
    accountNextGuestBody: "Lo Google tàbí ímẹ̀ìlì láti mú àwọn ìpinnu, ìrònú, àwọn ìfẹ́ràn, ìmọ̀ràn àti ìfitónilétí pọ̀ láàárín àwọn ẹ̀rọ.",
    accountManageSummary: "Ṣàkóso ìwọlé, ìmúpọ̀, èdè, ìfitónilétí, ìtàn àti àwọn àmì ìdàgbàsókè láì kó ìdàrúdàpọ̀ bá alábàákẹ́gbẹ́ ọgbọ́n.",
    accountSignedInAs: "Ti wọlé gẹ́gẹ́ bí",
    accountSignInOrGuest: "Wọlé tàbí tẹ̀síwájú gẹ́gẹ́ bí àlejò",
    accountSyncActive: "Ìmúpọ̀ ti ṣiṣẹ́.",
    accountNotificationsNotEnabled: "Ìfitónilétí kò tíì ṣiṣẹ́.",
    accountGuestSummary: "Ìwọlé Google àti ímẹ̀ìlì ń jẹ́ kí ìtàn, àwọn ìfẹ́ràn, àwọn ìpinnu àti ìfitónilétí rẹ rọrùn láti mú lọ sí ibòmíì.",
    accountPreferencesEyebrow: "Àwọn ìfẹ́ràn",
    accountPreferencesSummary: "Èdè, ìtumọ̀ Bíbélì, ìrísí, agbègbè àti ohùn wà níbí kí Alábàákẹ́gbẹ́ lè dúró ní ìdákẹ́jẹ.",
    accountContextActive: "Àyíká ti ṣiṣẹ́",
    accountContextPaused: "Àyíká ti dúró",
    accountArea: "àgbègbè",
    accountAreas: "àwọn àgbègbè",
    accountAdded: "tí a fikún",
    accountManualContextSummary: "Àyíká ọwọ́ jẹ́ àṣàyàn àti ìkọ̀kọ̀. Ṣàfikún ohun tí ó yẹ kó ṣàkóso ìmọ̀ràn Aletheia nìkan.",
    accountDailyWisdomEnabled: "Ọgbọ́n ojoojúmọ́ ti ṣiṣẹ́",
    accountNotificationsSummaryEnabled: "Aletheia yóò lo àṣàyàn àkókò ìbílẹ̀ tí o ti fipamọ́.",
    accountNotificationsSummaryDisabled: "Tan ìrántí ojoojúmọ́ pẹ̀lẹ́ sílẹ̀ nígbà tí ẹ̀rọ yìí bá ti ṣetán.",
    accountInstallTitle: "Ṣàfikún Aletheia sí ojú ìbẹ̀rẹ̀ rẹ",
    accountInstallSummary: "Àwọn ìtọ́nisọ́nà fifi sori ẹrọ wà ní ìdákẹ́jẹ títí ẹnikan fi nílò ìrírí bí app.",
    accountInstallEyebrow: "Fi Aletheia sori ẹrọ",
    accountInviteTitle: "Pe ẹnikan ní ìkọ̀kọ̀",
    accountInviteSummary: "Pin ọna asopọ Aletheia nìkan, kì í ṣe àwọn ìbéèrè ìkọ̀kọ̀, ìwé ìrònú tàbí ìmọ̀ràn ní àìtẹ̀sí.",
    accountInviteEyebrow: "Pe ẹnikan",
    accountHistoryConversations: "àwọn ìjíròrò",
    accountHistoryDecisions: "àwọn ìpinnu",
    accountHistoryReflections: "àwọn ìrònú",
    accountHistorySummary: "Ìtàn máa ń dúró ní fífi pa mọ́ títí o fi fẹ́ wo ohun tí a ti fipamọ́.",
    accountStatConversations: "Àwọn ìjíròrò",
    accountStatDecisions: "Àwọn ìpinnu",
    accountStatJournalEntries: "Àwọn ìforúkọsílẹ̀ ìwé ìrònú",
    accountHistoryEmptyBody: "Bẹ̀rẹ̀ pẹ̀lú ìbéèrè olóòtítọ́ kan tàbí ìpinnu kan lábẹ́ títẹ. Aletheia yóò jẹ́ kí àkọọ́lẹ̀ náà dájú, ṣinṣin, kí ó sì wúlò.",
    accountTrustPostureTitle: "Ìpo ìgbẹ́kẹ̀lé àti ìkọ̀kọ̀",
    accountTrustPostureSummary: "Àwọn ààlà, ibi tí ìtọọ́kasí mímọ́ ti wá, data tí a fipamọ́ àti ìlànà pínpín wà ní mímọ̀ láì kó àkúnya bá ojú-ìwé.",
    accountBoundariesTitle: "Àwọn ààlà Aletheia",
    accountBoundariesSummary: "Àwọn ààlà ààbò app náà wà ní mímọ̀ nígbà tí a bá nílò wọn, kì í sì í di ọ lójú ní gbogbo ìgbà.",
    accountBoundariesBody: "Àwọn ìdènà wọ̀nyí ń dáàbò bo ọ kúrò nínú ìmọ̀ràn AI tó lè ṣàkóbá, wọ́n sì ń jẹ́ kí Aletheia dúró ṣinṣin sí ìdí rẹ.",
    accountFormationPrefix: "Ìdàgbàsókè",
    accountQuietMilestoneSingular: "àmì ìdàgbàsókè pẹ̀lẹ́ kan",
    accountQuietMilestonePlural: "àwọn àmì ìdàgbàsókè pẹ̀lẹ́",
    accountFormationSummary: "Ìdàgbàsókè jẹ́ àkọọ́lẹ̀ ìdákẹ́jẹ ti ìṣe, kì í ṣe pátákó amì-ẹ̀yẹ.",
  },
  ig: {
    nav: { companion: "Ụlọ", decisions: "Mkpebi", reflect: "Tụgharịa uche", library: "Ọba akwụkwọ", account: "Akaụntụ" },
    decideShort: "Kpebie",
    guardrails: "Oke nche",
    guardrailItems: ["Anaghị ebu amụma nsonaazụ ego.", "Anaghị emepụta ntụaka Baịbụl.", "Na-agba ume ịchọ ndụmọdụ maka mkpebi dị mkpa."],
    wisdomMode: "Ụdị amamihe",
    currentLens: "Anya ugbu a",
    offline: "Enweghị njikọ",
    languageSelect: "Gbanwee asụsụ",
    bibleSelect: "Gbanwee ntụgharị Baịbụl",
    account: "Akaụntụ",
    askTitle: "Jụọ Aletheia",
    askIntro: "Malite na otu ajụjụ eziokwu. Aletheia na-enyere gị belata ngwa ngwa ma ghọta nke ọma.",
    yourQuestion: "Ajụjụ gị",
    askButton: "Jụọ",
    startHere: "Bido ebe a",
    ready: "Njikere",
    whatModeFor: "Ihe ụdị a bara uru",
    deepChecks: "Nlele miri emi",
    blindSpots: "Ihe nwere ike ifu anya",
    maturitySignals: "Ihe ngosi ntozu",
    modeGuidance: "Nduzi ụdị",
    change: "Gbanwee",
    showDetails: "Gosi nkọwa",
    hideDetails: "Zoo nkọwa",
    modeGuidancePreview: "Debe echiche a ka ọ dị mfe. Mepee ya mgbe ịchọrọ nlele miri emi, ihe nwere ike ifu anya, na ihe ngosi ntozu.",
    trustLayer: "Ogo ntụkwasị obi",
    preferencesTitle: "Asụsụ na mpaghara",
    language: "Asụsụ",
    region: "Mpaghara",
    bible: "Baịbụl",
    voiceControls: "Njikwa olu",
    available: "Dị",
    englishFallback: "Laghachi n'Bekee",
    greetingMorning: "Ụtụtụ ọma",
    greetingAfternoon: "Ehihie ọma",
    greetingEvening: "Mgbede ọma",
    greetingFallback: "Nnọọ ọzọ",
    greetingIntent: "Ka anyị họrọ otu nzọụkwụ amamihe ọzọ taa.",
    personalizedPriority: "Ihe kacha mkpa nye gị",
    whatNext: "Gịnị ka m kwesịrị ime ugbu a?",
    whatNextBody: "Aletheia na-ahọrọ ihe amamihe ka ọ bụrụ nke mbụ. Ebe ajụjụ na njikwa ụdị dị n'okpuru mgbe ịchọrọ ịmalite ihe ọhụrụ.",
    continueDecision: "Gaa n'ihu na mkpebi a",
    askOneQuestion: "Jụọ otu ajụjụ",
    askOneQuestionBody: "Malite site n'ọnọdụ nsogbu ma ọ bụ mkpebi ị na-ebu ugbu a.",
    askNewQuestion: "Jụọ ajụjụ ọhụrụ",
    askNewQuestionBody: "Ebe ntinye ajụjụ na ụdị amamihe dị n'okpuru.",
    reflectToday: "Tụgharịa uche na taa",
    reviewPattern: "Lelee usoro",
    enableNotifications: "Gbanye ọkwa ozi",
    enableSync: "Gbanye mmekọrịta",
    notificationPromptBody: "Nata otu ụbọchị niile mgbasa ozi amamihe dị jụụ.",
    syncDevicesBody: "Jide mkpebi na ntụgharị uche gị n'ụdị ngwaọrụ niile.",
    startDecision: "Malite mkpebi",
    startDecisionBody: "Soro nhọrọ dị mkpa n'oge.",
    todaysCompanion: "Enyi nke taa",
    todayPrefix: "Taa",
    wisdomPrinciple: "Ụkpụrụ amamihe",
    tinyPractice: "Omume nta",
    reflectionQuestion: "Ajụjụ",
    whatINotice: "Ihe m na-ahụ",
    context: "Ọnọdụ",
    application: "Mmekọrịta",
    carryThisToday: "Buru nke a taa",
    todayScriptureLabel: "Akwụkwọ Nsọ",
    todayQuestionLabel: "Ajụjụ taa",
    todayActionsLabel: "Omume taa",
    weeklyReviewHeading: "Nyocha izu gị",
    weeklyReviewLastWeekLabel: "Izu gara aga",
    weeklyWisdomReview: "Nyocha amamihe kwa izu",
    weeklyReviewTitle: "Nlele dị jụụ n'izu gị",
    weeklyReviewBody: "Enweghị usoro pụrụ iche ma ọ bụ nrụgide. Naanị hụ otú {pattern} si na-akpụ uche gị.",
    carryWithMe: "Buru ya na m",
    askAboutThis: "Jụọ maka nke a",
    saveToRuleOfLife: "Chekwaa dị ka iwu ndụ",
    carryingToday: "Ihe ị na-ebu taa",
    currentCounsel: "Ndụmọdụ ugbu a",
    modeShapesCounsel: "na-akpụ ndụmọdụ a gburugburu",
    trackThisDecision: "Soro mkpebi a",
    saveAsReflection: "Chekwaa dịka ntụgharị uche",
    createCounselSummary: "Mepụta nchịkọta ndụmọdụ",
    goDeeper: "Gaa n'ime",
    waitThreeDays: "Chere ụbọchị 3",
    shareAnswerPrompt: "Kekọrịta Aletheia na onye nwere ike irite uru site n'ụdị ndụmọdụ a.",
    sharePrivacyNote: "Nke a na-ekekọrịta naanị njikọ ngwa ahụ, ọ bụghị ajụjụ gị ma ọ bụ azịza nzuzo Aletheia.",
    shareAletheia: "Kekọrịta Aletheia",
    feedbackQuestion: "Ndụmọdụ a ọ bara uru?",
    feedbackHelpful: "Bara uru",
    feedbackMildlyHelpful: "Bara uru ntakịrị",
    feedbackTooVague: "Adịghị doro anya",
    feedbackTooPreachy: "Na-akụzi nke ukwuu",
    feedbackNotRelevant: "Adịghị mkpa",
    badgesFormation: "Akara / Nhazi",
    firstReflectionSaved: "Ntụgharị uche mbụ echekwara",
    firstDecisionTracked: "Mkpebi mbụ esochiri",
    soughtCounsel: "Chọrọ ndụmọdụ",
    waitingModeUsed: "Jiri ụdị ichere",
    ruleOfLifeCreated: "Iwu ndụ emepụtara",
    notificationsEnabled: "Gbanyere ọkwa ozi",
    sevenDaysPractice: "Ụbọchị 7 nke omume amamihe",
    formationNote: "Ndị a bụ akara nhazi dị jụụ, ọ bụghị isi ihe ị ga-achụ. Nkume njedebe mbụ na-amalitekarị site na ịchekwa otu ntụgharị uche.",
    milestoneShareTitle: "Ị maara onye na-eme mkpebi dị mkpa?",
    milestoneShareBody: "Ị nwere ike ịkpọ ha ka ha bịa Aletheia n'ekekọtaghị ihe ọ bụla nzuzo site na akaụntụ gị.",
    welcomeCounsel:
      "Weta mkpebi n'ezie, nrụgide ma ọ bụ ajụjụ ego. Aga m aza site n'ọba akwụkwọ amamihe ahaziri ahazi, na-enwe nkọwa mmetụta uche ma ọ bụghị nkwa ego.",
    trustScriptureBody:
      "Nrụtụ aka Akwụkwọ Nsọ sitere n'ọba akwụkwọ amamihe ahaziri ahazi Aletheia. Ọ bụrụ na amaokwu apụta, ị nwere ike ịmetụ ya aka ka ị hụ ọnọdụ yana ihe kpatara o ji dị mkpa.",
    trustBoundaryBody:
      "Aletheia agaghị ekwe nkwa nsonaazụ, amachaghị ahịa, kwupụta ijide n'aka Chineke, ma ọ bụ dochie ndụmọdụ ọkachamara ego, iwu, ụtụ isi, ahụike ma ọ bụ ndị ụkọchukwu.",
    trustMemoryBody:
      "Ebe nchekwa ejikọtara na-enyere aka na nkwụsi ike n'etiti mkpebi, ntụgharị uche, ndụmọdụ na iwu ndụ. O kwesịrị ime ka ntụzịaka bụrụ nke onwe karịa n'ekpugheghị nkọwa nzuzo n'efu.",
    trustConnectedDataBody:
      "Njikọta ahụike, ego ma ọ bụ ngwaọrụ n'ọdịnihu kwesịrị ịbụ ikike site na ikike, gbanyụọ na ndabere ma bụrụ naanị data ọ bụla onye ọrụ ahọrọ ịjikọ.",
    accountNextEyebrow: "Ihe na-esote n'Akaụntụ",
    accountNextReviewSyncFormation: "Lelee mmekọrịta na nhazi",
    accountNextSignInPortable: "Banye ka Aletheia nwee ike iso gị gafee ngwaọrụ",
    accountNextActiveBody: "Akaụntụ gị na-arụ ọrụ. Lelee mmasị, akụkọ na nkume nhazi mgbe ịchọrọ ya.",
    accountNextSyncBody: "Mmekọrịta na-arụ ọrụ. Gbanwuo otu mkpali amamihe dị jụụ kwa ụbọchị ma ọ bụrụ na ngwaọrụ a kwesịrị ịnata ya.",
    accountNextGuestBody: "Jiri Google ma ọ bụ email mekọrịta mkpebi, ntụgharị uche, mmasị, ndụmọdụ na ọkwa ozi n'ofe ngwaọrụ.",
    accountManageSummary: "Jikwaa nbanye, mmekọrịta, asụsụ, ọkwa ozi, akụkọ na nkume nhazi na-enweghị imeju Onye Amamihe.",
    accountSignedInAs: "Ị banyere dị ka",
    accountSignInOrGuest: "Banye ma ọ bụ gaa n'ihu dịka ọbịa",
    accountSyncActive: "Mmekọrịta na-arụ ọrụ.",
    accountNotificationsNotEnabled: "Ọkwa ozi agbanyebeghị.",
    accountGuestSummary: "Nbanye Google na email na-eme ka akụkọ, mmasị, mkpebi na ọkwa ozi bụrụ ihe a na-eburu n'ebe ọ bụla.",
    accountPreferencesEyebrow: "Mmasị",
    accountPreferencesSummary: "Asụsụ, ntụgharị Baịbụl, ọdịdị, mpaghara na olu nọ ebe a ka Enyi wee dị jụụ.",
    accountContextActive: "Ọnọdụ na-arụ ọrụ",
    accountContextPaused: "Ọnọdụ kwụsịrị nwa oge",
    accountArea: "mpaghara",
    accountAreas: "mpaghara",
    accountAdded: "agbakwunyere",
    accountManualContextSummary: "Ọnọdụ aka bụ nhọrọ ma bụrụ nke nzuzo. Tinye naanị ihe kwesịrị ịkpụzi ndụmọdụ Aletheia.",
    accountDailyWisdomEnabled: "Amamihe kwa ụbọchị agbanyere",
    accountNotificationsSummaryEnabled: "Aletheia ga-eji mmasị oge obodo ị chekwara.",
    accountNotificationsSummaryDisabled: "Gbanwuo otu mkpali dị jụụ kwa ụbọchị mgbe ngwaọrụ a dị njikere.",
    accountInstallTitle: "Tinye Aletheia na ihuenyo ụlọ gị",
    accountInstallSummary: "Ntuziaka itinye na-anọ nwayọọ ruo mgbe mmadụ chọrọ ahụmịhe dịka app.",
    accountInstallEyebrow: "Tinye Aletheia",
    accountInviteTitle: "Kpọọ mmadụ na nzuzo",
    accountInviteSummary: "Kekọrịta naanị njikọ Aletheia, ọ bụghị ajụjụ nzuzo, akwụkwọ ncheta ma ọ bụ ndụmọdụ n'usoro ndabara.",
    accountInviteEyebrow: "Kpọọ mmadụ",
    accountHistoryConversations: "mkparịta ụka",
    accountHistoryDecisions: "mkpebi",
    accountHistoryReflections: "ntụgharị uche",
    accountHistorySummary: "Akụkọ ihe mere eme na-anọ mechiri emechi ruo mgbe ịchọrọ ilegharị ihe echekwara anya.",
    accountStatConversations: "Mkparịta ụka",
    accountStatDecisions: "Mkpebi",
    accountStatJournalEntries: "Ndenye akwụkwọ ncheta",
    accountHistoryEmptyBody: "Malite na otu ajụjụ eziokwu ma ọ bụ otu mkpebi dị n'okpuru nrụgide. Aletheia ga-eme ka ndekọ ahụ dị jụụ ma baa uru.",
    accountTrustPostureTitle: "Ọnọdụ ntụkwasị obi na nzuzo",
    accountTrustPostureSummary: "Ókè, ebe Akwụkwọ Nsọ si bịa, data echekwara na ụzọ e si ekekọrịta dị ebe a n'enweghị ibu arọ n'ahụ ibe ahụ.",
    accountBoundariesTitle: "Ókè nche Aletheia",
    accountBoundariesSummary: "Ókè nche nchekwa app ahụ na-anọ na anya mgbe achọrọ ha, ọ bụghị igbochi mgbe niile.",
    accountBoundariesBody: "Mgbochi ndị a na-echebe gị pụọ na ndụmọdụ AI nwere ike imerụ ahụ ma na-edobe Aletheia n'ikwesị ntụkwasị obi nye ebumnuche ya.",
    accountFormationPrefix: "Nhazi",
    accountQuietMilestoneSingular: "nkume nhazi dị jụụ",
    accountQuietMilestonePlural: "nkume nhazi dị jụụ",
    accountFormationSummary: "Nhazi bụ ndekọ dị jụụ nke omume, ọ bụghị tebụl akara.",
  },
  ha: {
    nav: { companion: "Gida", decisions: "Shawara", reflect: "Tunani", library: "Laburare", account: "Asusu" },
    decideShort: "Yanke",
    guardrails: "Iyakoki",
    guardrailItems: ["Ba ya hango sakamakon kudi.", "Ba ya kirkirar nassoshin Littafi Mai Tsarki.", "Yana karfafa neman shawara a manyan zabi."],
    wisdomMode: "Yanayin hikima",
    currentLens: "Duban yanzu",
    offline: "Babu intanet",
    languageSelect: "Canza harshe",
    bibleSelect: "Canza fassarar Littafi",
    account: "Asusu",
    askTitle: "Tambayi Aletheia",
    askIntro: "Fara da tambaya ta gaskiya. Aletheia za ta rage gaggawa ta taimaka maka fahimta.",
    yourQuestion: "Tambayarka",
    askButton: "Tambaya",
    startHere: "Fara a nan",
    ready: "Shirye",
    whatModeFor: "Amfanin wannan yanayi",
    deepChecks: "Bincike mai zurfi",
    blindSpots: "Abubuwan da ka iya boye",
    maturitySignals: "Alamun balaga",
    modeGuidance: "Jagorar yanayi",
    change: "Canza",
    showDetails: "Nuna bayani",
    hideDetails: "Boyar da bayani",
    modeGuidancePreview: "Ka wannan kallo ya kasance mai sauki. Bude shi idan kana son bincike mai zurfi, abubuwan da ka iya boye, da alamun balaga.",
    trustLayer: "Matakin amincewa",
    preferencesTitle: "Harshe da yanki",
    language: "Harshe",
    region: "Yanki",
    bible: "Littafi",
    voiceControls: "Sarrafa murya",
    available: "Akwai",
    englishFallback: "Komawa Turanci",
    greetingMorning: "Ina kwana",
    greetingAfternoon: "Ina wuni",
    greetingEvening: "Barka da yamma",
    greetingFallback: "Barka da dawowa",
    greetingIntent: "Mu zabi mataki na hikima na gaba yau.",
    personalizedPriority: "Fifikon ku",
    whatNext: "Me zan yi a yanzu?",
    whatNextBody: "Aletheia tana zaɓar aiki na hikima da farko. Filin tambaya da sarrafa yanayi suna a ƙasa lokacin da kuke son fara sabon abu.",
    continueDecision: "Ci gaba da wannan shawarar",
    askOneQuestion: "Yi tambaya ɗaya",
    askOneQuestionBody: "Fara da matsin lamba ko shawarar da kuke ɗauka a yanzu.",
    askNewQuestion: "Yi sabuwar tambaya",
    askNewQuestionBody: "Filin Companion da salon hikima suna a ƙasa.",
    reflectToday: "Yi tunani a yau",
    reviewPattern: "Bincika tsari",
    enableNotifications: "Kunna sanarwa",
    enableSync: "Kunna haɗin kai",
    notificationPromptBody: "Karɓi ƙarfafawa na hikima na yau da kullun a hankali.",
    syncDevicesBody: "Ajiye shawara da tunani a dukkan na'urori.",
    startDecision: "Fara shawara",
    startDecisionBody: "Bi zaɓi mai mahimmanci a lokaci.",
    todaysCompanion: "Abokin yau",
    todayPrefix: "Yau",
    wisdomPrinciple: "Ka'idar hikima",
    tinyPractice: "Karamin aiki",
    reflectionQuestion: "Tambaya",
    whatINotice: "Abin da na lura da shi",
    context: "Mahalli",
    application: "Aikace-aikace",
    carryThisToday: "Rike wannan yau",
    todayScriptureLabel: "Nassi",
    todayQuestionLabel: "Tambayar yau",
    todayActionsLabel: "Ayyukan yau",
    weeklyReviewHeading: "Bitar mako naka",
    weeklyReviewLastWeekLabel: "Makon da ya gabata",
    weeklyWisdomReview: "Bitar hikima ta mako",
    weeklyReviewTitle: "Dubi mai natsuwa ga makonka",
    weeklyReviewBody: "Ba tare da tsari ko matsin lamba ba. Ka lura yadda {pattern} ke tsara fahimtarka.",
    carryWithMe: "Rike tare da ni",
    askAboutThis: "Tambaya game da wannan",
    saveToRuleOfLife: "Ajiye a matsayin ka'idar rayuwa",
    carryingToday: "Abin da kake rike da shi yau",
    currentCounsel: "Shawarar yanzu",
    modeShapesCounsel: "yana tsara wannan shawarar dangane da",
    trackThisDecision: "Bi wannan shawarar",
    saveAsReflection: "Adana azaman tunani",
    createCounselSummary: "Ƙirƙiri taƙaitaccen shawara",
    goDeeper: "Je mai zurfi",
    waitThreeDays: "Jira kwanaki 3",
    shareAnswerPrompt: "Raba Aletheia da wanda zai iya amfana da irin wannan shawarar.",
    sharePrivacyNote: "Wannan yana raba mahaɗin app kawai, ba tambayar ku ko amsar sirri ta Aletheia ba.",
    shareAletheia: "Raba Aletheia",
    feedbackQuestion: "Wannan shawarar ta taimaka?",
    feedbackHelpful: "Mai taimako",
    feedbackMildlyHelpful: "Yana taimakawa kaɗan",
    feedbackTooVague: "Ba a fayyace ba",
    feedbackTooPreachy: "Wa'azi da yawa",
    feedbackNotRelevant: "Ba ya dacewa",
    badgesFormation: "Tambari / Tsarawa",
    firstReflectionSaved: "Tunani na farko an adana",
    firstDecisionTracked: "Shawara ta farko an bi",
    soughtCounsel: "Neman shawara",
    waitingModeUsed: "An yi amfani da yanayin jira",
    ruleOfLifeCreated: "An ƙirƙiri ƙa'idar rayuwa",
    notificationsEnabled: "An kunna sanarwa",
    sevenDaysPractice: "Kwanaki 7 na aikin hikima",
    formationNote: "Waɗannan alamomi ne na hankali na tsarawa, ba maki da za a bi ba. Alamar farko yawanci tana farawa da adana tunani ɗaya.",
    milestoneShareTitle: "Kun san wanda ke yin muhimmiyar shawara?",
    milestoneShareBody: "Kuna iya gayyatonsu zuwa Aletheia ba tare da raba wani abu mai sirri daga asusunku ba.",
    welcomeCounsel:
      "Kawo shawara ta gaske, matsin lamba ko tambayar kuɗi. Zan amsa daga ɗakin karatu na hikima da aka tsara, tare da fayyace motsin rai kuma ba tare da alkawuran kuɗi ba.",
    trustScriptureBody:
      "Nassoshi na Littafi Mai Tsarki sun fito ne daga ɗakin karatu na hikima na Aletheia. Idan aya ta bayyana, zaku iya danna ta don ganin mahallin da dalilin da ya sa yake da muhimmanci.",
    trustBoundaryBody:
      "Aletheia ba zai yi alkawarin sakamako ba, ba zai yi hasashen kasuwanni ba, ba zai yi iƙirarin tabbacin Allah ba, ko kuma ya maye gurbin shawara ta ƙwararru na kuɗi, doka, haraji, likita ko na limamin coci.",
    trustMemoryBody:
      "Ƙwaƙwalwar ajiya da aka haɗa tana taimakawa daidaituwa tsakanin shawara, tunani, shawara da ƙa'idodin rayuwa. Ya kamata ya sanya jagora ta zama ta sirri fiye ba tare da fallasa cikakkun bayanai na sirri ba tare da buƙata ba.",
    trustConnectedDataBody:
      "Haɗin lafiya, kuɗi ko na'ura na gaba yakamata su kasance izini-zuwa-izini, kashe a tsohuwa kuma iyakance ga ainihin bayanan da mai amfani ya zaɓa don haɗawa.",
    accountNextEyebrow: "Na gaba a Asusu",
    accountNextReviewSyncFormation: "Duba daidaitawa da tsarawa",
    accountNextSignInPortable: "Shiga domin ka rika daukar Aletheia tare da kai",
    accountNextActiveBody: "Asusunka yana aiki. Duba abubuwan da ka fi so, tarihi da matakan tsarawa idan kana bukata.",
    accountNextSyncBody: "Daidaitawa tana aiki. Kunna dan karamin tunasarwar hikima ta yau idan wannan na'ura ya kamata ta karbe ta.",
    accountNextGuestBody: "Yi amfani da Google ko imel don daidaita shawarwari, tunani, abubuwan da ka fi so, nasiha da sanarwa a tsakanin na'urori.",
    accountManageSummary: "Sarrafa shiga, daidaitawa, harshe, sanarwa, tarihi da matakan tsarawa ba tare da cunkushe abokin hikima ba.",
    accountSignedInAs: "An shiga a matsayin",
    accountSignInOrGuest: "Shiga ko ci gaba a matsayin bako",
    accountSyncActive: "Daidaitawa tana aiki.",
    accountNotificationsNotEnabled: "Ba a kunna sanarwa ba tukuna.",
    accountGuestSummary: "Shiga da Google da imel yana sa tarihinka, abubuwan da ka fi so, shawarwari da sanarwa su kasance masu saukin dauka a ko'ina.",
    accountPreferencesEyebrow: "Abubuwan da aka fi so",
    accountPreferencesSummary: "Harshe, fassarar Littafi, bayyanar fuska, yanki da murya suna nan domin Aboki ya zauna cikin natsuwa.",
    accountContextActive: "Mahalli yana aiki",
    accountContextPaused: "An dakatar da mahalli",
    accountArea: "fanni",
    accountAreas: "fannoni",
    accountAdded: "an kara",
    accountManualContextSummary: "Mahallin hannu na zabi ne kuma na sirri ne. Kara kawai abin da ya kamata ya tsara nasihohin Aletheia.",
    accountDailyWisdomEnabled: "An kunna hikimar yau da kullum",
    accountNotificationsSummaryEnabled: "Aletheia za ta yi amfani da zabin lokacinka na gida da aka riga aka ajiye.",
    accountNotificationsSummaryDisabled: "Kunna dan karamin tunasarwar yau da kullum idan wannan na'ura ta shirya.",
    accountInstallTitle: "Saka Aletheia a allon gida",
    accountInstallSummary: "Umarnin shigarwa suna zaune a hankali har sai wani ya bukaci tsarin kama da app.",
    accountInstallEyebrow: "Saka Aletheia",
    accountInviteTitle: "Gayyaci wani a boye",
    accountInviteSummary: "Raba hanyar Aletheia kadai, ba tambayoyin sirri ba, ba rubutun tunani ba, ba kuma nasiha ta tsohuwa ba.",
    accountInviteEyebrow: "Gayyaci wani",
    accountHistoryConversations: "tattaunawa",
    accountHistoryDecisions: "shawarwari",
    accountHistoryReflections: "tunani",
    accountHistorySummary: "Tarihi yana nan a dunkule har sai kana son duba abin da aka ajiye.",
    accountStatConversations: "Tattaunawa",
    accountStatDecisions: "Shawarwari",
    accountStatJournalEntries: "Rubuce-rubucen tunani",
    accountHistoryEmptyBody: "Fara da tambaya ta gaskiya daya ko shawara daya a karkashin matsin lamba. Aletheia za ta sa bayanin ya kasance cikin natsuwa kuma mai amfani.",
    accountTrustPostureTitle: "Matsayin amincewa da sirri",
    accountTrustPostureSummary: "Iyakoki, tushen nassosi, bayanan da aka ajiye da yadda ake rabawa suna samuwa ba tare da cika shafin da yawa ba.",
    accountBoundariesTitle: "Iyakokin kariyar Aletheia",
    accountBoundariesSummary: "Iyakokin tsaron app suna nan a bayyane idan an bukace su, ba tare da zama cikas kullum ba.",
    accountBoundariesBody: "Wadannan takurawa suna kare ka daga nasihohin AI masu cutarwa kuma suna sa Aletheia ta kasance mai aminci ga manufarta.",
    accountFormationPrefix: "Tsarawa",
    accountQuietMilestoneSingular: "matakin tsarawa mai nutsuwa",
    accountQuietMilestonePlural: "matakan tsarawa masu nutsuwa",
    accountFormationSummary: "Tsarawa rikodi ne mai natsuwa na aiki, ba allon maki ba.",
  },
  tl: {
    nav: { companion: "Tahanan", decisions: "Mga Desisyon", reflect: "Pagninilay", library: "Aklatan", account: "Akaunti" },
    decideShort: "Magpasya",
    guardrails: "Mga hangganan",
    guardrailItems: ["Hindi kailanman naghuhula ng pinansyal na resulta.", "Hindi kailanman gumagawa ng mga sanggunian sa Kasulatan.", "Hinihikayat ang tulong ng tao sa self-harm, adiksyon, o krisis."],
    wisdomMode: "Paraan ng karunungan",
    currentLens: "Kasalukuyang lente",
    offline: "Wala sa online",
    languageSelect: "Palitan ang wika",
    bibleSelect: "Palitan ang salin ng Biblia",
    account: "Akaunti",
    askTitle: "Magtanong kay Aletheia",
    askIntro: "Magsimula sa isang tapat na tanong. Pinapabagal ni Aletheia ang sandali at tumutulong maglinaw ng isip.",
    yourQuestion: "Ang tanong mo",
    askButton: "Magtanong",
    startHere: "Magsimula rito",
    ready: "Handa",
    whatModeFor: "Para saan ang paraang ito",
    deepChecks: "Masusing pagsuri",
    blindSpots: "Mga hindi napapansin",
    maturitySignals: "Mga palatandaan ng paghinog",
    modeGuidance: "Patnubay sa paraan",
    change: "Palitan",
    showDetails: "Ipakita ang detalye",
    hideDetails: "Itago ang detalye",
    modeGuidancePreview: "Panatilihing nakatuon ang tinging ito. Palawakin kapag gusto mo ng mas malalim na pagsusuri, mga hindi napapansin, at mga palatandaan ng paghinog.",
    trustLayer: "Patong ng tiwala",
    preferencesTitle: "Wika at rehiyon",
    language: "Wika",
    region: "Rehiyon",
    bible: "Biblia",
    voiceControls: "Kontrol sa boses",
    available: "Magagamit",
    englishFallback: "Kapalit na Ingles",
    greetingMorning: "Magandang umaga",
    greetingAfternoon: "Magandang hapon",
    greetingEvening: "Magandang gabi",
    greetingFallback: "Maligayang pagbabalik",
    greetingIntent: "Pumili tayo ng isang matalinong susunod na hakbang ngayon.",
    personalizedPriority: "Piniling prayoridad",
    whatNext: "Ano ang susunod kong dapat gawin?",
    whatNextBody: "Pinipili muna ni Aletheia ang isang matalinong susunod na aksyon. Nasa malapit pa rin ang tanong at mga kontrol sa paraan kapag handa ka nang magsimula.",
    personalizationNudgeTitle: "Gusto mo ng mas personal na payo?",
    personalizationNudgeBody: "Magdagdag ng isang detalye tungkol sa pera, trabaho, o ritmo.",
    continueDecision: "Ipagpatuloy ang desisyong ito",
    askOneQuestion: "Magtanong ng isang tanong",
    askOneQuestionBody: "Magsimula sa bigat o desisyong dala mo ngayon.",
    askNewQuestion: "Magtanong ng bago",
    askNewQuestionBody: "Nasa malapit lang ang input ng kasama at mga paraang may karunungan.",
    reflectToday: "Magnilay ngayon",
    reviewPattern: "Suriin ang pattern",
    enableNotifications: "I-enable ang mga abiso",
    enableSync: "I-on ang pagsabay",
    notificationPromptBody: "Tumanggap ng isang tahimik na paalala ng karunungan bawat araw.",
    syncDevicesBody: "Panatilihing magkakasabay ang mga desisyon at pagninilay sa iba't ibang aparato.",
    startDecision: "Magsimula ng desisyon",
    startDecisionBody: "Subaybayan ang isang mahalagang pagpili sa paglipas ng panahon.",
    tinyPractice: "Maliit na pagsasanay",
    todaysCompanion: "Kasama ngayon",
    todayPrefix: "Ngayon",
    wisdomPrinciple: "Prinsipyo ng karunungan",
    reflectionQuestion: "Tanong",
    whatINotice: "Napapansin ko",
    context: "Konteksto",
    application: "Paglalapat",
    carryThisToday: "Dalhin ito ngayon",
    carryWithMe: "Dalhin ko",
    weeklyWisdomReview: "Lingguhang Pagsusuri ng Karunungan",
    weeklyReviewTitle: "Tahimik na tingin sa linggong ito",
    weeklyReviewBody: "Walang pressure o streak. Pansinin lang kung paano hinuhubog ng {pattern} ang paghatol mo.",
    todayScriptureLabel: "Kasulatan",
    todayQuestionLabel: "Tanong ngayon",
    todayActionsLabel: "Mga gawain ngayon",
    weeklyReviewHeading: "Iyong Lingguhang Pagsusuri",
    weeklyReviewLastWeekLabel: "Noong nakaraang linggo",
    nextFaithfulStep: "Susunod na tapat na hakbang",
    askAboutThis: "Magtanong tungkol dito",
    saveToRuleOfLife: "I-save sa tuntunin ng buhay",
    carryingToday: "Bitbit ngayong araw",
    currentCounsel: "Kasalukuyang payo",
    modeShapesCounsel: "ang humuhubog sa payong ito batay sa",
    trackThisDecision: "Subaybayan ang desisyong ito",
    saveAsReflection: "I-save bilang pagninilay",
    createCounselSummary: "Gumawa ng buod ng payo",
    goDeeper: "Pumunta nang mas malalim",
    waitThreeDays: "Maghintay ng 3 araw",
    shareAnswerPrompt: "Ibahagi ang Aletheia sa taong maaaring makinabang sa ganitong payo.",
    sharePrivacyNote: "Ibinabahagi lang nito ang link ng app, hindi ang tanong mo o ang pribadong sagot ni Aletheia.",
    shareAletheia: "Ibahagi ang Aletheia",
    feedbackQuestion: "Nakatulong ba ang payong ito?",
    feedbackHelpful: "Nakatulong",
    feedbackMildlyHelpful: "Medyo nakatulong",
    feedbackTooVague: "Masyadong malabo",
    feedbackTooPreachy: "Masyadong parang sermon",
    feedbackNotRelevant: "Hindi akma",
    badgesFormation: "Mga palatandaan / Paghubog",
    firstReflectionSaved: "Naka-save ang unang pagninilay",
    firstDecisionTracked: "Nabinyayang unang desisyon",
    soughtCounsel: "Humingi ng payo",
    waitingModeUsed: "Ginamit ang paraan ng paghihintay",
    ruleOfLifeCreated: "Nagawa ang tuntunin ng buhay",
    notificationsEnabled: "Naka-on ang mga abiso",
    sevenDaysPractice: "7 araw ng pagsasanay sa karunungan",
    formationNote: "Mga tahimik itong palatandaan ng paghubog, hindi mga puntong habulin. Karaniwang nagsisimula ang unang milestone sa pag-save ng isang pagninilay.",
    milestoneShareTitle: "May kilala ka bang gumagawa ng mahalagang desisyon?",
    milestoneShareBody: "Maaari mo silang anyayahan sa Aletheia nang hindi nagbabahagi ng pribado mula sa iyong akaunti.",
    welcomeCounsel: "Magdala ng totoong desisyon, pressure, o tanong sa pera. Sasagot ako mula sa piniling aklatan ng karunungan, nang may kalinawan at walang pangakong pinansyal.",
    trustScriptureBody: "Ang mga sanggunian sa Kasulatan ay mula sa piniling aklatan ng karunungan ni Aletheia. Kapag may lumabas na talata, maaari mo itong i-tap para makita ang konteksto at kahalagahan nito.",
    trustBoundaryBody: "Hindi mangangako si Aletheia ng resulta, manghuhula ng merkado, maghahabol ng banal na katiyakan, o papalitan ang kwalipikadong payo sa pananalapi, legal, buwis, medikal, o pastoral.",
    trustMemoryBody: "Tumutulong ang naka-login na memorya sa pagpapatuloy ng mga desisyon, pagninilay, payo, at mga tuntunin sa buhay. Dapat nitong gawing mas personal ang gabay nang hindi inilalantad ang pribadong detalye nang hindi kailangan.",
    trustConnectedDataBody: "Ang mga susunod na integrasyon sa kalusugan, pananalapi, o mga aparato ay dapat may malinaw na pahintulot, naka-off bilang default, at limitado lamang sa eksaktong datos na pipiliing ikonekta ng user.",
    accountNextEyebrow: "Susunod sa Akaunti",
    accountNextReviewSyncFormation: "Suriin ang pagsabay at paghubog",
    accountNextSignInPortable: "Mag-log in para madala si Aletheia saan ka man",
    accountNextActiveBody: "Aktibo ang iyong akaunti. Suriin ang mga kagustuhan, kasaysayan, at mga milestone ng paghubog kapag kailangan mo.",
    accountNextSyncBody: "Aktibo ang pagsabay. I-on ang isang tahimik na pang-araw-araw na paalala ng karunungan kung dapat itong matanggap ng aparatong ito.",
    accountNextGuestBody: "Gamitin ang Google o email para isabay ang mga desisyon, pagninilay, mga kagustuhan, payo, at abiso sa iba't ibang aparato.",
    accountManageSummary: "Pamahalaan ang pag-login, pagsabay, wika, mga abiso, kasaysayan, at mga milestone ng paghubog nang hindi sumasakal sa kasama ng karunungan.",
    accountSignedInAs: "Naka-login bilang",
    accountSignInOrGuest: "Mag-login o magpatuloy bilang bisita",
    accountSyncActive: "Aktibo ang pagsabay.",
    accountNotificationsNotEnabled: "Hindi pa naka-on ang mga abiso.",
    accountGuestSummary: "Mag-sign in para mapanatili ang iyong kasaysayan, mga kagustuhan, at mga desisyon.",
    accountPreferencesEyebrow: "Mga kagustuhan",
    accountPreferencesSummary: "Nandito ang wika, salin ng Biblia, itsura, rehiyon, at boses para manatiling kalmado ang kasama.",
    accountContextActive: "Aktibo ang konteksto",
    accountContextPaused: "Naka-pause ang konteksto",
    accountArea: "lugar",
    accountAreas: "mga lugar",
    accountAdded: "naidagdag",
    accountManualContextSummary: "Opsyonal at pribado ang manual na konteksto. Idagdag lamang ang dapat humubog sa payo ni Aletheia.",
    accountDailyWisdomEnabled: "Naka-enable ang pang-araw-araw na karunungan",
    accountNotificationsSummaryEnabled: "Gagamitin ni Aletheia ang iyong naka-save na lokal na oras.",
    accountNotificationsSummaryDisabled: "I-on ang isang tahimik na pang-araw-araw na paalala kapag handa na ang aparatong ito.",
    accountInstallTitle: "Idagdag si Aletheia sa home screen mo",
    accountInstallSummary: "Nakatago ang mga tagubilin sa pag-install hanggang may kailangan sa setup na parang app.",
    accountInstallEyebrow: "I-install si Aletheia",
    accountInviteTitle: "Imbitahan ang isang tao nang pribado",
    accountInviteSummary: "Ibahagi lang ang link ni Aletheia, hindi kailanman pribadong tanong, tala sa araw-araw, o payo bilang default.",
    accountInviteEyebrow: "Mag-imbita ng tao",
    accountHistoryConversations: "mga usapan",
    accountHistoryDecisions: "mga desisyon",
    accountHistoryReflections: "mga pagninilay",
    accountHistorySummary: "Nakatiklop ang kasaysayan hanggang gusto mong balikan ang mga na-save.",
    accountStatConversations: "Mga usapan",
    accountStatDecisions: "Mga desisyon",
    accountStatJournalEntries: "Mga tala sa araw-araw",
    accountHistoryEmptyBody: "Magsimula sa isang tapat na tanong o isang desisyong may pressure. Panatilihing tahimik at kapaki-pakinabang ni Aletheia ang tala.",
    accountTrustPostureTitle: "Tiwala at pagkapribado",
    accountTrustPostureSummary: "Makikita ang mga hangganan, naka-save na data, at mga patakaran sa pagbabahagi.",
    accountBoundariesTitle: "Mga hangganan ni Aletheia",
    accountBoundariesSummary: "Nananatiling nakikita ang mga hangganan ng seguridad ng app kapag kailangan, hindi lagi nakaharang.",
    accountBoundariesBody: "Pinoprotektahan ka ng mga limitasyong ito mula sa mapaminsalang payo ng AI at pinananatiling tapat si Aletheia sa layunin nito.",
    accountFormationPrefix: "Paghubog",
    accountQuietMilestoneSingular: "tahimik na milestone",
    accountQuietMilestonePlural: "mga tahimik na milestone",
    accountFormationSummary: "Ang paghubog ay isang kalmadong tala ng pagsasanay, hindi talaan ng puntos.",
  },
  ar: {
    nav: { companion: "الرئيسية", decisions: "القرارات", reflect: "التأمل", library: "المكتبة", account: "الحساب" },
    decideShort: "اتخذ قرارًا",
    guardrails: "الضوابط",
    guardrailItems: ["لا يتنبأ بالنتائج المالية.", "لا يخترع مراجع كتابية.", "يشجع على طلب دعم بشري عند لغة إيذاء النفس أو الإدمان أو الأزمات."],
    wisdomMode: "وضع الحكمة",
    currentLens: "المنظور الحالي",
    offline: "غير متصل",
    languageSelect: "تغيير اللغة",
    bibleSelect: "تغيير ترجمة الكتاب المقدس",
    account: "الحساب",
    askTitle: "اسأل Aletheia",
    askIntro: "ابدأ بسؤال صادق. يبطئ Aletheia اللحظة ويساعدك على التمييز بوضوح.",
    yourQuestion: "سؤالك",
    askButton: "اسأل",
    startHere: "ابدأ هنا",
    ready: "جاهز",
    whatModeFor: "ما فائدة هذا الوضع",
    deepChecks: "فحوصات عميقة",
    blindSpots: "نقاط عمياء",
    maturitySignals: "علامات النضج",
    modeGuidance: "إرشادات الوضع",
    change: "تغيير",
    showDetails: "عرض التفاصيل",
    hideDetails: "إخفاء التفاصيل",
    modeGuidancePreview: "أبقِ هذه الصفحة مركزة. وسّعها عندما تريد فحوصات أعمق ونقاطًا عمياء وعلامات نضج.",
    trustLayer: "طبقة الثقة",
    preferencesTitle: "اللغة والمنطقة",
    language: "اللغة",
    region: "المنطقة",
    bible: "الكتاب المقدس",
    voiceControls: "التحكم بالصوت",
    available: "متاح",
    englishFallback: "البديل الإنجليزي",
    greetingMorning: "صباح الخير",
    greetingAfternoon: "مساء الخير",
    greetingEvening: "مساء الخير",
    greetingFallback: "مرحبًا بعودتك",
    greetingIntent: "لنختر خطوة حكيمة واحدة اليوم.",
    personalizedPriority: "أولوية مخصصة",
    whatNext: "ما الذي ينبغي أن أفعله بعد ذلك؟",
    whatNextBody: "يختار Aletheia أولًا إجراءً حكيمًا واحدًا. يبقى سؤال البدء والتحكم في الوضع قريبين عندما ترغب في بدء شيء جديد.",
    personalizationNudgeTitle: "هل تريد مشورة أكثر شخصية؟",
    personalizationNudgeBody: "أضف تفصيلًا واحدًا عن المال أو العمل أو الإيقاع.",
    continueDecision: "تابع هذا القرار",
    askOneQuestion: "اطرح سؤالًا واحدًا",
    askOneQuestionBody: "ابدأ بالضغط أو القرار الذي تحمله الآن.",
    askNewQuestion: "اطرح سؤالًا جديدًا",
    askNewQuestionBody: "يبقى إدخال الرفيق وأوضاع الحكمة قريبين.",
    reflectToday: "تأمل اليوم",
    reviewPattern: "راجع نمطًا",
    enableNotifications: "تفعيل الإشعارات",
    enableSync: "تفعيل المزامنة",
    notificationPromptBody: "استقبل تنبيه حكمة يوميًا بهدوء.",
    syncDevicesBody: "احتفظ بالقرارات والتأملات عبر الأجهزة.",
    startDecision: "ابدأ قرارًا",
    startDecisionBody: "تتبّع اختيارًا مهمًا عبر الزمن.",
    tinyPractice: "ممارسة صغيرة",
    todaysCompanion: "رفيق اليوم",
    todayPrefix: "اليوم",
    wisdomPrinciple: "مبدأ الحكمة",
    reflectionQuestion: "سؤال",
    whatINotice: "ما ألاحظه",
    context: "السياق",
    application: "التطبيق",
    carryThisToday: "احمله اليوم",
    carryWithMe: "احمله معي",
    weeklyWisdomReview: "مراجعة الحكمة الأسبوعية",
    weeklyReviewTitle: "نظرة هادئة إلى أسبوعك",
    weeklyReviewBody: "من دون ضغط أو سباق. فقط لاحظ كيف شكّل {pattern} تمييزك.",
    todayScriptureLabel: "الكتاب المقدس",
    todayQuestionLabel: "سؤال اليوم",
    todayActionsLabel: "أفعال اليوم",
    weeklyReviewHeading: "مراجعتك الأسبوعية",
    weeklyReviewLastWeekLabel: "الأسبوع الماضي",
    nextFaithfulStep: "الخطوة الأمينة التالية",
    askAboutThis: "اسأل عن هذا",
    saveToRuleOfLife: "حفظ في قاعدة الحياة",
    carryingToday: "ما تحمله اليوم",
    currentCounsel: "المشورة الحالية",
    modeShapesCounsel: "يشكّل هذه المشورة حول",
    trackThisDecision: "تتبّع هذا القرار",
    saveAsReflection: "حفظ كتأمل",
    createCounselSummary: "إنشاء ملخص للمشورة",
    goDeeper: "تعمق أكثر",
    waitThreeDays: "انتظر 3 أيام",
    shareAnswerPrompt: "شارك Aletheia مع شخص قد يستفيد من هذا النوع من المشورة.",
    sharePrivacyNote: "هذه المشاركة تشمل رابط التطبيق فقط، لا سؤالك ولا جواب Aletheia الخاص.",
    shareAletheia: "مشاركة Aletheia",
    feedbackQuestion: "هل كانت هذه المشورة مفيدة؟",
    feedbackHelpful: "مفيدة",
    feedbackMildlyHelpful: "مفيدة قليلًا",
    feedbackTooVague: "غامضة جدًا",
    feedbackTooPreachy: "وعظية جدًا",
    feedbackNotRelevant: "غير مناسبة",
    badgesFormation: "شارات / التكوين",
    firstReflectionSaved: "تم حفظ أول تأمل",
    firstDecisionTracked: "تم تتبع أول قرار",
    soughtCounsel: "طلب المشورة",
    waitingModeUsed: "تم استخدام وضع الانتظار",
    ruleOfLifeCreated: "تم إنشاء قاعدة الحياة",
    notificationsEnabled: "تم تفعيل الإشعارات",
    sevenDaysPractice: "7 أيام من ممارسة الحكمة",
    formationNote: "هذه علامات هادئة على التكوين، وليست نقاطًا للمطاردة. يبدأ أول معلم عادةً بحفظ تأمل واحد.",
    milestoneShareTitle: "هل تعرف شخصًا يتخذ قرارًا مهمًا؟",
    milestoneShareBody: "يمكنك دعوته إلى Aletheia دون مشاركة أي شيء خاص من حسابك.",
    welcomeCounsel: "اسأل عن قرار حقيقي أو ضغط أو مال. سأجيب من مكتبة الحكمة المنسقة، بوضوح وبدون وعود مالية.",
    trustScriptureBody: "تأتي مراجع الكتاب المقدس من مكتبة الحكمة المنسقة في Aletheia. إذا ظهرت آية، يمكنك النقر عليها لرؤية السياق ومعرفة سبب أهميتها.",
    trustBoundaryBody: "لن يعد Aletheia بالنتائج، أو يتنبأ بالأسواق، أو يدعي يقينًا إلهيًا، أو يحل محل المشورة المؤهلة المالية أو القانونية أو الضريبية أو الطبية أو الرعوية.",
    trustMemoryBody: "تساعد الذاكرة المسجّلة على الاستمرارية عبر القرارات والتأملات والمشورة وقواعد الحياة. ويجب أن تجعل التوجيه أكثر شخصية من دون الكشف عن التفاصيل الخاصة بلا حاجة.",
    trustConnectedDataBody: "يجب أن تكون عمليات التكامل المستقبلية مع الصحة أو التمويل أو الأجهزة قائمة على إذن واضح، ومغلقة افتراضيًا، ومحدودة بالبيانات الدقيقة التي يختار المستخدم ربطها.",
    accountNextEyebrow: "التالي في الحساب",
    accountNextReviewSyncFormation: "راجع المزامنة والتكوين",
    accountNextSignInPortable: "سجّل الدخول لتجعل Aletheia معك",
    accountNextActiveBody: "حسابك نشط. راجع التفضيلات والسجل ومراحل التكوين عند الحاجة.",
    accountNextSyncBody: "المزامنة نشطة. فعّل تنبيه حكمة يومي هادئ إذا كان هذا الجهاز يجب أن يستقبله.",
    accountNextGuestBody: "استخدم Google أو البريد الإلكتروني لمزامنة القرارات والتأملات والتفضيلات والمشورة والإشعارات عبر الأجهزة.",
    accountManageSummary: "أدر تسجيل الدخول والمزامنة واللغة والإشعارات والسجل ومراحل التكوين دون إرباك رفيق الحكمة.",
    accountSignedInAs: "تم تسجيل الدخول باسم",
    accountSignInOrGuest: "سجّل الدخول أو تابع كضيف",
    accountSyncActive: "المزامنة نشطة.",
    accountNotificationsNotEnabled: "الإشعارات غير مفعلة بعد.",
    accountGuestSummary: "سجّل الدخول للاحتفاظ بسجلك وتفضيلاتك وقراراتك.",
    accountPreferencesEyebrow: "التفضيلات",
    accountPreferencesSummary: "تظل اللغة وترجمة الكتاب المقدس والمظهر والمنطقة والصوت هنا ليبقى الرفيق هادئًا.",
    accountContextActive: "السياق نشط",
    accountContextPaused: "السياق متوقف مؤقتًا",
    accountArea: "منطقة",
    accountAreas: "مناطق",
    accountAdded: "تمت الإضافة",
    accountManualContextSummary: "السياق اليدوي اختياري وخاص. أضف فقط ما ينبغي أن يشكل نصيحة Aletheia.",
    accountDailyWisdomEnabled: "تم تفعيل الحكمة اليومية",
    accountNotificationsSummaryEnabled: "سيستخدم Aletheia تفضيل وقتك المحلي المحفوظ.",
    accountNotificationsSummaryDisabled: "فعّل تنبيهًا يوميًا هادئًا عندما يكون هذا الجهاز جاهزًا.",
    accountInstallTitle: "أضف Aletheia إلى الشاشة الرئيسية",
    accountInstallSummary: "تبقى تعليمات التثبيت مخفية حتى يحتاج أحدهم إلى إعداد يشبه التطبيق.",
    accountInstallEyebrow: "تثبيت Aletheia",
    accountInviteTitle: "ادعُ شخصًا بشكل خاص",
    accountInviteSummary: "شارك رابط Aletheia فقط، ولا تشارك افتراضيًا أي أسئلة خاصة أو مذكرات أو مشورة.",
    accountInviteEyebrow: "دعوة شخص",
    accountHistoryConversations: "المحادثات",
    accountHistoryDecisions: "القرارات",
    accountHistoryReflections: "التأملات",
    accountHistorySummary: "يبقى السجل مطويًا حتى ترغب في مراجعة ما تم حفظه.",
    accountStatConversations: "المحادثات",
    accountStatDecisions: "القرارات",
    accountStatJournalEntries: "إدخالات دفتر اليوميات",
    accountHistoryEmptyBody: "ابدأ بسؤال صادق أو قرار تحت الضغط. سيبقي Aletheia السجل هادئًا ومفيدًا.",
    accountTrustPostureTitle: "وضعية الثقة والخصوصية",
    accountTrustPostureSummary: "اعرض الحدود والبيانات المحفوظة وقواعد المشاركة.",
    accountBoundariesTitle: "ضوابط Aletheia",
    accountBoundariesSummary: "تبقى حدود الأمان في التطبيق ظاهرة عند الحاجة، من دون أن تعيقك دائمًا.",
    accountBoundariesBody: "تحميك هذه القيود من نصائح الذكاء الاصطناعي الضارة وتبقي Aletheia مخلصًا لرسالته.",
    accountFormationPrefix: "التكوين",
    accountQuietMilestoneSingular: "معلم هادئ",
    accountQuietMilestonePlural: "معالم هادئة",
    accountFormationSummary: "التكوين سجل هادئ للممارسة، لا لوحة نتائج.",
  },
  hi: {
    nav: { companion: "घर", decisions: "निर्णय", reflect: "चिंतन", library: "पुस्तकालय", account: "खाता" },
    decideShort: "निर्णय लें",
    guardrails: "सुरक्षा सीमाएँ",
    guardrailItems: ["वित्तीय परिणामों का अनुमान नहीं लगाता।", "शास्त्र संदर्भ नहीं गढ़ता।", "आत्म-हानि, लत या संकट भाषा में मानव सहायता के लिए प्रेरित करता है।"],
    wisdomMode: "ज्ञान अवस्था",
    currentLens: "वर्तमान दृष्टि",
    offline: "ऑफ़लाइन",
    languageSelect: "भाषा बदलें",
    bibleSelect: "बाइबिल अनुवाद बदलें",
    account: "खाता",
    askTitle: "Aletheia से पूछें",
    askIntro: "एक सच्चे प्रश्न से शुरू करें। Aletheia क्षण को धीमा करता है और स्पष्टता से समझने में मदद करता है।",
    yourQuestion: "आपका प्रश्न",
    askButton: "पूछें",
    startHere: "यहां शुरू करें",
    ready: "तैयार",
    whatModeFor: "यह अवस्था किसलिए है",
    deepChecks: "गहन जांच",
    blindSpots: "अदृश्य हिस्से",
    maturitySignals: "परिपक्वता के संकेत",
    modeGuidance: "अवस्था-मार्गदर्शन",
    change: "बदलें",
    showDetails: "विवरण दिखाएँ",
    hideDetails: "विवरण छिपाएँ",
    modeGuidancePreview: "इस दृश्य को केंद्रित रखें। जब आप गहन जांच, अंधे हिस्से, और परिपक्वता के संकेत देखना चाहें, तब इसे फैलाएँ।",
    trustLayer: "विश्वास परत",
    preferencesTitle: "भाषा और क्षेत्र",
    language: "भाषा",
    region: "क्षेत्र",
    bible: "बाइबिल",
    voiceControls: "आवाज़ नियंत्रण",
    available: "उपलब्ध",
    englishFallback: "अंग्रेज़ी फ़ॉलबैक",
    greetingMorning: "सुप्रभात",
    greetingAfternoon: "नमस्कार",
    greetingEvening: "शुभ संध्या",
    greetingFallback: "वापसी पर स्वागत है",
    greetingIntent: "आइए आज एक बुद्धिमान अगला कदम चुनें।",
    personalizedPriority: "व्यक्तिगत प्राथमिकता",
    whatNext: "मुझे आगे क्या करना चाहिए?",
    whatNextBody: "Aletheia पहले एक बुद्धिमान अगला कदम चुनता है। जब आप कुछ नया शुरू करना चाहें, तब प्रश्न और मोड नियंत्रण पास ही रहते हैं।",
    personalizationNudgeTitle: "क्या आप और व्यक्तिगत सलाह चाहते हैं?",
    personalizationNudgeBody: "धन, काम, या लय के बारे में एक विवरण जोड़ें।",
    continueDecision: "इस निर्णय को जारी रखें",
    askOneQuestion: "एक प्रश्न पूछें",
    askOneQuestionBody: "उस दबाव या निर्णय से शुरू करें जिसे आप अभी ढो रहे हैं।",
    askNewQuestion: "नया प्रश्न पूछें",
    askNewQuestionBody: "साथी इनपुट और ज्ञान मोड पास ही बने रहते हैं।",
    reflectToday: "आज चिंतन करें",
    reviewPattern: "पैटर्न की समीक्षा करें",
    enableNotifications: "सूचनाएँ सक्षम करें",
    enableSync: "संगति चालू करें",
    notificationPromptBody: "हर दिन एक शांत ज्ञान-सूचना प्राप्त करें।",
    syncDevicesBody: "निर्णयों और चिंतन को सभी उपकरणों पर एक-साथ रखें।",
    startDecision: "निर्णय शुरू करें",
    startDecisionBody: "एक महत्वपूर्ण विकल्प को समय के साथ ट्रैक करें।",
    tinyPractice: "छोटी प्रैक्टिस",
    todaysCompanion: "आज का साथी",
    todayPrefix: "आज",
    wisdomPrinciple: "ज्ञान सिद्धांत",
    reflectionQuestion: "प्रश्न",
    whatINotice: "जो मैं देखता हूँ",
    context: "संदर्भ",
    application: "प्रयोग",
    carryThisToday: "इसे आज साथ रखें",
    carryWithMe: "मेरे साथ रखें",
    weeklyWisdomReview: "साप्ताहिक ज्ञान समीक्षा",
    weeklyReviewTitle: "आपके सप्ताह पर शांत नज़र",
    weeklyReviewBody: "कोई दबाव नहीं। बस देखें कि {pattern} आपकी समझ को कैसे आकार दे रहा है।",
    todayScriptureLabel: "शास्त्र",
    todayQuestionLabel: "आज का प्रश्न",
    todayActionsLabel: "आज के कार्य",
    weeklyReviewHeading: "आपकी साप्ताहिक समीक्षा",
    weeklyReviewLastWeekLabel: "पिछला सप्ताह",
    nextFaithfulStep: "अगला निष्ठावान कदम",
    askAboutThis: "इस बारे में पूछें",
    saveToRuleOfLife: "जीवन नियम में सहेजें",
    carryingToday: "आज साथ ले जा रहे हैं",
    currentCounsel: "वर्तमान सलाह",
    modeShapesCounsel: "इस सलाह को इस तरह आकार दे रहा है",
    trackThisDecision: "इस निर्णय को ट्रैक करें",
    saveAsReflection: "चिंतन के रूप में सहेजें",
    createCounselSummary: "सलाह सारांश बनाएं",
    goDeeper: "और गहराई में जाएँ",
    waitThreeDays: "3 दिन प्रतीक्षा करें",
    shareAnswerPrompt: "Aletheia को उस व्यक्ति के साथ साझा करें जिसे इस तरह की सलाह से लाभ हो सकता है।",
    sharePrivacyNote: "इसमें केवल ऐप लिंक साझा होता है, आपका प्रश्न या Aletheia का निजी उत्तर नहीं।",
    shareAletheia: "Aletheia साझा करें",
    feedbackQuestion: "क्या यह सलाह उपयोगी थी?",
    feedbackHelpful: "उपयोगी",
    feedbackMildlyHelpful: "थोड़ी उपयोगी",
    feedbackTooVague: "बहुत अस्पष्ट",
    feedbackTooPreachy: "बहुत उपदेशात्मक",
    feedbackNotRelevant: "उपयुक्त नहीं",
    badgesFormation: "बैज / गठन",
    firstReflectionSaved: "पहला चिंतन सहेजा गया",
    firstDecisionTracked: "पहला निर्णय ट्रैक हुआ",
    soughtCounsel: "सलाह ली",
    waitingModeUsed: "प्रतीक्षा अवस्था का उपयोग किया गया",
    ruleOfLifeCreated: "जीवन नियम बनाया",
    notificationsEnabled: "सूचनाएँ सक्षम की गईं",
    sevenDaysPractice: "ज्ञान अभ्यास के 7 दिन",
    formationNote: "ये गठन के शांत संकेत हैं, न कि पीछा करने योग्य लक्ष्य। पहला मील का पत्थर आम तौर पर एक चिंतन सहेजने से शुरू होता है।",
    milestoneShareTitle: "क्या आप किसी को जानते हैं जो बड़ा निर्णय ले रहा है?",
    milestoneShareBody: "आप अपने खाते से कुछ भी निजी साझा किए बिना उन्हें Aletheia पर आमंत्रित कर सकते हैं।",
    welcomeCounsel: "कोई वास्तविक निर्णय, दबाव, या पैसे का प्रश्न लेकर आएँ। मैं क्यूरेटेड ज्ञान पुस्तकालय से उत्तर दूँगा, स्पष्टता के साथ और बिना वित्तीय वादों के।",
    trustScriptureBody: "शास्त्र संदर्भ Aletheia के क्यूरेटेड ज्ञान पुस्तकालय से आते हैं। यदि कोई पद दिखाई देता है, तो आप उसे टैप करके संदर्भ और उसका महत्व देख सकते हैं।",
    trustBoundaryBody: "Aletheia परिणामों का वादा नहीं करेगा, बाजारों की भविष्यवाणी नहीं करेगा, दैवीय निश्चितता का दावा नहीं करेगा, या योग्य वित्तीय, कानूनी, कर, चिकित्सा, या देहाती परामर्श की जगह नहीं लेगा।",
    trustMemoryBody: "साइन-इन मेमोरी निर्णयों, चिंतनों, सलाह और जीवन-नियमों में निरंतरता में मदद करती है। इसे अनावश्यक निजी विवरण उजागर किए बिना मार्गदर्शन को अधिक व्यक्तिगत बनाना चाहिए।",
    trustConnectedDataBody: "भविष्य के स्वास्थ्य, वित्त, या डिवाइस एकीकरण को स्पष्ट अनुमति के साथ, डिफ़ॉल्ट रूप से बंद, और केवल उसी सटीक डेटा तक सीमित होना चाहिए जिसे उपयोगकर्ता जोड़ना चुनता है।",
    accountNextEyebrow: "खाते में अगला",
    accountNextReviewSyncFormation: "संगति और गठन की समीक्षा करें",
    accountNextSignInPortable: "Aletheia को अपने साथ ले जाने के लिए साइन इन करें",
    accountNextActiveBody: "आपका खाता सक्रिय है। जब ज़रूरत हो, प्राथमिकताएँ, इतिहास, और गठन मील के पत्थर देखें।",
    accountNextSyncBody: "संगति सक्रिय है। यदि यह उपकरण उसे पाए, तो एक शांत दैनिक ज्ञान-सूचना चालू करें।",
    accountNextGuestBody: "निर्णय, चिंतन, प्राथमिकताएँ, सलाह, और सूचनाएँ उपकरणों में एक-साथ रखने के लिए Google या ईमेल का उपयोग करें।",
    accountManageSummary: "साइन-इन, संगति, भाषा, सूचनाएँ, इतिहास, और गठन मील के पत्थरों को ज्ञान साथी को भीड़ दिए बिना प्रबंधित करें।",
    accountSignedInAs: "साइन इन किया गया है",
    accountSignInOrGuest: "साइन इन करें या अतिथि के रूप में जारी रखें",
    accountSyncActive: "संगति सक्रिय है।",
    accountNotificationsNotEnabled: "सूचनाएँ अभी सक्षम नहीं हैं।",
    accountGuestSummary: "अपना इतिहास, प्राथमिकताएँ, और निर्णय सुरक्षित रखने के लिए साइन इन करें।",
    accountPreferencesEyebrow: "प्राथमिकताएँ",
    accountPreferencesSummary: "भाषा, बाइबिल अनुवाद, रूप, क्षेत्र, और आवाज़ यहीं रहें ताकि साथी शांत रहे।",
    accountContextActive: "संदर्भ सक्रिय",
    accountContextPaused: "संदर्भ रुका हुआ",
    accountArea: "क्षेत्र",
    accountAreas: "क्षेत्र",
    accountAdded: "जोड़ा गया",
    accountManualContextSummary: "मैन्युअल संदर्भ वैकल्पिक और निजी है। केवल वही जोड़ें जो Aletheia की सलाह को आकार दे।",
    accountDailyWisdomEnabled: "दैनिक ज्ञान सक्षम",
    accountNotificationsSummaryEnabled: "Aletheia आपकी सहेजी हुई स्थानीय समय-प्राथमिकता का उपयोग करेगा।",
    accountNotificationsSummaryDisabled: "जब यह उपकरण तैयार हो, एक शांत दैनिक याद दिलाने वाला चालू करें।",
    accountInstallTitle: "Aletheia को होम स्क्रीन पर जोड़ें",
    accountInstallSummary: "इंस्टॉल निर्देश तब तक छिपे रहते हैं जब तक किसी को ऐप-जैसी सेटअप की ज़रूरत न हो।",
    accountInstallEyebrow: "Aletheia इंस्टॉल करें",
    accountInviteTitle: "किसी को निजी तौर पर आमंत्रित करें",
    accountInviteSummary: "सिर्फ Aletheia लिंक साझा करें, निजी प्रश्न, डायरी, या सलाह नहीं।",
    accountInviteEyebrow: "किसी को आमंत्रित करें",
    accountHistoryConversations: "वार्तालाप",
    accountHistoryDecisions: "निर्णय",
    accountHistoryReflections: "चिंतन",
    accountHistorySummary: "इतिहास तब तक संक्षिप्त रहता है जब तक आप सहेजे गए को देखना न चाहें।",
    accountStatConversations: "वार्तालाप",
    accountStatDecisions: "निर्णय",
    accountStatJournalEntries: "जर्नल प्रविष्टियाँ",
    accountHistoryEmptyBody: "एक सच्चे प्रश्न या दबाव वाले निर्णय से शुरू करें। Aletheia रिकॉर्ड को शांत और उपयोगी रखेगा।",
    accountTrustPostureTitle: "विश्वास और गोपनीयता की स्थिति",
    accountTrustPostureSummary: "सीमाएँ, सहेजा गया डेटा, और साझा करने के नियम देखें।",
    accountBoundariesTitle: "Aletheia की सुरक्षा सीमाएँ",
    accountBoundariesSummary: "ज़रूरत पड़ने पर ऐप की सुरक्षा सीमाएँ दिखाई देती हैं, लगातार बाधा नहीं बनतीं।",
    accountBoundariesBody: "ये सीमाएँ आपको हानिकारक AI सलाह से बचाती हैं और Aletheia को उसके उद्देश्य के प्रति सच्चा रखती हैं।",
    accountFormationPrefix: "गठन",
    accountQuietMilestoneSingular: "शांत मील का पत्थर",
    accountQuietMilestonePlural: "शांत मील के पत्थर",
    accountFormationSummary: "गठन अभ्यास का शांत रिकॉर्ड है, स्कोरबोर्ड नहीं।",
  },
};

export type UiText = NonNullable<(typeof uiText)[LanguageCode]> & typeof enTranslations;
export const englishText: UiText = uiText.en as UiText;

